# Exemplos Aplicados

### Exemplo Aplicado

Nesta seção, com o conjunto de dados dos estudantes disponível em [SOGA-Py](https://www.geo.fu-berlin.de/en/v/soga-py/Basics-of-statistics/Hypothesis-Tests/index.html). Você pode carregá-lo diretamente como um recurso da *web*. Vamos importar o conjunto de dados para o `Python` como um objeto **DataFrame** do pandas utilizando o método `read_csv`:

```{python}
import pandas as pd
import numpy as np

estudantes = pd.read_csv("dados/students.csv")

estudantes.head()
```

O conjunto de dados **estudantes** consiste em 8.239 linhas, cada uma representando um estudante específico, e 16 colunas, cada uma correspondendo a uma variável/característica relacionada a esse estudante. Neste estudo, considera-se o conjunto completo de estudantes disponível na base de dados como a população de interesse. Além disso, a variável de interesse é o peso (massa corporal).

> Aqui iremos considerar a variância conhecida, ou seja, iremos calcular diretamente a partir dos dados completos.

### Variância e desvio-padrão populacionais

Como a base contém todos os 8.239 estudantes considerados neste estudo, a variância calculada corresponde à variância populacional.

```{python}
N = len(estudantes)
sigma2 = estudantes["weight"].var(ddof=0) # variância populacional 
sigma = estudantes["weight"].std(ddof=0) # desvio-padrão populacional 

print(f"Tamanho da população: {N}") 
print(f"Variância populacional: {sigma2:.2f}") 
print(f"Desvio-padrão populacional: {sigma:.2f} kg")
```

### Objetivo

Avaliar se a massa corporal média dos estudantes difere da massa corporal média da população adulta europeia, reportada por [Walpole et al. (2012)](https://link.springer.com/article/10.1186/1471-2458-12-439) como 70,8 kg. As hipóteses são:

$$H_0: \mu = 70,8$$

e

$$H_A: \mu \neq 70,8$$ 
em que $\mu$ representa a massa corporal média dos estudantes.

### Cálculo do tamanho mínimo de amostra

Foi adotada uma diferença mínima detectável de 2 kg em relação à média de referência de 70,8 kg. O tamanho amostral foi calculado para garantir poder estatístico de 80% e nível de significância de 5%, ou seja,

1.  nível de confiança = 95%;
2.  poder do teste = 80%;
3.  diferença mínima detectável = 2 kg.

```{python}
from scipy.stats import norm

alpha = 0.05 
power = 0.80 
delta = 2.0 

z_alpha = norm.ppf(1 - alpha/2) 
z_beta = norm.ppf(power) 
n0 = ((z_alpha + z_beta) * sigma / delta)**2 

print(f"Tamanho inicial da amostra: {np.ceil(n0):.0f}")
```

Como a população possui apenas 8.239 indivíduos, aplicaremos uma correção para população finita:

```{python}
n = (n0 * N)/(n0 + N - 1) 
n = int(np.ceil(n)) 

print(f"Tamanho corrigido da amostra: {n}")
```

### Seleção da amostra aleatória

```{python}
amostra = estudantes.sample(n=n, replace=False, random_state=123 ) 

amostra.head()
```

### Teste Z para uma média com variância conhecida

```{python}
mu0 = 70.8 

xbar = amostra["weight"].mean() 

z = (xbar - mu0)/(sigma/np.sqrt(n)) 

print(f"Média amostral: {xbar:.2f}") 
print(f"Estatística Z: {z:.4f}")
```

### Cálculo do p-valor

```{python}
from scipy.stats import norm

p_value = 2 * (1 - norm.cdf(abs(z)))

print(f"Valor-p: {p_value:.6f}")

```

### Regra de Decisão

```{python}
alpha = 0.05 

if p_value < alpha: 
  print("Rejeita H0") 
else: 
  print("Não rejeita H0")
```

### Intervalo de confiança de 95%

```{python}
z_crit = norm.ppf(0.975)

erro = z_crit * sigma/np.sqrt(n)

li = xbar - erro
ls = xbar + erro

print(f"IC95%: ({li:.2f}, {ls:.2f})")

```

### Conclusão

Como o $p$-valor calculado (0,004493) é consideravelmente inferior ao nível de significância adotado (0,05), a decisão estatística é rejeitar a hipótese nula, ou seja, de que a massa corporal média dos estudantes é igual a massa corporal média da população adulta europeia. Sendo assim, existe evidência estatisticamente significativa de que a média populacional é diferente do valor inicialmente suposto.

Note que a média populacional é:

```{python}
mu_pop = estudantes["weight"].mean()

print(f"Média populacional: {mu_pop:.2f} kg")
```

## Exemplo Aplicado

Agora iremos considerar a situação mais realista que é quando a variância populacional é desconhecida. Para calcular o tamanho mínimo de amostra iremos precisar estimar a variância populacional. Para isto, iremos usar uma amostra piloto.

### Amostra piloto

```{python}
amostra_piloto = estudantes.sample(n=50, replace=False, random_state=123 ) 

n_piloto = len(amostra_piloto)
s2 = amostra_piloto["weight"].var(ddof=1) # variância amostral 
s = amostra_piloto["weight"].std(ddof=1) # desvio-padrão amostral

print(f"Tamanho da amostra piloto: {n_piloto}") 
print(f"Variância amostral: {s2:.2f}") 
print(f"Desvio-padrão amostral: {s:.2f} kg")

amostra_piloto.head()

```

### Cálculo do tamanho mínimo de amostra

```{python}
from scipy.stats import t

alpha = 0.05 
power = 0.80 
delta = 2.0 

z_alpha = norm.ppf(1 - alpha/2) 
z_beta = norm.ppf(power) 

n0 = ((z_alpha + z_beta) * s/delta)**2

print(f"Tamanho inicial da amostra (usando quantil da normal padrão): {np.ceil(n0):.0f}")


t_alpha = t.ppf(1 - alpha/2, df = n0-1)
t_beta = t.ppf(power, df = n0-1)
n1 = ((t_alpha + t_beta) * s/delta)**2 

print(f"Tamanho inicial da amostra (usando quantil da t-student): {np.ceil(n1):.0f}")
```

Como a população possui apenas 8.239 indivíduos, aplicaremos uma correção para população finita:

```{python}
n = (n1 * N)/(n1 + N - 1) 
n = int(np.ceil(n)) 

print(f"Tamanho corrigido da amostra: {n}")
```

### Seleção da amostra aleatória

Iremos considerar os estudantes coletados na amostra piloto na amostra final considerada para o estudo. Assim, iremos selecionar mais 81 estudantes. Como a semente aleatória é a mesma da amostra piloto, basta selecionar normalmente os 131 estudantes.

```{python}
amostra = estudantes.sample(n=n, replace=False, random_state=123 ) 

amostra.head()
```

### Verificando normalidade dos dados

Agora, vamos testar a suposição de normalidade plotando um gráfico de probabilidade normal, frequentemente chamado de QQ plot. Se a variável tiver distribuição normal, o gráfico de probabilidade normal deverá ser aproximadamente linear.

```{python}
import matplotlib.pyplot as plt
import scipy.stats as stats

fig, ax = plt.subplots()

stats.probplot(amostra["weight"], dist="norm", plot=ax)

ax.set_title("Q-Q plot (amostra)")
ax.set_ylabel("Quantis amostrais")
ax.set_xlabel("Quantis teóricos")


plt.show()
```

Observamos que os dados da amostra apresentam algum ruído, os desvios da linha reta na parte inferior sugerem que a distribuição dos dados é ligeiramente assimétrica, como pode ser visto no histograma abaixo.

```{python}
plt.hist(amostra["weight"], bins=20)
plt.title("Histograma da variável weight")
plt.xlabel("Weight")
plt.ylabel("Frequência")
plt.show()
```

Podemos usar algum teste de hipótese para teste a normalidade dos dados. As hipóteses do teste são:

- Hipótese Nula: Os dados vem de uma distribuição normal.

- Hipótese Alternativa: Os dados observados não vêm da distribuição normal.

```{python}
from statsmodels.stats.diagnostic import lilliefors

lilliefors(amostra["weight"], dist='norm')
```

```{python}
from scipy.stats import anderson

anderson(amostra["weight"], dist='norm')
```

```{python}
from scipy.stats import jarque_bera

jarque_bera(amostra["weight"])
```

```{python}
from scipy.stats import normaltest

normaltest(amostra["weight"]) #teste de D’Agostino-Pearson
```

Se considerarmos um nível de significância de 1%, temos que a maioria dos testes não rejeita a hipótese de que os dados são provenientes de uma população normal. No entanto, ao considerarmos um nível de 5% temos que o resultado se inverte.

### Teste t para uma média com variância desconhecida

```{python}
mu0 = 70.8 

xbar = amostra["weight"].mean() 
s_amostral = amostra["weight"].std(ddof=1)

tc = (xbar - mu0)/(s_amostral/np.sqrt(n)) 

print(f"Desvio-Padrão amostral: {s_amostral:.2f}")
print(f"Média amostral: {xbar:.2f}") 
print(f"Estatística t: {tc:.4f}")
```

### Cálculo do p-valor

```{python}
from scipy.stats import t
gl = n-1

p_value = 2 * (1 - t.cdf(x=abs(tc), df = gl))

print(f"Valor-p: {p_value:.6f}")

```

```{python}
from statsmodels.stats.weightstats import DescrStatsW

d = DescrStatsW(amostra["weight"])

t_stat, p_value, gl = d.ttest_mean(mu0)

print(d)
print(f"t = {t_stat:.4f}")
print(f"p = {p_value:.6f}")
print(f"gl = {gl:.0f}")
```

### Regra de Decisão

```{python}
alpha = 0.05 

if p_value < alpha: 
  print("Rejeita H0") 
else: 
  print("Não rejeita H0")
```

### Intervalo de confiança de 95%

```{python}

t_crit = t.ppf(1-alpha/2, df = gl)

erro = t_crit * s_amostral/np.sqrt(n)

li = xbar - erro
ls = xbar + erro

print(f"IC95%: ({li:.2f}, {ls:.2f})")

```

### Exemplo Aplicado

Segundo a [*Deutsche Bischofskonferenz (Conferência Episcopal Alemã, DBK)*](https://www.vaticannews.va/pt/igreja/news/2024-06/alemanha-igreja-catolica-dados-estatisticos.html), aproximadamente 24% da população alemã se declara católica. Neste estudo, pretende-se investigar se a proporção de estudantes católicos difere da proporção observada na população geral da Alemanha.

Para isso, será obtida uma amostra aleatória de estudantes, a partir da qual será realizada uma inferência estatística sobre a proporção populacional. Em particular, o objetivo é testar a hipótese de igualdade entre a proporção de católicos no grupo de estudantes e o valor de referência de 0,24. Iremos considerar a seguintes hipótese:

$$H_0: p = 0,24$$

e

$$H_A: p \neq 0,24$$ 
em que $p$ representa a proporção dos estudantes que são católicos.

#### Cálculo do tamanho mínimo de amostra

Desejamos ter 80% de poder para detectar diferenças de pelo menos 2 pontos percentuais em relação ao valor de referência. Além disso, o valor de $p=0.5$ maximiza a variância $p(1-p)$ e, portanto, produz o maior tamanho amostral possível.

```{python}
from scipy.stats import norm

alpha = 0.05 
power = 0.80 
delta = 0.02
p0 = 0.5
p1 = np.abs(p0-delta)

z_alpha = norm.ppf(1 - alpha/2) 
z_beta = norm.ppf(power) 
n0 = ((z_alpha*np.sqrt(p0*(1-p0)) + z_beta*np.sqrt(p1*(1-p1)) )/delta)**2 

print(f"Tamanho inicial da amostra: {np.ceil(n0):.0f}")

```

Como a população possui apenas 8.239 indivíduos, aplicaremos uma correção para população finita:

```{python}
n = (n0 * N)/(n0 + N - 1) 
n = int(np.ceil(n)) 

print(f"Tamanho corrigido da amostra: {n}")
```

Agora iremos retirar uma amostra piloto para estimar a proporção de estudantes que são católicos.

```{python}
amostra_piloto = estudantes.sample(n=50, replace=False, random_state=2026) 

proporcao_catolica = (amostra_piloto["religion"] == "Catholic").mean()

print(f"Proporção de Católicos na amostra piloto: {proporcao_catolica}")

```

Agora, o tamanho de amostra mínimo será:

```{python}
from scipy.stats import norm

alpha = 0.05 
power = 0.80 
delta = 0.02
p0 = proporcao_catolica
p1 = np.abs(p0-delta)


z_alpha = norm.ppf(1 - alpha/2) 
z_beta = norm.ppf(power) 
n0 = n0 = ((z_alpha*np.sqrt(p0*(1-p0)) + z_beta*np.sqrt(p1*(1-p1)) )/delta)**2 

n = (n0 * N)/(n0 + N - 1) 
n = int(np.ceil(n)) 

print(f"Tamanho da amostra : {np.ceil(n0):.0f}")
print(f"Tamanho da amostra corrigido: {np.ceil(n):.0f}")

```

#### Seleção da amostra aleatória

Agora iremos selecionar aleatoriamente os 2905 estudantes.

```{python}
amostra = estudantes.sample(n=n, replace=False, random_state=2026) 

amostra.head()
```

#### Teste Z para uma proporção

```{python}
p0 =  0.24 

p_amostral = (amostra["religion"] == "Catholic").mean()

z = (p_amostral - p0)/(np.sqrt(p0*(1-p0)/n)) 

print(f"Proporção amostral: {p_amostral:.2f}") 
print(f"Estatística Z: {z:.4f}")
```

#### Cálculo do $p_{\text{valor}}$

```{python}
from scipy.stats import norm

p_value = 2 * (1 - norm.cdf(abs(z)))

print(f"Valor-p: {p_value:.6f}")

```

```{python}
from statsmodels.stats.proportion import proportions_ztest

x = (amostra["religion"] == "Catholic").sum()

stat, p_value = proportions_ztest(
    count=x,
    nobs=n,
    value=0.24,
    prop_var = p0, #por padrao usa a proporcao amostral
    alternative='two-sided'
)

print(f"Estatística Z: {stat:.4f}")
print(f"Valor-p: {p_value:.6f}")
```

::: callout-note
## Observação

A função `proportions_ztest()` do pacote `statsmodels` utiliza, por padrão, a proporção amostral para estimar a variância da estatística de teste.
:::

#### Regra de Decisão

```{python}
alpha = 0.05 

if p_value < alpha: 
  print("Rejeita H0") 
else: 
  print("Não rejeita H0")
```

#### Intervalo de confiança de 95%

```{python}
z_crit = norm.ppf(1-alpha/2)

erro = z_crit * np.sqrt(p_amostral*(1-p_amostral)/n)

li = p_amostral - erro
ls = p_amostral + erro

print(f"IC95%: ({li:.2f}, {ls:.2f})")

```

#### Conclusão

Ao nível de significância de 5%, os dados fornecem evidências suficientes para concluir que a proporção de estudantes católicos difere da proporção de 24% observada na população alemã segundo a DBK. O resultado sugere que a composição religiosa da população estudantil não reflete exatamente a composição religiosa da população geral.

### Exemplo Prático

O `Python` permite realizar um teste t com variâncias combinadas utilizando a função `ttest_ind_from_stats()`, disponível no módulo `stats` do pacote `scipy`.

> No exemplo, assumiremos que as variâncias das duas amostras são iguais. Portanto, o argumento `equal_var` da função será definido como `True`.

Para praticar a aplicação do teste t com variâncias combinadas, utilizaremos o conjunto de dados *estudantes*.

#### Hipóteses

Queremos verificar se existe diferença entre os ganhos de homens e mulheres graduados. Desta forma, queremos testar as seguintes hipóteses:

$$H_0: \mu_1 = \mu_2$$

e

$$H_A: \mu_1 \neq \mu_2$$ 

em que $\mu_1$ e $\mu_2$ representam as médias salariais dos estudantes graduados do sexo masculino e feminino, respectivamente.

#### Preparação dos dados

Começamos com a preparação dos dados, que inclui as seguintes etapas:

1.  Subdividimos o conjunto de dados com base na variável binária `graduated`, que indica se o estudante já se formou. O valor 1 representa “formado”, enquanto 0 indica “não formado”.

2.  Em seguida, dividimos o conjunto de dados por gênero (masculino e feminino).

3.  Depois, selecionamos aleatoriamente uma amostra de 50 estudantes do sexo feminino e 50 do sexo masculino de cada subconjunto e extraímos a média do salário anual (em euros) como variável de interesse.

Armazenaremos as informações de salário dos grupos masculino e feminino em variáveis separadas chamadas `amostra_homens` e `amostra_mulheres`. A informação relevante está armazenada na coluna `salary`.

```{python}
estudantes_graduados = estudantes.loc[estudantes.graduated == 1] #filta estudantes formados

homens_graduados = estudantes_graduados.loc[estudantes.gender == "Male"] #separa homens formados

mulheres_graduadas = estudantes_graduados.loc[estudantes.gender == "Female"] #separa mulheres formadas

n_piloto = 30

amostra_homens_piloto = homens_graduados.sample(n_piloto, random_state = 24, replace = False)["salary"] #Sorteia amostra de homens e pega salário

amostra_mulheres_piloto = mulheres_graduadas.sample(n_piloto, random_state = 24, replace = False)["salary"] #Sorteia amostra de mulheres e pega salário

s21_piloto = np.var(amostra_homens_piloto, ddof = 1)
s22_piloto = np.var(amostra_mulheres_piloto, ddof = 1)

n1 = n2 = n_piloto


alpha = 0.05 
power = 0.90 
delta = 5000 

z_alpha = norm.ppf(1 - alpha/2) 
z_beta = norm.ppf(power) 
n0 = (((z_alpha + z_beta)/ delta)**2)*(s21_piloto + s22_piloto) 

print(f"Razão entre as variâncias da amostra piloto: {np.sqrt(s21_piloto)/np.sqrt(s22_piloto):.2f}")
print(f"Tamanho inicial da amostra: {np.ceil(n0):.0f}")

```

A razão entre os desvios-padrão é aproximadamente 1,34 e, portanto, nota-se que o suposição de igualdade dos desvios-padrão populacionais parece razoável.

```{python}
tol = 1
max_iter = 100
n0 = np.ceil(n0)

for i in range(max_iter):

    gl = 2*n0 - 2

    t_alpha = t.ppf(1 - alpha/2, df=gl)
    t_beta = t.ppf(power, df=gl)

    n_novo = (((t_alpha + t_beta)/delta)**2) * (s21_piloto + s22_piloto)

    # normalmente arredondamos para cima
    n_novo = np.ceil(n_novo)

    if n_novo == n0:
        break

    n0 = n_novo

n = int(np.ceil(n0)) 

print(f"Convergiu em {i+1} iterações")
print(f"n por grupo = {int(n)}")
```

### Seleção da amostra

```{python}
amostra_homens = homens_graduados.sample(n, random_state = 24, replace = False)["salary"] #Sorteia amostra de homens e pega salário

amostra_mulheres = mulheres_graduadas.sample(n, random_state = 24, replace = False)["salary"] #Sorteia amostra de mulheres e pega salário

```

```{python}
import matplotlib.pyplot as plt
import scipy.stats as stats

plt.figure(figsize=(12,5))

ax = plt.subplot(1, 2, 1)
qq = stats.probplot(amostra_homens, dist="norm", plot = plt)
ax.set_title("Q-Q plot para homens (amostra)")
ax.set_ylabel("Quantis Amostrais")

ax = plt.subplot(1, 2, 2)
qq = stats.probplot(amostra_mulheres, dist="norm", plot = plt)
ax.set_title("Q-Q plot para mulheres (amostra)")
ax.set_ylabel("Quantis Amostrais")
```

Observamos que os dados da amostra apresentam certo nível de ruído, mas ainda seguem aproximadamente uma distribuição normal. Além disso, verificamos se os desvios-padrão das duas populações são aproximadamente iguais. Como regra prática, a condição de igualdade dos desvios-padrão populacionais é considerada satisfeita se a razão entre o maior e o menor desvio-padrão amostral for inferior a 2.

```{python}
s1 = np.std(amostra_homens, ddof = 1)
s2 = np.std(amostra_mulheres, ddof = 1)

n1 = n2 = n

sc = np.sqrt(((n1 - 1) * s1**2 + (n2 - 1) * s2**2) / (n1 + n2 - 2))

print(f"Razão entre os desvios-padrão: {s1/s2:.2f}")
```

Podemos analisar a suposição de igualdade das variâncias, fazendo um boxplot por gênero.

```{python}
import seaborn as sns

plt.figure(figsize=(11,5))

amostra = pd.melt(pd.DataFrame({'Homens': amostra_homens.values, 'Mulheres': amostra_mulheres.values}))

amostra.columns = ["Gênero", "Salário Anual em Euros"]

sns.boxplot(x='Gênero', 
            y='Salário Anual em Euros', 
            hue='Gênero',
            data=amostra).set(title='Dados Amostrais')

```

#### Estatística de Teste

```{python}
gl = 2*n-2
xbar1 = np.mean(amostra_homens)
xbar2 = np.mean(amostra_mulheres)

t_cal = (xbar1 - xbar2) / (sc * np.sqrt((1/n1) + (1/n2)))

p_valor = 1 - t.cdf(t_cal, df = gl)
p_valor

print(f"Graus de Liberdade: {gl: 0f}")
print(f"Estatística de Teste: {t_cal:.2f}")
print(f"P-valor: {p_valor:.4f}")

```

#### Regra de Decisão

```{python}
alpha = 0.05 

if p_valor < alpha: 
  print("Rejeita H0") 
else: 
  print("Não rejeita H0")
```

#### Usando `scipy`

```{python}
from scipy import stats

resultado_teste = stats.ttest_ind(amostra_homens, amostra_mulheres, 
                              equal_var = True, 
                              alternative = "two-sided")

resultado_teste
```

#### Conclusão

Ao nível de significância de 1%, os dados fornecem evidências muito fortes para concluir que o salário médio dos graduados do sexo masculino é diferente do salário médio das graduadas do sexo feminino.

## Inferências para duas médias populacionais com amostras independentes e variâncias desiguais

No exemplo, anterior poderíamos aplicar o teste de maneira prática e fácil usando a função `stats.ttest_ind()` com o argumento `equal_var = False`.

```{python}
resultado_teste_Welch = stats.ttest_ind(amostra_homens, amostra_mulheres, 
                              equal_var = False, 
                              alternative = "two-sided")

resultado_teste_Welch
```

### Exemplo Prático

Para ilustrar a aplicação do teste t pareado para amostras dependentes, estamos interessados em verificar se um tutorial online de Estatística auxilia os estudantes a melhorar seu desempenho acadêmico.

Existem três variáveis de interesse no conjunto de dados dos estudantes:

1.  A variável \`online.tutorial é uma variável binária que assume valor 1 se o estudante concluiu o tutorial online de Estatística e 0 caso contrário.

2.  As variáveis `score1` e `score2` representam as notas (de 0 a 100) obtidas em duas avaliações de Matemática e Estatística. Quanto maior a nota, melhor o desempenho do estudante.

3.  Observe que a primeira avaliação ocorre antes da participação dos estudantes no tutorial online de Estatística. A participação no tutorial é opcional, mas as duas avaliações são obrigatórias para todos os estudantes. A primeira prova (`score1`) é realizada no início do terceiro semestre, enquanto a segunda prova (`score2`) é realizada ao final do terceiro semestre.

Neste contexto, há duas questões de pesquisa de interesse:

- Verificar se o grupo de estudantes que participou do tutorial online de Estatística apresentou melhor desempenho na segunda avaliação em comparação com a primeira avaliação.

- Avaliar o desempenho do grupo de estudantes que não participou do tutorial online, comparando os resultados obtidos na primeira e na segunda avaliação.

### Hipóteses

A hipótese nula afirma que não há diferença entre as médias das notas dos dois exames:

$$H_0: \mu_1 = \mu_2$$

A hipótese alternativa indica que os alunos têm melhor desempenho no segundo exame:

$$H_A: \mu_1 < \mu_2$$

Isso caracteriza um teste de hipótese unilateral à esquerda

### Preparação dos Dados e Amostra Piloto

```{python}
subconjunto = estudantes.loc[estudantes["online.tutorial"] == 1]

n_piloto = 50

amostra_piloto = subconjunto.sample(n_piloto, random_state = 24)[["score1", "score2"]]

d_piloto = (amostra_piloto["score1"] - amostra_piloto["score2"]).to_frame(name="diferenca")

sd_piloto = np.std(d_piloto["diferenca"])

print(f"Desvio-padrão da diferença (amostra piloto) : {sd_piloto:.2f}")

```

## Cálculo do tamanho amostral

```{python}
from scipy.stats import t

alpha = 0.01 
power = 0.80 
delta = 2.0 

z_alpha = norm.ppf(1 - alpha) 
z_beta = norm.ppf(power) 

n0 = ((z_alpha + z_beta) * sd_piloto/delta)**2

print(f"Tamanho inicial da amostra (usando quantil da normal padrão): {np.ceil(n0):.0f}")


t_alpha = t.ppf(1 - alpha, df = n0-1)
t_beta = t.ppf(power, df = n0-1)
n1 = ((t_alpha + t_beta) * s/delta)**2
N = 3182
n = (n1 * N)/(n1 + N - 1) 
n = int(np.ceil(n)) 

print(f"Tamanho mínimo da amostra (usando quantil da t-student): {n:.0f}")
```

### Seleção da Amostra

```{python}
amostra = subconjunto.sample(n, random_state = 24)[["score1", "score2"]]
```

### Estatística de Teste

```{python}
d = (amostra["score1"] - amostra["score2"]).to_frame(name="diferenca")

diff_mean = np.mean(d)
diff_std = np.sqrt((np.sum(d**2) - ((np.sum(d)**2) / n)) / (n - 1))

t_value = diff_mean / (diff_std / np.sqrt(n))


p = t.cdf(t_value, df = n-1)


print(f"EGraus de Liberdade: {n-1: 0f}")
print(f"Estatística de Teste: {t_value:.2f}")
print(f"P-valor: {p:.4f}")
```

#### Regra de Decisão

```{python}
alpha = 0.01 

if p < alpha: 
  print("Rejeita H0") 
else: 
  print("Não rejeita H0")
```

#### Usando funções do Python

```{python}
test_result = stats.ttest_rel(amostra["score1"], amostra["score2"], alternative = "less")

test_result
```

#### Conclusão

Ao nível de significância de 1%, os dados fornecem evidência forte para concluir que as notas dos estudantes em exames melhoram após realizarem um tutorial online de aprendizagem de estatística.

## Referências
