<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.23">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Demonstrações</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 1em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Unidade8.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-1fe81d0376b2c50856e68e651e390326.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-6f6599830d51be977da3b6af758f8eff.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-1fe81d0376b2c50856e68e651e390326.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2641b481724464e61c86985d8c912b6f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-4c6d65c679321d81af7ec8b61b1d5a24.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-2641b481724464e61c86985d8c912b6f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./demo.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Demonstrações</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Procurar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
      <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo escuro"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Procurar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Informações Legais e Declaração de Uso de Inteligência Artificial</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Identificação da(s) Disciplina(s)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade0p1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Revisão de Probabilidade e Modelos Probabilísticos</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade0p2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resultados Matemáticos e Assintóticos para Inferência</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Fundamentos da Inferência Estatística</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Distribuições Amostrais</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Avaliação de Estimadores e Princípios de Redução de Dados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Métodos de Estimação Pontual</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimação intervalar</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Testes de Hipóteses e Análise de Dados Categóricos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Projetos Aplicados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Unidade8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exemplos Aplicados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./demo.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Demonstrações</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#mapa-das-demonstrações-e-fontes" id="toc-mapa-das-demonstrações-e-fontes" class="nav-link active" data-scroll-target="#mapa-das-demonstrações-e-fontes">Mapa das demonstrações e fontes</a></li>
  <li><a href="#resultados-fundamentais-de-probabilidade" id="toc-resultados-fundamentais-de-probabilidade" class="nav-link" data-scroll-target="#resultados-fundamentais-de-probabilidade">Resultados fundamentais de probabilidade</a>
  <ul class="collapse">
  <li><a href="#demonstração-1-lei-fraca-dos-grandes-números-para-a-média-amostral" id="toc-demonstração-1-lei-fraca-dos-grandes-números-para-a-média-amostral" class="nav-link" data-scroll-target="#demonstração-1-lei-fraca-dos-grandes-números-para-a-média-amostral">Demonstração 1 — Lei fraca dos grandes números para a média amostral</a>
  <ul class="collapse">
  <li><a href="#enunciado" id="toc-enunciado" class="nav-link" data-scroll-target="#enunciado">Enunciado</a></li>
  <li><a href="#demonstração" id="toc-demonstração" class="nav-link" data-scroll-target="#demonstração">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-2-teorema-central-do-limite-por-funções-geradoras-de-momentos" id="toc-demonstração-2-teorema-central-do-limite-por-funções-geradoras-de-momentos" class="nav-link" data-scroll-target="#demonstração-2-teorema-central-do-limite-por-funções-geradoras-de-momentos">Demonstração 2 — Teorema Central do Limite por funções geradoras de momentos</a>
  <ul class="collapse">
  <li><a href="#enunciado-1" id="toc-enunciado-1" class="nav-link" data-scroll-target="#enunciado-1">Enunciado</a></li>
  <li><a href="#demonstração-1" id="toc-demonstração-1" class="nav-link" data-scroll-target="#demonstração-1">Demonstração</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#distribuições-amostrais" id="toc-distribuições-amostrais" class="nav-link" data-scroll-target="#distribuições-amostrais">Distribuições amostrais</a>
  <ul class="collapse">
  <li><a href="#demonstração-3-distribuições-de-bar-x-e-s2-no-modelo-normal" id="toc-demonstração-3-distribuições-de-bar-x-e-s2-no-modelo-normal" class="nav-link" data-scroll-target="#demonstração-3-distribuições-de-bar-x-e-s2-no-modelo-normal">Demonstração 3 — Distribuições de <span class="math inline">\(\bar X\)</span> e <span class="math inline">\(S^2\)</span> no modelo normal</a>
  <ul class="collapse">
  <li><a href="#enunciado-2" id="toc-enunciado-2" class="nav-link" data-scroll-target="#enunciado-2">Enunciado</a></li>
  <li><a href="#demonstração-2" id="toc-demonstração-2" class="nav-link" data-scroll-target="#demonstração-2">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-4-independência-entre-bar-x-e-s2" id="toc-demonstração-4-independência-entre-bar-x-e-s2" class="nav-link" data-scroll-target="#demonstração-4-independência-entre-bar-x-e-s2">Demonstração 4 — Independência entre <span class="math inline">\(\bar X\)</span> e <span class="math inline">\(S^2\)</span></a>
  <ul class="collapse">
  <li><a href="#enunciado-3" id="toc-enunciado-3" class="nav-link" data-scroll-target="#enunciado-3">Enunciado</a></li>
  <li><a href="#demonstração-3" id="toc-demonstração-3" class="nav-link" data-scroll-target="#demonstração-3">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-5-derivação-da-distribuição-t-de-student" id="toc-demonstração-5-derivação-da-distribuição-t-de-student" class="nav-link" data-scroll-target="#demonstração-5-derivação-da-distribuição-t-de-student">Demonstração 5 — Derivação da distribuição <span class="math inline">\(t\)</span> de Student</a>
  <ul class="collapse">
  <li><a href="#enunciado-4" id="toc-enunciado-4" class="nav-link" data-scroll-target="#enunciado-4">Enunciado</a></li>
  <li><a href="#demonstração-4" id="toc-demonstração-4" class="nav-link" data-scroll-target="#demonstração-4">Demonstração</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#redução-de-dados-e-estimação" id="toc-redução-de-dados-e-estimação" class="nav-link" data-scroll-target="#redução-de-dados-e-estimação">Redução de dados e estimação</a>
  <ul class="collapse">
  <li><a href="#demonstração-6-teorema-da-fatoração-de-fisherneyman-versão-discreta" id="toc-demonstração-6-teorema-da-fatoração-de-fisherneyman-versão-discreta" class="nav-link" data-scroll-target="#demonstração-6-teorema-da-fatoração-de-fisherneyman-versão-discreta">Demonstração 6 — Teorema da fatoração de Fisher–Neyman: versão discreta</a>
  <ul class="collapse">
  <li><a href="#enunciado-5" id="toc-enunciado-5" class="nav-link" data-scroll-target="#enunciado-5">Enunciado</a></li>
  <li><a href="#demonstração-5" id="toc-demonstração-5" class="nav-link" data-scroll-target="#demonstração-5">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-7-teorema-de-raoblackwell" id="toc-demonstração-7-teorema-de-raoblackwell" class="nav-link" data-scroll-target="#demonstração-7-teorema-de-raoblackwell">Demonstração 7 — Teorema de Rao–Blackwell</a>
  <ul class="collapse">
  <li><a href="#enunciado-6" id="toc-enunciado-6" class="nav-link" data-scroll-target="#enunciado-6">Enunciado</a></li>
  <li><a href="#demonstração-6" id="toc-demonstração-6" class="nav-link" data-scroll-target="#demonstração-6">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-8-teorema-de-lehmannscheffé" id="toc-demonstração-8-teorema-de-lehmannscheffé" class="nav-link" data-scroll-target="#demonstração-8-teorema-de-lehmannscheffé">Demonstração 8 — Teorema de Lehmann–Scheffé</a>
  <ul class="collapse">
  <li><a href="#enunciado-7" id="toc-enunciado-7" class="nav-link" data-scroll-target="#enunciado-7">Enunciado</a></li>
  <li><a href="#demonstração-7" id="toc-demonstração-7" class="nav-link" data-scroll-target="#demonstração-7">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-9-desigualdade-de-cramérrao" id="toc-demonstração-9-desigualdade-de-cramérrao" class="nav-link" data-scroll-target="#demonstração-9-desigualdade-de-cramérrao">Demonstração 9 — Desigualdade de Cramér–Rao</a>
  <ul class="collapse">
  <li><a href="#enunciado-8" id="toc-enunciado-8" class="nav-link" data-scroll-target="#enunciado-8">Enunciado</a></li>
  <li><a href="#demonstração-8" id="toc-demonstração-8" class="nav-link" data-scroll-target="#demonstração-8">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-10-invariância-do-estimador-de-máxima-verossimilhança" id="toc-demonstração-10-invariância-do-estimador-de-máxima-verossimilhança" class="nav-link" data-scroll-target="#demonstração-10-invariância-do-estimador-de-máxima-verossimilhança">Demonstração 10 — Invariância do estimador de máxima verossimilhança</a>
  <ul class="collapse">
  <li><a href="#enunciado-9" id="toc-enunciado-9" class="nav-link" data-scroll-target="#enunciado-9">Enunciado</a></li>
  <li><a href="#demonstração-9" id="toc-demonstração-9" class="nav-link" data-scroll-target="#demonstração-9">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-14-teorema-de-gaussmarkov" id="toc-demonstração-14-teorema-de-gaussmarkov" class="nav-link" data-scroll-target="#demonstração-14-teorema-de-gaussmarkov">Demonstração 14 — Teorema de Gauss–Markov</a>
  <ul class="collapse">
  <li><a href="#enunciado-10" id="toc-enunciado-10" class="nav-link" data-scroll-target="#enunciado-10">Enunciado</a></li>
  <li><a href="#demonstração-10" id="toc-demonstração-10" class="nav-link" data-scroll-target="#demonstração-10">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-22-estimadores-de-bayes-sob-perdas-quadrática-absoluta-e-01" id="toc-demonstração-22-estimadores-de-bayes-sob-perdas-quadrática-absoluta-e-01" class="nav-link" data-scroll-target="#demonstração-22-estimadores-de-bayes-sob-perdas-quadrática-absoluta-e-01">Demonstração 22 — Estimadores de Bayes sob perdas quadrática, absoluta e <span class="math inline">\(0\)</span>–<span class="math inline">\(1\)</span></a>
  <ul class="collapse">
  <li><a href="#perda-quadrática" id="toc-perda-quadrática" class="nav-link" data-scroll-target="#perda-quadrática">Perda quadrática</a></li>
  <li><a href="#perda-absoluta" id="toc-perda-absoluta" class="nav-link" data-scroll-target="#perda-absoluta">Perda absoluta</a></li>
  <li><a href="#perda-01-no-caso-discreto" id="toc-perda-01-no-caso-discreto" class="nav-link" data-scroll-target="#perda-01-no-caso-discreto">Perda <span class="math inline">\(0\)</span>–<span class="math inline">\(1\)</span> no caso discreto</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#verossimilhança-e-teoria-assintótica" id="toc-verossimilhança-e-teoria-assintótica" class="nav-link" data-scroll-target="#verossimilhança-e-teoria-assintótica">Verossimilhança e teoria assintótica</a>
  <ul class="collapse">
  <li><a href="#demonstração-16-consistência-do-emv-em-famílias-exponenciais-regulares" id="toc-demonstração-16-consistência-do-emv-em-famílias-exponenciais-regulares" class="nav-link" data-scroll-target="#demonstração-16-consistência-do-emv-em-famílias-exponenciais-regulares">Demonstração 16 — Consistência do EMV em famílias exponenciais regulares</a>
  <ul class="collapse">
  <li><a href="#enunciado-11" id="toc-enunciado-11" class="nav-link" data-scroll-target="#enunciado-11">Enunciado</a></li>
  <li><a href="#demonstração-11" id="toc-demonstração-11" class="nav-link" data-scroll-target="#demonstração-11">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-17-normalidade-assintótica-do-emv" id="toc-demonstração-17-normalidade-assintótica-do-emv" class="nav-link" data-scroll-target="#demonstração-17-normalidade-assintótica-do-emv">Demonstração 17 — Normalidade assintótica do EMV</a>
  <ul class="collapse">
  <li><a href="#enunciado-12" id="toc-enunciado-12" class="nav-link" data-scroll-target="#enunciado-12">Enunciado</a></li>
  <li><a href="#demonstração-12" id="toc-demonstração-12" class="nav-link" data-scroll-target="#demonstração-12">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-18-método-delta-univariado-e-multivariado" id="toc-demonstração-18-método-delta-univariado-e-multivariado" class="nav-link" data-scroll-target="#demonstração-18-método-delta-univariado-e-multivariado">Demonstração 18 — Método delta univariado e multivariado</a>
  <ul class="collapse">
  <li><a href="#enunciado-13" id="toc-enunciado-13" class="nav-link" data-scroll-target="#enunciado-13">Enunciado</a></li>
  <li><a href="#demonstração-13" id="toc-demonstração-13" class="nav-link" data-scroll-target="#demonstração-13">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-19-equivalência-assintótica-entre-wald-escore-e-razão-de-verossimilhanças" id="toc-demonstração-19-equivalência-assintótica-entre-wald-escore-e-razão-de-verossimilhanças" class="nav-link" data-scroll-target="#demonstração-19-equivalência-assintótica-entre-wald-escore-e-razão-de-verossimilhanças">Demonstração 19 — Equivalência assintótica entre Wald, escore e razão de verossimilhanças</a>
  <ul class="collapse">
  <li><a href="#enunciado-14" id="toc-enunciado-14" class="nav-link" data-scroll-target="#enunciado-14">Enunciado</a></li>
  <li><a href="#demonstração-14" id="toc-demonstração-14" class="nav-link" data-scroll-target="#demonstração-14">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-20-teorema-de-wilks-para-uma-subfamília-exponencial-curva" id="toc-demonstração-20-teorema-de-wilks-para-uma-subfamília-exponencial-curva" class="nav-link" data-scroll-target="#demonstração-20-teorema-de-wilks-para-uma-subfamília-exponencial-curva">Demonstração 20 — Teorema de Wilks para uma subfamília exponencial curva</a>
  <ul class="collapse">
  <li><a href="#enunciado-15" id="toc-enunciado-15" class="nav-link" data-scroll-target="#enunciado-15">Enunciado</a></li>
  <li><a href="#demonstração-15" id="toc-demonstração-15" class="nav-link" data-scroll-target="#demonstração-15">Demonstração</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#testes-de-hipóteses-e-intervalos-de-confiança" id="toc-testes-de-hipóteses-e-intervalos-de-confiança" class="nav-link" data-scroll-target="#testes-de-hipóteses-e-intervalos-de-confiança">Testes de hipóteses e intervalos de confiança</a>
  <ul class="collapse">
  <li><a href="#demonstração-11-lema-de-neymanpearson" id="toc-demonstração-11-lema-de-neymanpearson" class="nav-link" data-scroll-target="#demonstração-11-lema-de-neymanpearson">Demonstração 11 — Lema de Neyman–Pearson</a>
  <ul class="collapse">
  <li><a href="#enunciado-16" id="toc-enunciado-16" class="nav-link" data-scroll-target="#enunciado-16">Enunciado</a></li>
  <li><a href="#demonstração-16" id="toc-demonstração-16" class="nav-link" data-scroll-target="#demonstração-16">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-12-teorema-de-karlinrubin" id="toc-demonstração-12-teorema-de-karlinrubin" class="nav-link" data-scroll-target="#demonstração-12-teorema-de-karlinrubin">Demonstração 12 — Teorema de Karlin–Rubin</a>
  <ul class="collapse">
  <li><a href="#enunciado-17" id="toc-enunciado-17" class="nav-link" data-scroll-target="#enunciado-17">Enunciado</a></li>
  <li><a href="#demonstração-17" id="toc-demonstração-17" class="nav-link" data-scroll-target="#demonstração-17">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-13-dualidade-entre-testes-e-regiões-de-confiança" id="toc-demonstração-13-dualidade-entre-testes-e-regiões-de-confiança" class="nav-link" data-scroll-target="#demonstração-13-dualidade-entre-testes-e-regiões-de-confiança">Demonstração 13 — Dualidade entre testes e regiões de confiança</a>
  <ul class="collapse">
  <li><a href="#enunciado-18" id="toc-enunciado-18" class="nav-link" data-scroll-target="#enunciado-18">Enunciado</a></li>
  <li><a href="#demonstração-18" id="toc-demonstração-18" class="nav-link" data-scroll-target="#demonstração-18">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-15-teste-t-de-uma-amostra-como-teste-da-razão-de-verossimilhanças-generalizada" id="toc-demonstração-15-teste-t-de-uma-amostra-como-teste-da-razão-de-verossimilhanças-generalizada" class="nav-link" data-scroll-target="#demonstração-15-teste-t-de-uma-amostra-como-teste-da-razão-de-verossimilhanças-generalizada">Demonstração 15 — Teste <span class="math inline">\(t\)</span> de uma amostra como teste da razão de verossimilhanças generalizada</a>
  <ul class="collapse">
  <li><a href="#enunciado-19" id="toc-enunciado-19" class="nav-link" data-scroll-target="#enunciado-19">Enunciado</a></li>
  <li><a href="#demonstração-19" id="toc-demonstração-19" class="nav-link" data-scroll-target="#demonstração-19">Demonstração</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#inferência-computacional-reamostragem-e-métodos-modernos" id="toc-inferência-computacional-reamostragem-e-métodos-modernos" class="nav-link" data-scroll-target="#inferência-computacional-reamostragem-e-métodos-modernos">Inferência computacional, reamostragem e métodos modernos</a>
  <ul class="collapse">
  <li><a href="#demonstração-21-monotonicidade-do-algoritmo-em" id="toc-demonstração-21-monotonicidade-do-algoritmo-em" class="nav-link" data-scroll-target="#demonstração-21-monotonicidade-do-algoritmo-em">Demonstração 21 — Monotonicidade do algoritmo EM</a>
  <ul class="collapse">
  <li><a href="#definição" id="toc-definição" class="nav-link" data-scroll-target="#definição">Definição</a></li>
  <li><a href="#demonstração-20" id="toc-demonstração-20" class="nav-link" data-scroll-target="#demonstração-20">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-23-consistência-de-minimizadores-convexos" id="toc-demonstração-23-consistência-de-minimizadores-convexos" class="nav-link" data-scroll-target="#demonstração-23-consistência-de-minimizadores-convexos">Demonstração 23 — Consistência de minimizadores convexos</a>
  <ul class="collapse">
  <li><a href="#enunciado-20" id="toc-enunciado-20" class="nav-link" data-scroll-target="#enunciado-20">Enunciado</a></li>
  <li><a href="#demonstração-21" id="toc-demonstração-21" class="nav-link" data-scroll-target="#demonstração-21">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-24-função-de-influência-e-eficiência-semiparamétrica" id="toc-demonstração-24-função-de-influência-e-eficiência-semiparamétrica" class="nav-link" data-scroll-target="#demonstração-24-função-de-influência-e-eficiência-semiparamétrica">Demonstração 24 — Função de influência e eficiência semiparamétrica</a>
  <ul class="collapse">
  <li><a href="#função-de-influência-de-um-funcional" id="toc-função-de-influência-de-um-funcional" class="nav-link" data-scroll-target="#função-de-influência-de-um-funcional">Função de influência de um funcional</a></li>
  <li><a href="#resultado-de-eficiência-semiparamétrica" id="toc-resultado-de-eficiência-semiparamétrica" class="nav-link" data-scroll-target="#resultado-de-eficiência-semiparamétrica">Resultado de eficiência semiparamétrica</a></li>
  <li><a href="#demonstração-22" id="toc-demonstração-22" class="nav-link" data-scroll-target="#demonstração-22">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-25-validade-exata-de-um-teste-de-permutação" id="toc-demonstração-25-validade-exata-de-um-teste-de-permutação" class="nav-link" data-scroll-target="#demonstração-25-validade-exata-de-um-teste-de-permutação">Demonstração 25 — Validade exata de um teste de permutação</a>
  <ul class="collapse">
  <li><a href="#enunciado-21" id="toc-enunciado-21" class="nav-link" data-scroll-target="#enunciado-21">Enunciado</a></li>
  <li><a href="#demonstração-23" id="toc-demonstração-23" class="nav-link" data-scroll-target="#demonstração-23">Demonstração</a></li>
  </ul></li>
  <li><a href="#demonstração-26-princípio-plug-in-e-bootstrap-da-média" id="toc-demonstração-26-princípio-plug-in-e-bootstrap-da-média" class="nav-link" data-scroll-target="#demonstração-26-princípio-plug-in-e-bootstrap-da-média">Demonstração 26 — Princípio <em>plug-in</em> e bootstrap da média</a>
  <ul class="collapse">
  <li><a href="#definição-1" id="toc-definição-1" class="nav-link" data-scroll-target="#definição-1">Definição</a></li>
  <li><a href="#demonstração-para-a-média" id="toc-demonstração-para-a-média" class="nav-link" data-scroll-target="#demonstração-para-a-média">Demonstração para a média</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#síntese-conceitual" id="toc-síntese-conceitual" class="nav-link" data-scroll-target="#síntese-conceitual">Síntese conceitual</a></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências">Referências</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Demonstrações</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Este capítulo reúne 26 demonstrações consideradas estruturantes para um livro de Inferência Estatística destinado à graduação e ao mestrado. A organização segue seis blocos: resultados fundamentais de probabilidade; distribuições amostrais; redução de dados e estimação; verossimilhança e teoria assintótica; testes e intervalos; e inferência computacional e moderna.</p>
<p>As demonstrações foram reescritas em notação uniforme e com nível de detalhe adequado ao texto didático. Cada resultado contém uma indicação explícita da fonte principal, da localização aproximada na obra e do grau de adaptação realizado.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Escopo bibliográfico">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Escopo bibliográfico
</div>
</div>
<div class="callout-body-container callout-body">
<p>As provas abaixo são adaptações didáticas das fontes indicadas. Quando a fonte apresenta apenas uma versão restrita do resultado, o enunciado preserva essa restrição. Generalizações não demonstradas nas obras consultadas são identificadas como observações que exigem verificação bibliográfica adicional.</p>
</div>
</div>
<section id="mapa-das-demonstrações-e-fontes" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="mapa-das-demonstrações-e-fontes">Mapa das demonstrações e fontes</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 39%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Nº</th>
<th>Demonstração</th>
<th>Fonte principal auditada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td>Lei fraca dos grandes números</td>
<td><span class="citation" data-cites="ramachandran2009">Ramachandran; Tsokos (<a href="#ref-ramachandran2009" role="doc-biblioref">2009, seç. 3.5</a>, Teorema 3.5.2)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td>Teorema Central do Limite por FGM</td>
<td><span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012</a>, Apêndice 4.A.2)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td>Distribuições de <span class="math inline">\(\bar X\)</span> e <span class="math inline">\(S^2\)</span> no modelo normal</td>
<td><span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012, seç. 7.1–7.3</a> e Apêndice 7.A.2)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td>Independência entre <span class="math inline">\(\bar X\)</span> e <span class="math inline">\(S^2\)</span></td>
<td><span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012</a>, Apêndice 7.A.2, Teorema 7.A.2.1)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td>Derivação da distribuição <span class="math inline">\(t\)</span></td>
<td><span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012, seç. 7.2–7.3</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td>Fatoração de Fisher–Neyman, versão discreta</td>
<td><span class="citation" data-cites="rice2007mathematical">Rice (<a href="#ref-rice2007mathematical" role="doc-biblioref">2007, seç. 8.8.1</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td>Teorema de Rao–Blackwell</td>
<td><span class="citation" data-cites="rice2007mathematical">Rice (<a href="#ref-rice2007mathematical" role="doc-biblioref">2007, seç. 8.8.2</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td>Teorema de Lehmann–Scheffé</td>
<td><span class="citation" data-cites="hogg1978">Hogg; Craig (<a href="#ref-hogg1978" role="doc-biblioref">1978, cap. 10</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td>Desigualdade de Cramér–Rao</td>
<td><span class="citation" data-cites="hogg1978">Hogg; Craig (<a href="#ref-hogg1978" role="doc-biblioref">1978, seç. 11.1</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td>Invariância do EMV sob transformação invertível</td>
<td><span class="citation" data-cites="chihara2022">Chihara; Hesterberg (<a href="#ref-chihara2022" role="doc-biblioref">2022, seç. 6.3.5</a>, Proposição 6.6)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td>Lema de Neyman–Pearson</td>
<td><span class="citation" data-cites="rice2007mathematical">Rice (<a href="#ref-rice2007mathematical" role="doc-biblioref">2007, seç. 9.2</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td>Teorema de Karlin–Rubin</td>
<td><span class="citation" data-cites="rasch2018">Rasch; Schott (<a href="#ref-rasch2018" role="doc-biblioref">2018, seç. 3.3.1</a>, Teoremas 3.7–3.8)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td>Dualidade entre testes e regiões de confiança</td>
<td><span class="citation" data-cites="rice2007mathematical">Rice (<a href="#ref-rice2007mathematical" role="doc-biblioref">2007, seç. 9.3</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td>Teorema de Gauss–Markov</td>
<td><span class="citation" data-cites="rasch2018">Rasch; Schott (<a href="#ref-rasch2018" role="doc-biblioref">2018</a>, Teorema 4.3)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td>Teste <span class="math inline">\(t\)</span> de uma amostra como TRVG</td>
<td><span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012</a>, Apêndice 7.A.3)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td>Consistência do EMV em famílias exponenciais regulares</td>
<td><span class="citation" data-cites="lauritzen2023fundamentals">Lauritzen (<a href="#ref-lauritzen2023fundamentals" role="doc-biblioref">2023, seç. 5.3.1</a>, Teorema 5.9)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td>Normalidade assintótica do EMV</td>
<td><span class="citation" data-cites="lauritzen2023fundamentals">Lauritzen (<a href="#ref-lauritzen2023fundamentals" role="doc-biblioref">2023, seç. 5.3.2</a>, Teorema 5.11)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td>Método delta univariado e multivariado</td>
<td><span class="citation" data-cites="lauritzen2023fundamentals">Lauritzen (<a href="#ref-lauritzen2023fundamentals" role="doc-biblioref">2023</a>, Apêndice A.2.3, Teorema A.19)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td>Equivalência assintótica de Wald, escore e razão de verossimilhanças</td>
<td><span class="citation" data-cites="cox2006principles">Cox (<a href="#ref-cox2006principles" role="doc-biblioref">2006</a>)</span> [Capítulo 6]; <span class="citation" data-cites="lauritzen2023fundamentals">Lauritzen (<a href="#ref-lauritzen2023fundamentals" role="doc-biblioref">2023, seç. 5.3.3</a> e 5.4.4)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td>Teorema de Wilks em famílias exponenciais curvas</td>
<td><span class="citation" data-cites="lauritzen2023fundamentals">Lauritzen (<a href="#ref-lauritzen2023fundamentals" role="doc-biblioref">2023</a>, Teorema 5.39)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td>Monotonicidade do algoritmo EM</td>
<td><span class="citation" data-cites="gupta2011em">Gupta; Chen (<a href="#ref-gupta2011em" role="doc-biblioref">2011, seç. 1.1</a> e 2.1)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td>Estimadores de Bayes sob três perdas</td>
<td><span class="citation" data-cites="ramachandran2021r">Ramachandran; Tsokos (<a href="#ref-ramachandran2021r" role="doc-biblioref">2021, seç. 10.2.1</a>, para perdas quadrática e absoluta)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td>Consistência de minimizadores convexos</td>
<td><span class="citation" data-cites="bickel2016volume2">Bickel; Doksum (<a href="#ref-bickel2016volume2" role="doc-biblioref">2016</a>, Proposição 9.2.1)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">24</td>
<td>Função de influência e eficiência semiparamétrica</td>
<td><span class="citation" data-cites="bickel2016volume2">Bickel; Doksum (<a href="#ref-bickel2016volume2" role="doc-biblioref">2016</a>)</span> [Seções 7.2.1 e 9.3, Proposição 9.3.3]; <span class="citation" data-cites="wilcox2022">Wilcox (<a href="#ref-wilcox2022" role="doc-biblioref">2022, seç. 2.1–2.2</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: right;">25</td>
<td>Validade exata de testes de permutação</td>
<td><span class="citation" data-cites="chihara2022">Chihara; Hesterberg (<a href="#ref-chihara2022" role="doc-biblioref">2022, seç. 3.3</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: right;">26</td>
<td>Princípio <em>plug-in</em> e bootstrap da média</td>
<td><span class="citation" data-cites="chihara2022">Chihara; Hesterberg (<a href="#ref-chihara2022" role="doc-biblioref">2022, seç. 5.2</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="resultados-fundamentais-de-probabilidade" class="level1 unnumbered">
<h1 class="unnumbered">Resultados fundamentais de probabilidade</h1>
<section id="demonstração-1-lei-fraca-dos-grandes-números-para-a-média-amostral" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-1-lei-fraca-dos-grandes-números-para-a-média-amostral">Demonstração 1 — Lei fraca dos grandes números para a média amostral</h2>
<section id="enunciado" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado">Enunciado</h3>
<p>Sejam <span class="math inline">\(X_1,\ldots,X_n\)</span> variáveis aleatórias independentes, com</p>
<p><span class="math display">\[E(X_i)=\mu
\quad\text{e}\quad
\operatorname{Var}(X_i)=\sigma^2&lt;\infty.\]</span></p>
<p>Então, para todo <span class="math inline">\(\varepsilon&gt;0\)</span>,</p>
<p><span class="math display">\[P\left(\left|\bar X_n-\mu\right|\geq\varepsilon\right)
\longrightarrow 0,\]</span></p>
<p>isto é, <span class="math inline">\(\bar X_n\xrightarrow{P}\mu\)</span>.</p>
</section>
<section id="demonstração" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração">Demonstração</h3>
<p>Pela independência,</p>
<p><span class="math display">\[E(\bar X_n)=\mu\]</span></p>
<p>e</p>
<p><span class="math display">\[\operatorname{Var}(\bar X_n)
=
\operatorname{Var}\left(\frac{1}{n}\sum_{i=1}^nX_i\right)
=
\frac{1}{n^2}\sum_{i=1}^n\operatorname{Var}(X_i)
=
\frac{\sigma^2}{n}.\]</span></p>
<p>Aplicando a desigualdade de Chebyshev,</p>
<p><span class="math display">\[P\left(\left|\bar X_n-\mu\right|\geq\varepsilon\right)
\leq
\frac{\operatorname{Var}(\bar X_n)}{\varepsilon^2}
=
\frac{\sigma^2}{n\varepsilon^2}.\]</span></p>
<p>Como <span class="math inline">\(\sigma^2/(n\varepsilon^2)\to 0\)</span>, o teorema do confronto fornece</p>
<p><span class="math display">\[P\left(\left|\bar X_n-\mu\right|\geq\varepsilon\right)
\to 0.\]</span></p>
<p>Portanto, <span class="math inline">\(\bar X_n\xrightarrow{P}\mu\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Interpretação">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Interpretação
</div>
</div>
<div class="callout-body-container callout-body">
<p>A variância da média decresce à taxa <span class="math inline">\(1/n\)</span>. A lei fraca não afirma que cada observação se aproxima de <span class="math inline">\(\mu\)</span>; afirma que a média de um número crescente de observações se concentra probabilisticamente em torno de <span class="math inline">\(\mu\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="ramachandran2009">Ramachandran; Tsokos (<a href="#ref-ramachandran2009" role="doc-biblioref">2009, seç. 3.5</a>, Teorema 3.5.2)</span>.<br>
<strong>Adaptação:</strong> notação modernizada e formulação direta em termos de convergência em probabilidade.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-2-teorema-central-do-limite-por-funções-geradoras-de-momentos" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-2-teorema-central-do-limite-por-funções-geradoras-de-momentos">Demonstração 2 — Teorema Central do Limite por funções geradoras de momentos</h2>
<section id="enunciado-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-1">Enunciado</h3>
<p>Sejam <span class="math inline">\(X_1,X_2,\ldots\)</span> variáveis aleatórias i.i.d., com <span class="math inline">\(E(X_i)=\mu\)</span>, <span class="math inline">\(\operatorname{Var}(X_i)=\sigma^2&gt;0\)</span>, e suponha que a função geradora de momentos exista em uma vizinhança de zero. Então</p>
<p><span class="math display">\[Z_n=\frac{\sqrt n(\bar X_n-\mu)}{\sigma}
\xrightarrow{d}N(0,1).\]</span></p>
</section>
<section id="demonstração-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-1">Demonstração</h3>
<p>Defina</p>
<p><span class="math display">\[Y_i=\frac{X_i-\mu}{\sigma}.\]</span></p>
<p>Temos <span class="math inline">\(E(Y_i)=0\)</span>, <span class="math inline">\(\operatorname{Var}(Y_i)=1\)</span> e</p>
<p><span class="math display">\[Z_n=\frac{Y_1+\cdots+Y_n}{\sqrt n}.\]</span></p>
<p>Se <span class="math inline">\(M_Y(t)\)</span> é a FGM de <span class="math inline">\(Y_i\)</span>, então, pela independência,</p>
<p><span class="math display">\[M_{Z_n}(t)
=
\left[M_Y\left(\frac{t}{\sqrt n}\right)\right]^n.\]</span></p>
<p>Como <span class="math inline">\(M_Y(0)=1\)</span>, <span class="math inline">\(M_Y'(0)=0\)</span> e <span class="math inline">\(M_Y''(0)=1\)</span>, a expansão de Taylor em torno de zero fornece</p>
<p><span class="math display">\[M_Y(s)=1+\frac{s^2}{2}+o(s^2),
\qquad s\to 0.\]</span></p>
<p>Tomando <span class="math inline">\(s=t/\sqrt n\)</span>,</p>
<p><span class="math display">\[M_Y\left(\frac{t}{\sqrt n}\right)
=
1+\frac{t^2}{2n}+o\left(\frac{1}{n}\right).\]</span></p>
<p>Logo,</p>
<p><span class="math display">\[M_{Z_n}(t)
=
\left[
1+\frac{t^2}{2n}+o\left(\frac{1}{n}\right)
\right]^n
\longrightarrow
\exp\left(\frac{t^2}{2}\right).\]</span></p>
<p>A função <span class="math inline">\(\exp(t^2/2)\)</span> é a FGM da distribuição normal padrão. Pelo teorema de continuidade para funções geradoras de momentos,</p>
<p><span class="math display">\[Z_n\xrightarrow{d}N(0,1).\]</span></p>
<div class="callout callout-style-default callout-warning callout-titled" title="Condição importante">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Condição importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta demonstração exige a existência da FGM em uma vizinhança de zero. O Teorema Central do Limite de Lindeberg–Lévy requer apenas variância finita, mas sua prova geral não é esta. A extensão precisa deve ser verificada bibliograficamente antes de se retirar a hipótese sobre a FGM.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012</a>, Apêndice 4.A.2)</span>.<br>
<strong>Fonte complementar:</strong> <span class="citation" data-cites="rice2007mathematical">Rice (<a href="#ref-rice2007mathematical" role="doc-biblioref">2007, seç. 5.3</a>)</span>.<br>
<strong>Adaptação:</strong> uso da notação <span class="math inline">\(o(n^{-1})\)</span> para condensar a expansão apresentada nas fontes.</p>
</div>
</div>
</section>
</section>
</section>
<section id="distribuições-amostrais" class="level1 unnumbered">
<h1 class="unnumbered">Distribuições amostrais</h1>
<section id="demonstração-3-distribuições-de-bar-x-e-s2-no-modelo-normal" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-3-distribuições-de-bar-x-e-s2-no-modelo-normal">Demonstração 3 — Distribuições de <span class="math inline">\(\bar X\)</span> e <span class="math inline">\(S^2\)</span> no modelo normal</h2>
<section id="enunciado-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-2">Enunciado</h3>
<p>Se <span class="math inline">\(X_1,\ldots,X_n\)</span> são i.i.d. <span class="math inline">\(N(\mu,\sigma^2)\)</span> e</p>
<p><span class="math display">\[\bar X=\frac{1}{n}\sum_{i=1}^nX_i,
\qquad
S^2=\frac{1}{n-1}\sum_{i=1}^n(X_i-\bar X)^2,\]</span></p>
<p>então</p>
<p><span class="math display">\[\bar X\sim N\left(\mu,\frac{\sigma^2}{n}\right)\]</span></p>
<p>e</p>
<p><span class="math display">\[\frac{(n-1)S^2}{\sigma^2}\sim\chi^2_{n-1}.\]</span></p>
</section>
<section id="demonstração-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-2">Demonstração</h3>
<p>A média amostral é uma combinação linear de variáveis normais independentes. Portanto, é normal, com</p>
<p><span class="math display">\[E(\bar X)=\mu,
\qquad
\operatorname{Var}(\bar X)=\frac{\sigma^2}{n}.\]</span></p>
<p>Para a segunda afirmação, padronize as observações:</p>
<p><span class="math display">\[Y_i=\frac{X_i-\mu}{\sigma}.\]</span></p>
<p>O vetor <span class="math inline">\(Y=(Y_1,\ldots,Y_n)^\top\)</span> tem distribuição <span class="math inline">\(N_n(0,I_n)\)</span>. Escolha uma matriz ortogonal <span class="math inline">\(A\)</span> cuja última linha seja</p>
<p><span class="math display">\[\frac{1}{\sqrt n}(1,\ldots,1).\]</span></p>
<p>Defina <span class="math inline">\(Z=AY\)</span>. Como transformações ortogonais preservam a distribuição normal padrão multivariada,</p>
<p><span class="math display">\[Z_1,\ldots,Z_n\]</span></p>
<p>são independentes e <span class="math inline">\(N(0,1)\)</span>. Além disso,</p>
<p><span class="math display">\[Z_n=\sqrt n\,\bar Y
=
\frac{\sqrt n(\bar X-\mu)}{\sigma}.\]</span></p>
<p>A preservação da norma pela transformação ortogonal implica</p>
<p><span class="math display">\[\sum_{i=1}^nY_i^2
=
\sum_{j=1}^nZ_j^2.\]</span></p>
<p>Usando a decomposição</p>
<p><span class="math display">\[\sum_{i=1}^n(Y_i-\bar Y)^2
=
\sum_{i=1}^nY_i^2-n\bar Y^2,\]</span></p>
<p>obtemos</p>
<p><span class="math display">\[\sum_{i=1}^n(Y_i-\bar Y)^2
=
\sum_{j=1}^{n-1}Z_j^2.\]</span></p>
<p>O lado direito é soma dos quadrados de <span class="math inline">\(n-1\)</span> normais padrão independentes. Assim,</p>
<p><span class="math display">\[\sum_{i=1}^n(Y_i-\bar Y)^2\sim\chi^2_{n-1}.\]</span></p>
<p>Como</p>
<p><span class="math display">\[\sum_{i=1}^n(Y_i-\bar Y)^2
=
\frac{1}{\sigma^2}\sum_{i=1}^n(X_i-\bar X)^2
=
\frac{(n-1)S^2}{\sigma^2},\]</span></p>
<p>segue o resultado.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012, seç. 7.1–7.3</a> e Apêndice 7.A.2)</span>.<br>
<strong>Adaptação:</strong> a normalidade de <span class="math inline">\(\bar X\)</span> é obtida por fechamento da família normal sob combinações lineares; a parte referente a <span class="math inline">\(S^2\)</span> segue a transformação ortogonal do Apêndice 7.A.2.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-4-independência-entre-bar-x-e-s2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-4-independência-entre-bar-x-e-s2">Demonstração 4 — Independência entre <span class="math inline">\(\bar X\)</span> e <span class="math inline">\(S^2\)</span></h2>
<section id="enunciado-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-3">Enunciado</h3>
<p>Sob as condições da demonstração anterior, <span class="math inline">\(\bar X\)</span> e <span class="math inline">\(S^2\)</span> são independentes.</p>
</section>
<section id="demonstração-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-3">Demonstração</h3>
<p>Na transformação ortogonal anterior,</p>
<p><span class="math display">\[Z_n=\frac{\sqrt n(\bar X-\mu)}{\sigma}\]</span></p>
<p>e</p>
<p><span class="math display">\[\frac{(n-1)S^2}{\sigma^2}
=
\sum_{j=1}^{n-1}Z_j^2.\]</span></p>
<p>O vetor <span class="math inline">\(Z\)</span> possui componentes normais padrão independentes. Portanto, <span class="math inline">\(Z_n\)</span> é independente do vetor</p>
<p><span class="math display">\[(Z_1,\ldots,Z_{n-1}).\]</span></p>
<p>Como <span class="math inline">\(\bar X\)</span> é função apenas de <span class="math inline">\(Z_n\)</span> e <span class="math inline">\(S^2\)</span> é função apenas de <span class="math inline">\((Z_1,\ldots,Z_{n-1})\)</span>, segue que <span class="math inline">\(\bar X\)</span> e <span class="math inline">\(S^2\)</span> são independentes.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Interpretação">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Interpretação
</div>
</div>
<div class="callout-body-container callout-body">
<p>No modelo normal, a informação amostral sobre posição, representada por <span class="math inline">\(\bar X\)</span>, separa-se exatamente da informação residual sobre escala, representada por <span class="math inline">\(S^2\)</span>. Essa propriedade é especial da distribuição normal e fundamenta a inferência exata baseada na distribuição <span class="math inline">\(t\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012</a>, Apêndice 7.A.2, Teorema 7.A.2.1)</span>.<br>
<strong>Adaptação:</strong> separação da conclusão de independência em uma demonstração própria para destacar sua função inferencial.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-5-derivação-da-distribuição-t-de-student" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-5-derivação-da-distribuição-t-de-student">Demonstração 5 — Derivação da distribuição <span class="math inline">\(t\)</span> de Student</h2>
<section id="enunciado-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-4">Enunciado</h3>
<p>Se <span class="math inline">\(X_1,\ldots,X_n\)</span> são i.i.d. <span class="math inline">\(N(\mu,\sigma^2)\)</span>, então</p>
<p><span class="math display">\[T=\frac{\bar X-\mu}{S/\sqrt n}
\sim t_{n-1}.\]</span></p>
</section>
<section id="demonstração-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-4">Demonstração</h3>
<p>Pelos resultados anteriores,</p>
<p><span class="math display">\[Z=\frac{\sqrt n(\bar X-\mu)}{\sigma}\sim N(0,1)\]</span></p>
<p>e</p>
<p><span class="math display">\[U=\frac{(n-1)S^2}{\sigma^2}\sim\chi^2_{n-1},\]</span></p>
<p>com <span class="math inline">\(Z\)</span> e <span class="math inline">\(U\)</span> independentes. Reescrevendo <span class="math inline">\(T\)</span>,</p>
<p><span class="math display">\[T
=
\frac{\sqrt n(\bar X-\mu)/\sigma}{S/\sigma}
=
\frac{Z}{\sqrt{U/(n-1)}}.\]</span></p>
<p>Por definição, se <span class="math inline">\(Z\sim N(0,1)\)</span> e <span class="math inline">\(U\sim\chi^2_\nu\)</span> são independentes, então</p>
<p><span class="math display">\[\frac{Z}{\sqrt{U/\nu}}\sim t_\nu.\]</span></p>
<p>Tomando <span class="math inline">\(\nu=n-1\)</span>, obtemos</p>
<p><span class="math display">\[T\sim t_{n-1}.\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012, seç. 7.2–7.3</a> e Apêndice 7.A.2)</span>.<br>
<strong>Adaptação:</strong> derivação apresentada como consequência direta dos dois resultados normais fundamentais.</p>
</div>
</div>
</section>
</section>
</section>
<section id="redução-de-dados-e-estimação" class="level1 unnumbered">
<h1 class="unnumbered">Redução de dados e estimação</h1>
<section id="demonstração-6-teorema-da-fatoração-de-fisherneyman-versão-discreta" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-6-teorema-da-fatoração-de-fisherneyman-versão-discreta">Demonstração 6 — Teorema da fatoração de Fisher–Neyman: versão discreta</h2>
<section id="enunciado-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-5">Enunciado</h3>
<p>Considere uma família de funções de probabilidade <span class="math inline">\(\{f_\theta:\theta\in\Theta\}\)</span> em um espaço amostral contável, com suporte comum <span class="math inline">\(\mathcal X_0\)</span>. Uma estatística <span class="math inline">\(T(X)\)</span> é suficiente para <span class="math inline">\(\theta\)</span> se, e somente se, existem funções não negativas <span class="math inline">\(g_\theta\)</span> e <span class="math inline">\(h\)</span> tais que</p>
<p><span class="math display">\[f_\theta(x)=g_\theta\{T(x)\}h(x),
\qquad x\in\mathcal X_0,\]</span></p>
<p>em que <span class="math inline">\(h\)</span> não depende de <span class="math inline">\(\theta\)</span>.</p>
</section>
<section id="demonstração-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-5">Demonstração</h3>
<p>Suponha primeiro que a fatoração seja válida. Para qualquer <span class="math inline">\(t\)</span> pertencente à imagem de <span class="math inline">\(T\)</span> no suporte comum,</p>
<p><span class="math display">\[P_\theta(T=t)
=
\sum_{x:T(x)=t}f_\theta(x)
=
g_\theta(t)\sum_{x:T(x)=t}h(x).\]</span></p>
<p>Logo, para <span class="math inline">\(T(x)=t\)</span>,</p>
<p><span class="math display">\[P_\theta(X=x\mid T=t)
=
\frac{g_\theta(t)h(x)}{g_\theta(t)\sum_{u:T(u)=t}h(u)}
=
\frac{h(x)}{\sum_{u:T(u)=t}h(u)}.\]</span></p>
<p>Essa distribuição condicional não depende de <span class="math inline">\(\theta\)</span>. Portanto, <span class="math inline">\(T\)</span> é suficiente.</p>
<p>Reciprocamente, suponha que <span class="math inline">\(T\)</span> seja suficiente. Então existe uma função condicional comum, independente de <span class="math inline">\(\theta\)</span>, que denotaremos por</p>
<p><span class="math display">\[h(x)=P_\theta\{X=x\mid T=T(x)\},\]</span></p>
<p>bem definida no suporte comum pela suficiência. Defina ainda</p>
<p><span class="math display">\[g_\theta(t)=P_\theta(T=t).\]</span></p>
<p>Pela regra do produto,</p>
<p><span class="math display">\[f_\theta(x)
=
P_\theta(T=T(x))P(X=x\mid T=T(x))
=
g_\theta(T(x))h(x).\]</span></p>
<p>Portanto, a fatoração é necessária e suficiente.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Extensão a famílias dominadas">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Extensão a famílias dominadas
</div>
</div>
<div class="callout-body-container callout-body">
<p>A forma geral do teorema vale para famílias dominadas por uma medida comum. A demonstração acima foi deliberadamente restrita ao caso discreto com suporte comum; no caso geral, a necessidade da fatoração exige uma formulação cuidadosa por densidades e distribuições condicionais regulares.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="rice2007mathematical">Rice (<a href="#ref-rice2007mathematical" role="doc-biblioref">2007, seç. 8.8.1</a>)</span>.<br>
<strong>Adaptação:</strong> prova completa da versão discreta, com explicitação da hipótese de suporte comum; a versão dominada geral é apenas enunciada na observação.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-7-teorema-de-raoblackwell" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-7-teorema-de-raoblackwell">Demonstração 7 — Teorema de Rao–Blackwell</h2>
<section id="enunciado-6" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-6">Enunciado</h3>
<p>Se <span class="math inline">\(T\)</span> é suficiente para <span class="math inline">\(\theta\)</span> e <span class="math inline">\(W\)</span> é um estimador não viesado de <span class="math inline">\(g(\theta)\)</span> com <span class="math inline">\(E_\theta(W^2)&lt;\infty\)</span>, então</p>
<p><span class="math display">\[W^*=E(W\mid T)\]</span></p>
<p>é não viesado e satisfaz</p>
<p><span class="math display">\[\operatorname{Var}_\theta(W^*)
\leq
\operatorname{Var}_\theta(W).\]</span></p>
</section>
<section id="demonstração-6" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-6">Demonstração</h3>
<p>Pela propriedade da esperança iterada,</p>
<p><span class="math display">\[E_\theta(W^*)
=
E_\theta\{E_\theta(W\mid T)\}
=
E_\theta(W)
=
g(\theta).\]</span></p>
<p>Logo, <span class="math inline">\(W^*\)</span> é não viesado. Como <span class="math inline">\(T\)</span> é suficiente, a esperança condicional pode ser escolhida como uma função da amostra que não depende do parâmetro desconhecido.</p>
<p>Pela decomposição da variância total,</p>
<p><span class="math display">\[\operatorname{Var}_\theta(W)
=
\operatorname{Var}_\theta\{E_\theta(W\mid T)\}
+
E_\theta\{\operatorname{Var}_\theta(W\mid T)\}.\]</span></p>
<p>O segundo termo é não negativo. Assim,</p>
<p><span class="math display">\[\operatorname{Var}_\theta(W)
\geq
\operatorname{Var}_\theta(W^*).\]</span></p>
<p>Além disso, há igualdade se, e somente se,</p>
<p><span class="math display">\[W=E_\theta(W\mid T)\]</span></p>
<p>quase certamente, isto é, se <span class="math inline">\(W\)</span> já é uma função de <span class="math inline">\(T\)</span> salvo em um conjunto nulo.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Interpretação">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Interpretação
</div>
</div>
<div class="callout-body-container callout-body">
<p>Condicionar em uma estatística suficiente remove a variabilidade de <span class="math inline">\(W\)</span> que não carrega informação adicional sobre <span class="math inline">\(\theta\)</span>. O procedimento preserva o alvo e não aumenta o erro quadrático entre estimadores não viesados.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="rice2007mathematical">Rice (<a href="#ref-rice2007mathematical" role="doc-biblioref">2007, seç. 8.8.2</a>)</span>.<br>
<strong>Fonte complementar:</strong> <span class="citation" data-cites="hogg1978">Hogg; Craig (<a href="#ref-hogg1978" role="doc-biblioref">1978, seç. 10.2</a>)</span>.<br>
<strong>Adaptação:</strong> uso explícito da lei da variância total.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-8-teorema-de-lehmannscheffé" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-8-teorema-de-lehmannscheffé">Demonstração 8 — Teorema de Lehmann–Scheffé</h2>
<section id="enunciado-7" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-7">Enunciado</h3>
<p>Se <span class="math inline">\(T\)</span> é suficiente e completa para <span class="math inline">\(\theta\)</span>, e <span class="math inline">\(\delta(T)\)</span> é quadrado-integrável e não viesado para <span class="math inline">\(g(\theta)\)</span>, então <span class="math inline">\(\delta(T)\)</span> é, a menos de igualdade quase certa, o único estimador não viesado de variância uniformemente mínima de <span class="math inline">\(g(\theta)\)</span>.</p>
</section>
<section id="demonstração-7" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-7">Demonstração</h3>
<p>Seja <span class="math inline">\(W\)</span> qualquer estimador quadrado-integrável e não viesado de <span class="math inline">\(g(\theta)\)</span>. Pelo teorema de Rao–Blackwell,</p>
<p><span class="math display">\[W^*=E(W\mid T)\]</span></p>
<p>é uma função de <span class="math inline">\(T\)</span>, é não viesado e satisfaz</p>
<p><span class="math display">\[\operatorname{Var}_\theta(W^*)
\leq
\operatorname{Var}_\theta(W).\]</span></p>
<p>Como <span class="math inline">\(W^*\)</span> e <span class="math inline">\(\delta(T)\)</span> são ambos não viesados,</p>
<p><span class="math display">\[E_\theta\{W^*-\delta(T)\}=0\]</span></p>
<p>para todo <span class="math inline">\(\theta\)</span>. A completude de <span class="math inline">\(T\)</span> implica</p>
<p><span class="math display">\[P_\theta\{W^*=\delta(T)\}=1\]</span></p>
<p>para todo <span class="math inline">\(\theta\)</span>. Portanto,</p>
<p><span class="math display">\[\operatorname{Var}_\theta\{\delta(T)\}
=
\operatorname{Var}_\theta(W^*)
\leq
\operatorname{Var}_\theta(W).\]</span></p>
<p>Como <span class="math inline">\(W\)</span> era arbitrário, <span class="math inline">\(\delta(T)\)</span> é ENVUM.</p>
<p>Para provar unicidade, sejam <span class="math inline">\(\delta_1(T)\)</span> e <span class="math inline">\(\delta_2(T)\)</span> duas funções não viesadas de <span class="math inline">\(T\)</span> para o mesmo alvo. Então</p>
<p><span class="math display">\[E_\theta\{\delta_1(T)-\delta_2(T)\}=0\]</span></p>
<p>para todo <span class="math inline">\(\theta\)</span>. Pela completude,</p>
<p><span class="math display">\[\delta_1(T)=\delta_2(T)\]</span></p>
<p>quase certamente.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="hogg1978">Hogg; Craig (<a href="#ref-hogg1978" role="doc-biblioref">1978, cap. 10</a>, sequência entre Rao–Blackwell, completude e Lehmann–Scheffé)</span>.<br>
<strong>Adaptação:</strong> prova reorganizada na forma moderna “existência por Rao–Blackwell e unicidade por completude”.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-9-desigualdade-de-cramérrao" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-9-desigualdade-de-cramérrao">Demonstração 9 — Desigualdade de Cramér–Rao</h2>
<section id="enunciado-8" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-8">Enunciado</h3>
<p>Considere uma amostra i.i.d. de densidade <span class="math inline">\(f(x;\theta)\)</span> e um estimador quadrado-integrável <span class="math inline">\(W\)</span> tal que</p>
<p><span class="math display">\[E_\theta(W)=g(\theta),\]</span></p>
<p>em que <span class="math inline">\(g\)</span> é diferenciável. Sob condições que permitem diferenciar sob o sinal de integral, com suporte independente de <span class="math inline">\(\theta\)</span> e informação de Fisher finita e positiva,</p>
<p><span class="math display">\[\operatorname{Var}_\theta(W)
\geq
\frac{[g'(\theta)]^2}{I_n(\theta)},\]</span></p>
<p>onde</p>
<p><span class="math display">\[I_n(\theta)
=
E_\theta\left[
\left(
\frac{\partial}{\partial\theta}\ell_n(\theta)
\right)^2
\right].\]</span></p>
</section>
<section id="demonstração-8" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-8">Demonstração</h3>
<p>Defina o escore</p>
<p><span class="math display">\[U_n(\theta)=\frac{\partial}{\partial\theta}\ell_n(\theta).\]</span></p>
<p>Pelas condições de regularidade,</p>
<p><span class="math display">\[E_\theta\{U_n(\theta)\}=0.\]</span></p>
<p>Diferenciando <span class="math inline">\(E_\theta(W)=g(\theta)\)</span> em relação a <span class="math inline">\(\theta\)</span>,</p>
<p><span class="math display">\[g'(\theta)
=
\int W(x)\frac{\partial}{\partial\theta}f_\theta(x)\,dx.\]</span></p>
<p>Como</p>
<p><span class="math display">\[\frac{\partial}{\partial\theta}f_\theta(x)
=
f_\theta(x)U_n(\theta;x),\]</span></p>
<p>segue que</p>
<p><span class="math display">\[g'(\theta)
=
E_\theta\{WU_n(\theta)\}.\]</span></p>
<p>Usando <span class="math inline">\(E(U_n)=0\)</span>,</p>
<p><span class="math display">\[g'(\theta)
=
E_\theta\{[W-g(\theta)]U_n(\theta)\}
=
\operatorname{Cov}_\theta(W,U_n).\]</span></p>
<p>Pela desigualdade de Cauchy–Schwarz,</p>
<p><span class="math display">\[[g'(\theta)]^2
\leq
\operatorname{Var}_\theta(W)
\operatorname{Var}_\theta(U_n).\]</span></p>
<p>Como <span class="math inline">\(\operatorname{Var}(U_n)=I_n(\theta)\)</span>,</p>
<p><span class="math display">\[\operatorname{Var}_\theta(W)
\geq
\frac{[g'(\theta)]^2}{I_n(\theta)}.\]</span></p>
<div class="callout callout-style-default callout-warning callout-titled" title="Regularidade">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Regularidade
</div>
</div>
<div class="callout-body-container callout-body">
<p>A prova falha quando o suporte depende de <span class="math inline">\(\theta\)</span> ou quando não se pode permutar diferenciação e integração. Modelos uniformes com extremo desconhecido são exemplos clássicos em que a forma regular da desigualdade não deve ser aplicada mecanicamente.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="hogg1978">Hogg; Craig (<a href="#ref-hogg1978" role="doc-biblioref">1978, seç. 11.1</a>)</span>.<br>
<strong>Fonte complementar:</strong> <span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012, seç. 5.5</a>, para a interpretação como limite inferior)</span>.<br>
<strong>Adaptação:</strong> formulação para um alvo geral <span class="math inline">\(g(\theta)\)</span>.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-10-invariância-do-estimador-de-máxima-verossimilhança" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-10-invariância-do-estimador-de-máxima-verossimilhança">Demonstração 10 — Invariância do estimador de máxima verossimilhança</h2>
<section id="enunciado-9" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-9">Enunciado</h3>
<p>Se <span class="math inline">\(\widehat\theta\)</span> maximiza <span class="math inline">\(L(\theta;x)\)</span> e <span class="math inline">\(\eta=h(\theta)\)</span> é uma transformação bijetiva, então o EMV de <span class="math inline">\(\eta\)</span> é</p>
<p><span class="math display">\[\widehat\eta=h(\widehat\theta).\]</span></p>
</section>
<section id="demonstração-9" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-9">Demonstração</h3>
<p>Escreva a verossimilhança na parametrização <span class="math inline">\(\eta\)</span> como</p>
<p><span class="math display">\[L_\eta(\eta;x)
=
L_\theta(h^{-1}(\eta);x).\]</span></p>
<p>Como <span class="math inline">\(h\)</span> é bijetiva, maximizar sobre <span class="math inline">\(\eta\)</span> equivale a maximizar sobre <span class="math inline">\(\theta\)</span>. Para qualquer <span class="math inline">\(\eta\)</span> existe exatamente um <span class="math inline">\(\theta=h^{-1}(\eta)\)</span> e</p>
<p><span class="math display">\[L_\eta(\eta;x)
=
L_\theta(\theta;x)
\leq
L_\theta(\widehat\theta;x)
=
L_\eta(h(\widehat\theta);x).\]</span></p>
<p>Portanto, <span class="math inline">\(h(\widehat\theta)\)</span> maximiza a verossimilhança na nova parametrização.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Transformações não injetivas">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Transformações não injetivas
</div>
</div>
<div class="callout-body-container callout-body">
<p>A fonte demonstra a propriedade para transformações invertíveis. A versão frequentemente citada para transformações não injetivas exige definir cuidadosamente a verossimilhança do parâmetro transformado, em geral por maximização sobre as fibras <span class="math inline">\(\{\theta:h(\theta)=\eta\}\)</span>. Essa generalização precisa de verificação bibliográfica antes de ser apresentada como automática.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="chihara2022">Chihara; Hesterberg (<a href="#ref-chihara2022" role="doc-biblioref">2022, seç. 6.3.5</a>, Proposição 6.6)</span>.<br>
<strong>Adaptação:</strong> escrita explícita da verossimilhança reparametrizada.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-14-teorema-de-gaussmarkov" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-14-teorema-de-gaussmarkov">Demonstração 14 — Teorema de Gauss–Markov</h2>
<section id="enunciado-10" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-10">Enunciado</h3>
<p>No modelo linear</p>
<p><span class="math display">\[Y=X\beta+\varepsilon,\]</span></p>
<p>suponha que <span class="math inline">\(X\)</span> tenha posto completo, <span class="math inline">\(E(\varepsilon)=0\)</span> e</p>
<p><span class="math display">\[\operatorname{Var}(\varepsilon)=\sigma^2I_n.\]</span></p>
<p>Então, para qualquer combinação estimável <span class="math inline">\(a^\top\beta\)</span>, o estimador de mínimos quadrados</p>
<p><span class="math display">\[a^\top\widehat\beta,
\qquad
\widehat\beta=(X^\top X)^{-1}X^\top Y,\]</span></p>
<p>é o estimador linear não viesado de variância mínima.</p>
</section>
<section id="demonstração-10" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-10">Demonstração</h3>
<p>Um estimador linear de <span class="math inline">\(a^\top\beta\)</span> tem a forma <span class="math inline">\(c^\top Y\)</span>. Ele é não viesado se</p>
<p><span class="math display">\[E(c^\top Y)=c^\top X\beta=a^\top\beta\]</span></p>
<p>para todo <span class="math inline">\(\beta\)</span>, ou seja,</p>
<p><span class="math display">\[X^\top c=a.\]</span></p>
<p>Defina</p>
<p><span class="math display">\[c_0=X(X^\top X)^{-1}a.\]</span></p>
<p>Então <span class="math inline">\(X^\top c_0=a\)</span>, e</p>
<p><span class="math display">\[c_0^\top Y=a^\top\widehat\beta.\]</span></p>
<p>Qualquer outro vetor <span class="math inline">\(c\)</span> que satisfaça <span class="math inline">\(X^\top c=a\)</span> pode ser escrito como</p>
<p><span class="math display">\[c=c_0+d,\]</span></p>
<p>com</p>
<p><span class="math display">\[X^\top d=0.\]</span></p>
<p>Como <span class="math inline">\(c_0\)</span> pertence ao espaço coluna de <span class="math inline">\(X\)</span> e <span class="math inline">\(d\)</span> é ortogonal a esse espaço,</p>
<p><span class="math display">\[c_0^\top d=0.\]</span></p>
<p>Assim,</p>
<p><span class="math display">\[\operatorname{Var}(c^\top Y)
=
\sigma^2c^\top c
=
\sigma^2(c_0+d)^\top(c_0+d)
=
\sigma^2c_0^\top c_0+
\sigma^2d^\top d.\]</span></p>
<p>Logo,</p>
<p><span class="math display">\[\operatorname{Var}(c^\top Y)
\geq
\operatorname{Var}(c_0^\top Y),\]</span></p>
<p>com igualdade somente se <span class="math inline">\(d=0\)</span>. Portanto, <span class="math inline">\(a^\top\widehat\beta\)</span> é BLUE.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="rasch2018">Rasch; Schott (<a href="#ref-rasch2018" role="doc-biblioref">2018</a>, Teorema 4.3)</span>.<br>
<strong>Adaptação:</strong> prova reescrita na parametrização matricial usual <span class="math inline">\(Y=X\beta+\varepsilon\)</span> e em termos de projeções ortogonais.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-22-estimadores-de-bayes-sob-perdas-quadrática-absoluta-e-01" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-22-estimadores-de-bayes-sob-perdas-quadrática-absoluta-e-01">Demonstração 22 — Estimadores de Bayes sob perdas quadrática, absoluta e <span class="math inline">\(0\)</span>–<span class="math inline">\(1\)</span></h2>
<p>Seja <span class="math inline">\(\pi(\theta\mid x)\)</span> a distribuição posterior e</p>
<p><span class="math display">\[r(a\mid x)=E\{L(\theta,a)\mid x\}\]</span></p>
<p>o risco posterior de escolher a ação <span class="math inline">\(a\)</span>.</p>
<section id="perda-quadrática" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="perda-quadrática">Perda quadrática</h3>
<p>Para</p>
<p><span class="math display">\[L(\theta,a)=(a-\theta)^2,\]</span></p>
<p>escreva <span class="math inline">\(m=E(\theta\mid x)\)</span>. Então</p>
<p><span class="math display">\[E\{(a-\theta)^2\mid x\}
=
E\{[(a-m)+(m-\theta)]^2\mid x\}.\]</span></p>
<p>O termo cruzado é zero, pois <span class="math inline">\(E(m-\theta\mid x)=0\)</span>. Logo,</p>
<p><span class="math display">\[r(a\mid x)
=(a-m)^2+
\operatorname{Var}(\theta\mid x),\]</span></p>
<p>que é minimizado em</p>
<p><span class="math display">\[a^*=E(\theta\mid x).\]</span></p>
</section>
<section id="perda-absoluta" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="perda-absoluta">Perda absoluta</h3>
<p>Para</p>
<p><span class="math display">\[L(\theta,a)=|a-\theta|,\]</span></p>
<p>suponha uma posterior contínua. O risco pode ser escrito como</p>
<p><span class="math display">\[r(a\mid x)
=
\int_{-\infty}^a(a-\theta)\pi(\theta\mid x)\,d\theta
+
\int_a^\infty(\theta-a)\pi(\theta\mid x)\,d\theta.\]</span></p>
<p>Derivando em relação a <span class="math inline">\(a\)</span>,</p>
<p><span class="math display">\[\frac{d}{da}r(a\mid x)
=
P(\theta\leq a\mid x)-P(\theta&gt;a\mid x)
=
2F(a\mid x)-1.\]</span></p>
<p>O mínimo ocorre quando</p>
<p><span class="math display">\[F(a\mid x)=\frac12.\]</span></p>
<p>Portanto, qualquer mediana posterior é uma ação de Bayes.</p>
</section>
<section id="perda-01-no-caso-discreto" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="perda-01-no-caso-discreto">Perda <span class="math inline">\(0\)</span>–<span class="math inline">\(1\)</span> no caso discreto</h3>
<p>Se</p>
<p><span class="math display">\[L(\theta,a)=
\begin{cases}
0,&amp;a=\theta,\\
1,&amp;a\neq\theta,
\end{cases}\]</span></p>
<p>então</p>
<p><span class="math display">\[r(a\mid x)
=P(\theta\neq a\mid x)
=1-P(\theta=a\mid x).\]</span></p>
<p>Minimizar o risco equivale a maximizar <span class="math inline">\(P(\theta=a\mid x)\)</span>. Logo, a ação de Bayes é uma moda posterior.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Parâmetro contínuo e perda 0--1">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Parâmetro contínuo e perda 0–1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para posteriores contínuas, <span class="math inline">\(P(\theta=a\mid x)=0\)</span> para todo ponto <span class="math inline">\(a\)</span>, de modo que a perda pontual <span class="math inline">\(0\)</span>–<span class="math inline">\(1\)</span> não seleciona uma ação. A identificação da moda pode ser justificada por uma perda de vizinhança que tende à perda <span class="math inline">\(0\)</span>–<span class="math inline">\(1\)</span>, mas essa passagem exige formulação adicional.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="ramachandran2021r">Ramachandran; Tsokos (<a href="#ref-ramachandran2021r" role="doc-biblioref">2021, seç. 10.2.1</a>)</span> para as perdas quadrática e absoluta.<br>
<strong>Complemento autoral:</strong> o argumento para a perda <span class="math inline">\(0\)</span>–<span class="math inline">\(1\)</span> discreta é uma derivação direta do risco posterior e não foi localizado na seção citada da fonte principal.<br>
<strong>Adaptação:</strong> a prova quadrática foi reescrita por decomposição em torno da média posterior; a prova da perda absoluta explicita a derivada do risco.</p>
</div>
</div>
</section>
</section>
</section>
<section id="verossimilhança-e-teoria-assintótica" class="level1 unnumbered">
<h1 class="unnumbered">Verossimilhança e teoria assintótica</h1>
<section id="demonstração-16-consistência-do-emv-em-famílias-exponenciais-regulares" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-16-consistência-do-emv-em-famílias-exponenciais-regulares">Demonstração 16 — Consistência do EMV em famílias exponenciais regulares</h2>
<section id="enunciado-11" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-11">Enunciado</h3>
<p>Considere uma família exponencial mínima e regular em forma canônica,</p>
<p><span class="math display">\[f_\theta(x)=h(x)\exp\{\theta^\top t(x)-\psi(\theta)\},\]</span></p>
<p>com <span class="math inline">\(\theta\)</span> em um conjunto aberto. O EMV é assintoticamente bem definido — isto é, existe com probabilidade tendendo a um — e</p>
<p><span class="math display">\[\widehat\theta_n\xrightarrow{P}\theta.\]</span></p>
</section>
<section id="demonstração-11" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-11">Demonstração</h3>
<p>A log-verossimilhança média é</p>
<p><span class="math display">\[\frac{1}{n}\ell_n(\theta)
=
\theta^\top\bar T_n-\psi(\theta)+C(x),\]</span></p>
<p>onde</p>
<p><span class="math display">\[\bar T_n=\frac{1}{n}\sum_{i=1}^nt(X_i).\]</span></p>
<p>A equação de escore é</p>
<p><span class="math display">\[\nabla\psi(\widehat\theta_n)=\bar T_n.\]</span></p>
<p>Defina o parâmetro de média</p>
<p><span class="math display">\[\tau(\theta)=E_\theta\{t(X)\}=\nabla\psi(\theta).\]</span></p>
<p>Em uma família mínima e regular,</p>
<p><span class="math display">\[D\tau(\theta)
=
\nabla^2\psi(\theta)
=
\operatorname{Var}_\theta\{t(X)\}\]</span></p>
<p>é positiva definida. Consequentemente, <span class="math inline">\(\tau\)</span> é localmente invertível e, na parametrização mínima, injetiva. Como a imagem de <span class="math inline">\(\tau\)</span> é aberta, a lei dos grandes números implica que <span class="math inline">\(\bar T_n\)</span> pertence a essa imagem com probabilidade tendendo a um. Nesse evento,</p>
<p><span class="math display">\[\widehat\theta_n=\tau^{-1}(\bar T_n).\]</span></p>
<p>Pela lei dos grandes números,</p>
<p><span class="math display">\[\bar T_n\xrightarrow{P}\tau(\theta).\]</span></p>
<p>Pela continuidade de <span class="math inline">\(\tau^{-1}\)</span>,</p>
<p><span class="math display">\[\widehat\theta_n
=
\tau^{-1}(\bar T_n)
\xrightarrow{P}
\tau^{-1}\{\tau(\theta)\}
=
\theta.\]</span></p>
<div class="callout callout-style-default callout-warning callout-titled" title="Escopo do resultado">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Escopo do resultado
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta é uma prova para famílias exponenciais mínimas e regulares. Ela não constitui uma prova geral da consistência do EMV em modelos paramétricos arbitrários. Em modelos não regulares, com parâmetros incidentais ou suporte dependente do parâmetro, o EMV pode ser inconsistente.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="lauritzen2023fundamentals">Lauritzen (<a href="#ref-lauritzen2023fundamentals" role="doc-biblioref">2023</a>, Teorema 5.9)</span>.<br>
<strong>Adaptação:</strong> explicitação da equação de escore e do uso do mapa entre parâmetro canônico e parâmetro de média.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-17-normalidade-assintótica-do-emv" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-17-normalidade-assintótica-do-emv">Demonstração 17 — Normalidade assintótica do EMV</h2>
<section id="enunciado-12" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-12">Enunciado</h3>
<p>Nas condições da demonstração anterior,</p>
<p><span class="math display">\[\sqrt n(\widehat\theta_n-\theta)
\xrightarrow{d}
N_k\{0,I(\theta)^{-1}\},\]</span></p>
<p>onde</p>
<p><span class="math display">\[I(\theta)=\operatorname{Var}_\theta\{t(X)\}\]</span></p>
<p>é a informação de Fisher por observação.</p>
</section>
<section id="demonstração-12" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-12">Demonstração</h3>
<p>Pelo Teorema Central do Limite multivariado,</p>
<p><span class="math display">\[\sqrt n\{\bar T_n-\tau(\theta)\}
\xrightarrow{d}
N_k\{0,\kappa(\theta)\},\]</span></p>
<p>onde</p>
<p><span class="math display">\[\kappa(\theta)
=
\operatorname{Var}_\theta\{t(X)\}
=
I(\theta).\]</span></p>
<p>Como</p>
<p><span class="math display">\[\widehat\theta_n=\tau^{-1}(\bar T_n),\]</span></p>
<p>aplicamos o método delta à função <span class="math inline">\(\tau^{-1}\)</span>. Pelo teorema da função inversa,</p>
<p><span class="math display">\[D\tau^{-1}\{\tau(\theta)\}
=
[D\tau(\theta)]^{-1}
=
\kappa(\theta)^{-1}.\]</span></p>
<p>Portanto,</p>
<p><span class="math display">\[\sqrt n(\widehat\theta_n-\theta)
\xrightarrow{d}
N_k\left(
0,
\kappa^{-1}\kappa\kappa^{-1}
\right),\]</span></p>
<p>isto é,</p>
<p><span class="math display">\[\sqrt n(\widehat\theta_n-\theta)
\xrightarrow{d}
N_k\{0,I(\theta)^{-1}\}.\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled" title="Interpretação">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Interpretação
</div>
</div>
<div class="callout-body-container callout-body">
<p>A matriz de covariância assintótica coincide com o inverso da informação de Fisher. Nesse sentido regular, o EMV alcança assintoticamente o limite informacional.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="lauritzen2023fundamentals">Lauritzen (<a href="#ref-lauritzen2023fundamentals" role="doc-biblioref">2023</a>, Teorema 5.11)</span>.<br>
<strong>Adaptação:</strong> apresentação explícita como aplicação do TCL multivariado e do método delta ao mapa inverso.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-18-método-delta-univariado-e-multivariado" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-18-método-delta-univariado-e-multivariado">Demonstração 18 — Método delta univariado e multivariado</h2>
<section id="enunciado-13" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-13">Enunciado</h3>
<p>Suponha que</p>
<p><span class="math display">\[\sqrt n(X_n-\xi)\xrightarrow{d}N_k(0,\Sigma)\]</span></p>
<p>e que <span class="math inline">\(g:\mathbb R^k\to\mathbb R^m\)</span> seja diferenciável em <span class="math inline">\(\xi\)</span>. Então</p>
<p><span class="math display">\[\sqrt n\{g(X_n)-g(\xi)\}
\xrightarrow{d}
N_m\{0,Dg(\xi)\Sigma Dg(\xi)^\top\}.\]</span></p>
</section>
<section id="demonstração-13" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-13">Demonstração</h3>
<p>Pela diferenciabilidade,</p>
<p><span class="math display">\[g(X_n)-g(\xi)
=
Dg(\xi)(X_n-\xi)+r(X_n-\xi),\]</span></p>
<p>com</p>
<p><span class="math display">\[\frac{\|r(h)\|}{\|h\|}\to 0
\quad\text{quando }h\to 0.\]</span></p>
<p>Como a convergência em distribuição da sequência escalada implica <span class="math inline">\(X_n\xrightarrow{P}\xi\)</span>, temos</p>
<p><span class="math display">\[r(X_n-\xi)
=o_P(\|X_n-\xi\|).\]</span></p>
<p>Multiplicando por <span class="math inline">\(\sqrt n\)</span>,</p>
<p><span class="math display">\[\sqrt n\{g(X_n)-g(\xi)\}
=
Dg(\xi)\sqrt n(X_n-\xi)
+
o_P\{\sqrt n\|X_n-\xi\|\}.\]</span></p>
<p>A sequência <span class="math inline">\(\sqrt n(X_n-\xi)\)</span> é limitada em probabilidade, de modo que o termo de resto é <span class="math inline">\(o_P(1)\)</span>. Assim,</p>
<p><span class="math display">\[\sqrt n\{g(X_n)-g(\xi)\}
=
Dg(\xi)\sqrt n(X_n-\xi)+o_P(1).\]</span></p>
<p>Pelo teorema de Slutsky,</p>
<p><span class="math display">\[\sqrt n\{g(X_n)-g(\xi)\}
\xrightarrow{d}
Dg(\xi)Z,\]</span></p>
<p>onde <span class="math inline">\(Z\sim N_k(0,\Sigma)\)</span>. Como uma transformação linear de um vetor normal é normal,</p>
<p><span class="math display">\[Dg(\xi)Z
\sim
N_m\{0,Dg(\xi)\Sigma Dg(\xi)^\top\}.\]</span></p>
<p>No caso univariado,</p>
<p><span class="math display">\[\sqrt n\{g(X_n)-g(\xi)\}
\xrightarrow{d}
N\left(0,[g'(\xi)]^2\sigma^2\right).\]</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="lauritzen2023fundamentals">Lauritzen (<a href="#ref-lauritzen2023fundamentals" role="doc-biblioref">2023</a>, Teorema A.19)</span>.<br>
<strong>Adaptação:</strong> notação de resto vetorial e explicitação do passo <span class="math inline">\(o_P(1)\)</span>.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-19-equivalência-assintótica-entre-wald-escore-e-razão-de-verossimilhanças" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-19-equivalência-assintótica-entre-wald-escore-e-razão-de-verossimilhanças">Demonstração 19 — Equivalência assintótica entre Wald, escore e razão de verossimilhanças</h2>
<section id="enunciado-14" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-14">Enunciado</h3>
<p>Considere um modelo regular uniparamétrico e o teste de</p>
<p><span class="math display">\[H_0:\theta=\theta_0.\]</span></p>
<p>Defina</p>
<p><span class="math display">\[W_n=I_n(\theta_0)(\widehat\theta-\theta_0)^2,\]</span></p>
<p><span class="math display">\[S_n=\frac{U_n(\theta_0)^2}{I_n(\theta_0)}\]</span></p>
<p>e</p>
<p><span class="math display">\[R_n=2\{\ell_n(\widehat\theta)-\ell_n(\theta_0)\}.\]</span></p>
<p>Sob <span class="math inline">\(H_0\)</span> e condições de regularidade,</p>
<p><span class="math display">\[W_n=S_n+o_P(1)=R_n+o_P(1),\]</span></p>
<p>e cada estatística converge para <span class="math inline">\(\chi^2_1\)</span>.</p>
</section>
<section id="demonstração-14" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-14">Demonstração</h3>
<p>A equação de escore no EMV é</p>
<p><span class="math display">\[U_n(\widehat\theta)=0.\]</span></p>
<p>Expanda em torno de <span class="math inline">\(\theta_0\)</span>:</p>
<p><span class="math display">\[0
=
U_n(\theta_0)
+
\ell_n''(\widetilde\theta)(\widehat\theta-\theta_0),\]</span></p>
<p>onde <span class="math inline">\(\widetilde\theta\)</span> está entre <span class="math inline">\(\widehat\theta\)</span> e <span class="math inline">\(\theta_0\)</span>. Sob regularidade,</p>
<p><span class="math display">\[-\ell_n''(\widetilde\theta)
=
I_n(\theta_0)+o_P(n).\]</span></p>
<p>Logo,</p>
<p><span class="math display">\[\widehat\theta-\theta_0
=
\frac{U_n(\theta_0)}{I_n(\theta_0)}+o_P(n^{-1/2}).\]</span></p>
<p>Substituindo no estatístico de Wald,</p>
<p><span class="math display">\[W_n
=
I_n(\theta_0)
\left[
\frac{U_n(\theta_0)}{I_n(\theta_0)}+o_P(n^{-1/2})
\right]^2
=
\frac{U_n(\theta_0)^2}{I_n(\theta_0)}+o_P(1)
=
S_n+o_P(1).\]</span></p>
<p>Agora expanda a log-verossimilhança em torno de <span class="math inline">\(\widehat\theta\)</span>:</p>
<p><span class="math display">\[\ell_n(\theta_0)
=
\ell_n(\widehat\theta)
+
\frac12\ell_n''(\bar\theta)(\theta_0-\widehat\theta)^2,\]</span></p>
<p>pois <span class="math inline">\(U_n(\widehat\theta)=0\)</span>. Assim,</p>
<p><span class="math display">\[R_n
=
-\ell_n''(\bar\theta)(\widehat\theta-\theta_0)^2
=
I_n(\theta_0)(\widehat\theta-\theta_0)^2+o_P(1)
=
W_n+o_P(1).\]</span></p>
<p>Por fim,</p>
<p><span class="math display">\[\frac{U_n(\theta_0)}{\sqrt{I_n(\theta_0)}}
\xrightarrow{d}N(0,1),\]</span></p>
<p>portanto</p>
<p><span class="math display">\[S_n\xrightarrow{d}\chi^2_1,\]</span></p>
<p>e o mesmo vale para <span class="math inline">\(W_n\)</span> e <span class="math inline">\(R_n\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fontes principais:</strong> <span class="citation" data-cites="cox2006principles">Cox (<a href="#ref-cox2006principles" role="doc-biblioref">2006</a>)</span> [Capítulo 6, aproximação quadrática da log-verossimilhança]; <span class="citation" data-cites="lauritzen2023fundamentals">Lauritzen (<a href="#ref-lauritzen2023fundamentals" role="doc-biblioref">2023, seç. 5.3.3</a> e 5.4.4)</span>.<br>
<strong>Adaptação:</strong> prova escalar unificada por duas expansões de Taylor.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-20-teorema-de-wilks-para-uma-subfamília-exponencial-curva" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-20-teorema-de-wilks-para-uma-subfamília-exponencial-curva">Demonstração 20 — Teorema de Wilks para uma subfamília exponencial curva</h2>
<section id="enunciado-15" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-15">Enunciado</h3>
<p>Considere uma família exponencial curva regular de dimensão <span class="math inline">\(m\)</span> contendo uma subfamília curva regular de dimensão <span class="math inline">\(d\)</span>. Sob a hipótese de que o parâmetro verdadeiro pertence à subfamília,</p>
<p><span class="math display">\[-2\log\Lambda_n
=
2\{\ell_n(\widehat\theta)-\ell_n(\widetilde\theta)\}
\xrightarrow{d}
\chi^2_{m-d},\]</span></p>
<p>onde <span class="math inline">\(\widehat\theta\)</span> é o EMV irrestrito e <span class="math inline">\(\widetilde\theta\)</span> é o EMV sob a restrição.</p>
</section>
<section id="demonstração-15" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-15">Demonstração</h3>
<p>Sob regularidade, a log-verossimilhança admite uma aproximação quadrática local. Em coordenadas padronizadas pela informação de Fisher, escreva</p>
<p><span class="math display">\[h=\sqrt n\,I(\theta_0)^{1/2}(\theta-\theta_0).\]</span></p>
<p>Uniformemente em conjuntos limitados de <span class="math inline">\(h\)</span>,</p>
<p><span class="math display">\[\ell_n\left(\theta_0 + \frac{I(\theta_0)^{-1/2}h}{\sqrt n}\right) - \ell_n(\theta_0)
=h^\top Z_n-\frac12h^\top h+o_P(1),\]</span></p>
<p>com</p>
<p><span class="math display">\[Z_n\xrightarrow{d}N_m(0,I_m).\]</span></p>
<p>No modelo irrestrito, a função quadrática é maximizada em <span class="math inline">\(h=Z_n\)</span>, com máximo</p>
<p><span class="math display">\[\frac12\|Z_n\|^2.\]</span></p>
<p>Localmente, a hipótese restrita corresponde a um subespaço tangente <span class="math inline">\(\mathcal T\)</span> de dimensão <span class="math inline">\(d\)</span>. O máximo restrito ocorre na projeção ortogonal <span class="math inline">\(\Pi_{\mathcal T}Z_n\)</span>, com valor</p>
<p><span class="math display">\[\frac12\|\Pi_{\mathcal T}Z_n\|^2.\]</span></p>
<p>Consequentemente,</p>
<p><span class="math display">\[-2\log\Lambda_n
=
\|Z_n\|^2-
\|\Pi_{\mathcal T}Z_n\|^2+o_P(1)
=
\|\Pi_{\mathcal T^\perp}Z_n\|^2+o_P(1).\]</span></p>
<p>O complemento ortogonal <span class="math inline">\(\mathcal T^\perp\)</span> tem dimensão <span class="math inline">\(m-d\)</span>. A projeção de um vetor <span class="math inline">\(N_m(0,I_m)\)</span> sobre esse espaço tem <span class="math inline">\(m-d\)</span> componentes normais padrão independentes. Portanto,</p>
<p><span class="math display">\[\|\Pi_{\mathcal T^\perp}Z_n\|^2
\sim\chi^2_{m-d},\]</span></p>
<p>e o resultado segue por Slutsky.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Escopo e generalização">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Escopo e generalização
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta é a versão demonstrada por Lauritzen para subfamílias curvas de famílias exponenciais curvas. Uma formulação para modelos paramétricos regulares mais gerais exige hipóteses adicionais de diferenciabilidade quadrática, identificabilidade, existência e consistência dos estimadores e controle uniforme do resto. Não se deve usar a aproximação <span class="math inline">\(\chi^2\)</span> automaticamente em problemas de fronteira ou não identificáveis.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="lauritzen2023fundamentals">Lauritzen (<a href="#ref-lauritzen2023fundamentals" role="doc-biblioref">2023</a>, Teorema 5.39 e resultados geométricos imediatamente anteriores)</span>.<br>
<strong>Adaptação:</strong> apresentação em coordenadas informacionais e por projeção no espaço tangente, preservando o escopo de família exponencial curva da fonte.</p>
</div>
</div>
</section>
</section>
</section>
<section id="testes-de-hipóteses-e-intervalos-de-confiança" class="level1 unnumbered">
<h1 class="unnumbered">Testes de hipóteses e intervalos de confiança</h1>
<section id="demonstração-11-lema-de-neymanpearson" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-11-lema-de-neymanpearson">Demonstração 11 — Lema de Neyman–Pearson</h2>
<section id="enunciado-16" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-16">Enunciado</h3>
<p>Para testar duas hipóteses simples</p>
<p><span class="math display">\[H_0:f=f_0
\quad\text{contra}\quad
H_1:f=f_1,\]</span></p>
<p>o teste que rejeita <span class="math inline">\(H_0\)</span> quando</p>
<p><span class="math display">\[\frac{f_1(x)}{f_0(x)}&gt;k\]</span></p>
<p>é o teste mais poderoso entre todos os testes de nível no máximo <span class="math inline">\(\alpha\)</span>, escolhendo-se <span class="math inline">\(k\)</span> e eventual randomização na fronteira para obter o nível desejado.</p>
</section>
<section id="demonstração-16" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-16">Demonstração</h3>
<p>Seja <span class="math inline">\(\varphi\)</span> o teste da razão de verossimilhanças e <span class="math inline">\(\psi\)</span> qualquer outro teste com</p>
<p><span class="math display">\[E_0(\psi)\leq E_0(\varphi)=\alpha.\]</span></p>
<p>Pela construção de <span class="math inline">\(\varphi\)</span>,</p>
<p><span class="math display">\[[\varphi(x)-\psi(x)]\{f_1(x)-kf_0(x)\}\geq 0\]</span></p>
<p>para todo <span class="math inline">\(x\)</span>: na região em que <span class="math inline">\(f_1-kf_0&gt;0\)</span>, <span class="math inline">\(\varphi\)</span> toma o maior valor possível; fora dela, toma o menor.</p>
<p>Integrando,</p>
<p><span class="math display">\[\int(\varphi-\psi)f_1
\geq
k\int(\varphi-\psi)f_0.\]</span></p>
<p>O lado direito é não negativo, pois</p>
<p><span class="math display">\[\int\varphi f_0-
\int\psi f_0
=
E_0(\varphi)-E_0(\psi)
\geq 0.\]</span></p>
<p>Logo,</p>
<p><span class="math display">\[E_1(\varphi)-E_1(\psi)
\geq 0.\]</span></p>
<p>Portanto, a potência de <span class="math inline">\(\varphi\)</span> é pelo menos tão grande quanto a de qualquer teste concorrente de nível não superior a <span class="math inline">\(\alpha\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="rice2007mathematical">Rice (<a href="#ref-rice2007mathematical" role="doc-biblioref">2007, seç. 9.2</a>)</span>.<br>
<strong>Fonte complementar:</strong> <span class="citation" data-cites="ramachandran2021r">Ramachandran; Tsokos (<a href="#ref-ramachandran2021r" role="doc-biblioref">2021</a>, capítulo de testes de hipóteses)</span>.<br>
<strong>Adaptação:</strong> razão escrita como <span class="math inline">\(f_1/f_0\)</span> e prova expressa por funções de teste.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-12-teorema-de-karlinrubin" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-12-teorema-de-karlinrubin">Demonstração 12 — Teorema de Karlin–Rubin</h2>
<section id="enunciado-17" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-17">Enunciado</h3>
<p>Suponha que a família de distribuições da estatística suficiente <span class="math inline">\(T\)</span> tenha razão de verossimilhanças monótona crescente em <span class="math inline">\(T\)</span>. Para testar</p>
<p><span class="math display">\[H_0:\theta\leq\theta_0
\quad\text{contra}\quad
H_1:\theta&gt;\theta_0,\]</span></p>
<p>o teste que rejeita para valores grandes de <span class="math inline">\(T\)</span> e tem tamanho <span class="math inline">\(\alpha\)</span> em <span class="math inline">\(\theta_0\)</span> é uniformemente mais poderoso de nível <span class="math inline">\(\alpha\)</span>.</p>
</section>
<section id="demonstração-17" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-17">Demonstração</h3>
<p>Escolha <span class="math inline">\(c\)</span> e, se necessário, uma probabilidade de randomização <span class="math inline">\(\gamma\)</span> tais que</p>
<p><span class="math display">\[E_{\theta_0}\{\varphi(T)\}=\alpha,\]</span></p>
<p>onde</p>
<p><span class="math display">\[\varphi(t)=
\begin{cases}
1,&amp;t&gt;c,\\
\gamma,&amp;t=c,\\
0,&amp;t&lt;c.
\end{cases}\]</span></p>
<p>Fixe uma alternativa <span class="math inline">\(\theta_1&gt;\theta_0\)</span>. A razão</p>
<p><span class="math display">\[\frac{f_T(t;\theta_1)}{f_T(t;\theta_0)}\]</span></p>
<p>é crescente em <span class="math inline">\(t\)</span>. Pelo lema de Neyman–Pearson, o teste mais poderoso para</p>
<p><span class="math display">\[H_0:\theta=\theta_0
\quad\text{contra}\quad
H_1:\theta=\theta_1\]</span></p>
<p>rejeita para valores grandes de <span class="math inline">\(T\)</span>. A região crítica é a mesma para qualquer <span class="math inline">\(\theta_1&gt;\theta_0\)</span>, pois o ponto de corte é determinado pela distribuição em <span class="math inline">\(\theta_0\)</span> e pelo nível <span class="math inline">\(\alpha\)</span>.</p>
<p>Além disso, a propriedade de razão de verossimilhanças monótona implica que</p>
<p><span class="math display">\[E_\theta\{\varphi(T)\}\]</span></p>
<p>é não decrescente em <span class="math inline">\(\theta\)</span>. Consequentemente,</p>
<p><span class="math display">\[\sup_{\theta\leq\theta_0}
E_\theta\{\varphi(T)\}
=
E_{\theta_0}\{\varphi(T)\}
=
\alpha.\]</span></p>
<p>Logo, <span class="math inline">\(\varphi\)</span> é um teste de nível <span class="math inline">\(\alpha\)</span> para a hipótese composta. Como ele é mais poderoso para cada alternativa simples <span class="math inline">\(\theta_1&gt;\theta_0\)</span>, é uniformemente mais poderoso contra toda a alternativa unilateral.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="rasch2018">Rasch; Schott (<a href="#ref-rasch2018" role="doc-biblioref">2018, seç. 3.3.1</a>, Teoremas 3.6–3.8 e Corolário 3.3)</span>.<br>
<strong>Adaptação:</strong> o resultado é apresentado sob o nome usual de Karlin–Rubin, combinando o argumento de monotonicidade da potência com Neyman–Pearson.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-13-dualidade-entre-testes-e-regiões-de-confiança" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-13-dualidade-entre-testes-e-regiões-de-confiança">Demonstração 13 — Dualidade entre testes e regiões de confiança</h2>
<section id="enunciado-18" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-18">Enunciado</h3>
<p>Para cada <span class="math inline">\(\theta_0\)</span>, suponha que <span class="math inline">\(A(\theta_0)\)</span> seja a região de não rejeição de um teste de nível <span class="math inline">\(\alpha\)</span> de</p>
<p><span class="math display">\[H_0:\theta=\theta_0,\]</span></p>
<p>de modo que</p>
<p><span class="math display">\[P_{\theta_0}\{X\notin A(\theta_0)\}\leq\alpha.\]</span></p>
<p>Então</p>
<p><span class="math display">\[C(X)=\{\theta_0:X\in A(\theta_0)\}\]</span></p>
<p>é uma região de confiança com cobertura pelo menos <span class="math inline">\(1-\alpha\)</span>:</p>
<p><span class="math display">\[P_{\theta_0}\{\theta_0\in C(X)\}\geq1-\alpha.\]</span></p>
<p>Se cada teste possui tamanho exatamente <span class="math inline">\(\alpha\)</span> em <span class="math inline">\(\theta_0\)</span>, a cobertura é exatamente <span class="math inline">\(1-\alpha\)</span>.</p>
</section>
<section id="demonstração-18" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-18">Demonstração</h3>
<p>Pela definição de <span class="math inline">\(C(X)\)</span>,</p>
<p><span class="math display">\[\{\theta_0\in C(X)\}
=
\{X\in A(\theta_0)\}.\]</span></p>
<p>Portanto,</p>
<p><span class="math display">\[\begin{aligned}
P_{\theta_0}\{\theta_0\in C(X)\}
&amp;=P_{\theta_0}\{X\in A(\theta_0)\}\\
&amp;=1-P_{\theta_0}\{X\notin A(\theta_0)\}\\
&amp;\geq1-\alpha.
\end{aligned}\]</span></p>
<p>Quando <span class="math inline">\(P_{\theta_0}\{X\notin A(\theta_0)\}=\alpha\)</span>, todas as desigualdades anteriores tornam-se igualdades.</p>
<p>Reciprocamente, se <span class="math inline">\(C(X)\)</span> satisfaz</p>
<p><span class="math display">\[P_{\theta_0}\{\theta_0\in C(X)\}\geq1-\alpha\]</span></p>
<p>para todo <span class="math inline">\(\theta_0\)</span>, então</p>
<p><span class="math display">\[A(\theta_0)=\{x:\theta_0\in C(x)\}\]</span></p>
<p>é a região de não rejeição de um teste de nível no máximo <span class="math inline">\(\alpha\)</span> de <span class="math inline">\(H_0:\theta=\theta_0\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Interpretação">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Interpretação
</div>
</div>
<div class="callout-body-container callout-body">
<p>Uma região de confiança é o conjunto dos valores do parâmetro que não seriam rejeitados por uma família coerente de testes. Essa equivalência é matemática; ela não transforma a cobertura frequentista em probabilidade posterior do parâmetro.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="rice2007mathematical">Rice (<a href="#ref-rice2007mathematical" role="doc-biblioref">2007, seç. 9.3</a>, Teoremas A e B)</span>.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-15-teste-t-de-uma-amostra-como-teste-da-razão-de-verossimilhanças-generalizada" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-15-teste-t-de-uma-amostra-como-teste-da-razão-de-verossimilhanças-generalizada">Demonstração 15 — Teste <span class="math inline">\(t\)</span> de uma amostra como teste da razão de verossimilhanças generalizada</h2>
<section id="enunciado-19" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-19">Enunciado</h3>
<p>Para uma amostra i.i.d. <span class="math inline">\(N(\mu,\sigma^2)\)</span>, o teste bilateral de</p>
<p><span class="math display">\[H_0:\mu=\mu_0
\quad\text{contra}\quad
H_1:\mu\neq\mu_0\]</span></p>
<p>baseado na razão de verossimilhanças generalizada rejeita para valores grandes de</p>
<p><span class="math display">\[|T|=
\left|
\frac{\bar X-\mu_0}{S/\sqrt n}
\right|.\]</span></p>
</section>
<section id="demonstração-19" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-19">Demonstração</h3>
<p>A verossimilhança é</p>
<p><span class="math display">\[L(\mu,\sigma^2)
=
(2\pi\sigma^2)^{-n/2}
\exp\left
\{-\frac{1}{2\sigma^2}
\sum_{i=1}^n(X_i-\mu)^2
\right\}.\]</span></p>
<p>No modelo irrestrito,</p>
<p><span class="math display">\[\widehat\mu=\bar X,
\qquad
\widehat\sigma^2=
\frac{1}{n}
\sum_{i=1}^n(X_i-\bar X)^2.\]</span></p>
<p>Sob <span class="math inline">\(H_0\)</span>,</p>
<p><span class="math display">\[\widetilde\mu=\mu_0,
\qquad
\widetilde\sigma^2=
\frac{1}{n}
\sum_{i=1}^n(X_i-\mu_0)^2.\]</span></p>
<p>Após substituir esses estimadores, a razão é</p>
<p><span class="math display">\[\Lambda
=
\left[
\frac{
\sum_{i=1}^n(X_i-\bar X)^2
}{
\sum_{i=1}^n(X_i-\mu_0)^2
}
\right]^{n/2}.\]</span></p>
<p>Pela identidade</p>
<p><span class="math display">\[\sum_{i=1}^n(X_i-\mu_0)^2
=
\sum_{i=1}^n(X_i-\bar X)^2
+n(\bar X-\mu_0)^2,\]</span></p>
<p>obtemos</p>
<p><span class="math display">\[\Lambda
=
\left[
1+
\frac{n(\bar X-\mu_0)^2}
{\sum_{i=1}^n(X_i-\bar X)^2}
\right]^{-n/2}.\]</span></p>
<p>Como</p>
<p><span class="math display">\[S^2=
\frac{1}{n-1}
\sum_{i=1}^n(X_i-\bar X)^2,\]</span></p>
<p>segue que</p>
<p><span class="math display">\[\Lambda
=
\left(
1+
\frac{T^2}{n-1}
\right)^{-n/2}.\]</span></p>
<p>Essa expressão é estritamente decrescente em <span class="math inline">\(T^2\)</span>. Portanto, rejeitar para valores pequenos de <span class="math inline">\(\Lambda\)</span> equivale a rejeitar para valores grandes de <span class="math inline">\(|T|\)</span>. Sob <span class="math inline">\(H_0\)</span>, <span class="math inline">\(T\sim t_{n-1}\)</span>, produzindo o teste <span class="math inline">\(t\)</span> bilateral usual.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="larsen2012">Larsen; Marx (<a href="#ref-larsen2012" role="doc-biblioref">2012</a>, Apêndice 7.A.3)</span>.<br>
<strong>Adaptação:</strong> notação de razão de verossimilhanças e simplificação algébrica preservadas da fonte.</p>
</div>
</div>
</section>
</section>
</section>
<section id="inferência-computacional-reamostragem-e-métodos-modernos" class="level1 unnumbered">
<h1 class="unnumbered">Inferência computacional, reamostragem e métodos modernos</h1>
<section id="demonstração-21-monotonicidade-do-algoritmo-em" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-21-monotonicidade-do-algoritmo-em">Demonstração 21 — Monotonicidade do algoritmo EM</h2>
<section id="definição" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definição">Definição</h3>
<p>Se <span class="math inline">\(Y\)</span> é o dado observado, <span class="math inline">\(Z\)</span> é o dado latente e <span class="math inline">\(X=(Y,Z)\)</span> é o dado completo, suponha que as distribuições envolvidas sejam dominadas por medidas comuns, que os suportes relevantes não variem com <span class="math inline">\(\theta\)</span> e que as esperanças abaixo sejam finitas. Defina</p>
<p><span class="math display">\[Q(\theta\mid\theta^{(m)})
=
E_{\theta^{(m)}}
\{\log p(Y,Z\mid\theta)\mid Y=y\}.\]</span></p>
<p>O passo M escolhe <span class="math inline">\(\theta^{(m+1)}\)</span> de modo que</p>
<p><span class="math display">\[Q(\theta^{(m+1)}\mid\theta^{(m)})
\geq
Q(\theta^{(m)}\mid\theta^{(m)}).\]</span></p>
</section>
<section id="demonstração-20" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-20">Demonstração</h3>
<p>Seja</p>
<p><span class="math display">\[q_m(z)=p(z\mid y,\theta^{(m)}).\]</span></p>
<p>Para qualquer <span class="math inline">\(\theta\)</span>,</p>
<p><span class="math display">\[\log p(y\mid\theta)
=
\log p(y,z\mid\theta)-
\log p(z\mid y,\theta).\]</span></p>
<p>Tomando esperança em relação a <span class="math inline">\(q_m\)</span>,</p>
<p><span class="math display">\[\ell(\theta)
=
Q(\theta\mid\theta^{(m)})
-
E_{q_m}\{\log p(Z\mid y,\theta)\}.\]</span></p>
<p>Adicione e subtraia <span class="math inline">\(E_{q_m}\{\log q_m(Z)\}\)</span>. Pela definição da divergência de Kullback–Leibler,</p>
<p><span class="math display">\[D_{\mathrm{KL}}
\{q_m\|p(\cdot\mid y,\theta)\}
=
E_{q_m}
\left[
\log\frac{q_m(Z)}{p(Z\mid y,\theta)}
\right].\]</span></p>
<p>Logo,</p>
<p><span class="math display">\[\ell(\theta)
=
Q(\theta\mid\theta^{(m)})
-E_{q_m}\{\log q_m(Z)\}
+
D_{\mathrm{KL}}
\{q_m\|p(\cdot\mid y,\theta)\}.\]</span></p>
<p>Ao tomar <span class="math inline">\(\theta=\theta^{(m)}\)</span>, a divergência é zero. Portanto,</p>
<p><span class="math display">\[\ell(\theta)-\ell(\theta^{(m)})
=
Q(\theta\mid\theta^{(m)})
-Q(\theta^{(m)}\mid\theta^{(m)})
+
D_{\mathrm{KL}}
\{q_m\|p(\cdot\mid y,\theta)\}.\]</span></p>
<p>Como a divergência KL é não negativa,</p>
<p><span class="math display">\[\ell(\theta)-\ell(\theta^{(m)})
\geq
Q(\theta\mid\theta^{(m)})
-Q(\theta^{(m)}\mid\theta^{(m)}).\]</span></p>
<p>Aplicando essa desigualdade a <span class="math inline">\(\theta^{(m+1)}\)</span>,</p>
<p><span class="math display">\[\ell(\theta^{(m+1)})
\geq
\ell(\theta^{(m)}).\]</span></p>
<div class="callout callout-style-default callout-warning callout-titled" title="O que a monotonicidade não garante">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>O que a monotonicidade não garante
</div>
</div>
<div class="callout-body-container callout-body">
<p>O aumento da log-verossimilhança não garante convergência ao máximo global. O algoritmo pode convergir para um máximo local, ponto estacionário ou fronteira, e a sequência de parâmetros exige hipóteses adicionais para convergir. Além disso, a demonstração pode falhar quando o suporte do dado completo depende do parâmetro.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="gupta2011em">Gupta; Chen (<a href="#ref-gupta2011em" role="doc-biblioref">2011, seç. 1.1</a> e 2.1)</span>.<br>
<strong>Adaptação:</strong> prova escrita pela decomposição da log-verossimilhança em <span class="math inline">\(Q\)</span> e divergência KL.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-23-consistência-de-minimizadores-convexos" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-23-consistência-de-minimizadores-convexos">Demonstração 23 — Consistência de minimizadores convexos</h2>
<section id="enunciado-20" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-20">Enunciado</h3>
<p>Sejam <span class="math inline">\(Q_n:\mathbb R^d\to\mathbb R\)</span> funções aleatórias convexas e <span class="math inline">\(Q\)</span> uma função determinística. Suponha que:</p>
<ol type="1">
<li><span class="math inline">\(Q_n\to Q\)</span> uniformemente em probabilidade em todo compacto;</li>
<li><span class="math inline">\(Q\)</span> é contínua, estritamente convexa e coerciva;</li>
<li><span class="math inline">\(\widehat t_n\in\operatorname{argmin}Q_n\)</span> e <span class="math inline">\(t_0=\operatorname{argmin}Q\)</span>.</li>
</ol>
<p>Então</p>
<p><span class="math display">\[\widehat t_n\xrightarrow{P}t_0.\]</span></p>
</section>
<section id="demonstração-21" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-21">Demonstração</h3>
<p>A estrita convexidade e a coercividade de <span class="math inline">\(Q\)</span> garantem que <span class="math inline">\(t_0\)</span> existe e é único. Fixe <span class="math inline">\(\varepsilon&gt;0\)</span>. Pela continuidade e unicidade do mínimo,</p>
<p><span class="math display">\[\delta_\varepsilon
=
\inf_{\|t-t_0\|=\varepsilon}
\{Q(t)-Q(t_0)\}
&gt;0.\]</span></p>
<p>A convergência uniforme em probabilidade na esfera compacta e em uma vizinhança de <span class="math inline">\(t_0\)</span> implica que, com probabilidade tendendo a um,</p>
<p><span class="math display">\[\inf_{\|t-t_0\|=\varepsilon}Q_n(t)
&gt;
Q_n(t_0).\]</span></p>
<p>Suponha, por contradição, que <span class="math inline">\(\|\widehat t_n-t_0\|&gt;\varepsilon\)</span>. Pela convexidade, existe <span class="math inline">\(\lambda\in(0,1)\)</span> tal que</p>
<p><span class="math display">\[t_1=\lambda\widehat t_n+(1-\lambda)t_0\]</span></p>
<p>satisfaz <span class="math inline">\(\|t_1-t_0\|=\varepsilon\)</span>. Como <span class="math inline">\(\widehat t_n\)</span> minimiza <span class="math inline">\(Q_n\)</span>,</p>
<p><span class="math display">\[Q_n(t_1)
\leq
\lambda Q_n(\widehat t_n)+(1-\lambda)Q_n(t_0)
\leq
Q_n(t_0).\]</span></p>
<p>Isso contradiz a desigualdade anterior na esfera. Logo,</p>
<p><span class="math display">\[P(\|\widehat t_n-t_0\|&gt;\varepsilon)
\to 0.\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled" title="Interpretação">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Dica</span>Interpretação
</div>
</div>
<div class="callout-body-container callout-body">
<p>O resultado é um princípio geral de consistência para <span class="math inline">\(M\)</span>-estimadores: se a função-objetivo amostral aproxima uniformemente uma função populacional com mínimo bem separado, os minimizadores amostrais aproximam o minimizador populacional.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="bickel2016volume2">Bickel; Doksum (<a href="#ref-bickel2016volume2" role="doc-biblioref">2016</a>, Proposição 9.2.1)</span>.<br>
<strong>Adaptação:</strong> preservação do argumento geométrico na esfera de raio <span class="math inline">\(\varepsilon\)</span>.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-24-função-de-influência-e-eficiência-semiparamétrica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-24-função-de-influência-e-eficiência-semiparamétrica">Demonstração 24 — Função de influência e eficiência semiparamétrica</h2>
<section id="função-de-influência-de-um-funcional" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="função-de-influência-de-um-funcional">Função de influência de um funcional</h3>
<p>Para um funcional estatístico <span class="math inline">\(T(P)\)</span>, a função de influência sob contaminação pontual é, quando a derivada existe,</p>
<p><span class="math display">\[\operatorname{IF}(x;T,P)
=
\left.
\frac{d}{d\varepsilon}
T\{(1-\varepsilon)P+\varepsilon\Delta_x\}
\right|_{\varepsilon=0}.\]</span></p>
<p>Ela mede a sensibilidade local de primeira ordem do funcional a uma contaminação infinitesimal no ponto <span class="math inline">\(x\)</span>.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Duas noções relacionadas">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Duas noções relacionadas
</div>
</div>
<div class="callout-body-container callout-body">
<p>A função de influência de um <strong>funcional</strong>, definida por derivada de contaminação, e a função de influência de um <strong>estimador regular assintoticamente linear</strong> são conceitos relacionados, mas não idênticos por definição. Sob condições adequadas de diferenciabilidade, a expansão do funcional avaliado na distribuição empírica produz a função de influência assintótica do estimador <em>plug-in</em>. A projeção eficiente abaixo refere-se à segunda noção.</p>
</div>
</div>
</section>
<section id="resultado-de-eficiência-semiparamétrica" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="resultado-de-eficiência-semiparamétrica">Resultado de eficiência semiparamétrica</h3>
<p>Considere um modelo semiparamétrico em <span class="math inline">\(P\)</span> cujo espaço tangente <span class="math inline">\(\dot{\mathcal P}\)</span> seja um subespaço linear fechado de <span class="math inline">\(L_2^0(P)\)</span>. Suponha que exista um estimador regular e assintoticamente linear do parâmetro, com função de influência <span class="math inline">\(\psi\in L_2^0(P)\)</span>. Então a função de influência eficiente é</p>
<p><span class="math display">\[\psi_{\mathrm{ef}}
=
\Pi\bigl(\psi\mid\dot{\mathcal P}\bigr),\]</span></p>
<p>isto é, a projeção ortogonal de <span class="math inline">\(\psi\)</span> sobre o espaço tangente.</p>
</section>
<section id="demonstração-22" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-22">Demonstração</h3>
<p>Pela decomposição ortogonal de Hilbert,</p>
<p><span class="math display">\[\psi
=
\Pi(\psi\mid\dot{\mathcal P})
+
\Pi(\psi\mid\dot{\mathcal P}^{\perp}).\]</span></p>
<p>As equações que caracterizam uma função de influência regular envolvem seus produtos internos com os escores dos submodelos paramétricos regulares. Esses escores pertencem a <span class="math inline">\(\dot{\mathcal P}\)</span>. Para qualquer escore <span class="math inline">\(s\in\dot{\mathcal P}\)</span>,</p>
<p><span class="math display">\[\langle\psi,s\rangle
=
\left\langle
\Pi(\psi\mid\dot{\mathcal P}),s
\right\rangle,\]</span></p>
<p>pois o componente em <span class="math inline">\(\dot{\mathcal P}^{\perp}\)</span> é ortogonal a <span class="math inline">\(s\)</span>. Portanto, a projeção preserva as equações de derivada que definem uma função de influência regular.</p>
<p>Pelo teorema de Pitágoras,</p>
<p><span class="math display">\[\|\psi\|_2^2
=
\|\Pi(\psi\mid\dot{\mathcal P})\|_2^2
+
\|\Pi(\psi\mid\dot{\mathcal P}^{\perp})\|_2^2.\]</span></p>
<p>Consequentemente,</p>
<p><span class="math display">\[E_P(\psi_{\mathrm{ef}}^2)
\leq
E_P(\psi^2).\]</span></p>
<p>Como a variância assintótica de um estimador regular assintoticamente linear é determinada por <span class="math inline">\(E_P(\psi^2)\)</span>, a projeção possui a menor variância entre as funções de influência regulares admissíveis e é eficiente.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Robustez">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Robustez
</div>
</div>
<div class="callout-body-container callout-body">
<p>Eficiência semiparamétrica e robustez local são critérios distintos. Em análise robusta, uma função de influência limitada controla o efeito local de contaminações extremas. A função de influência eficiente no modelo semiparamétrico pode ser não limitada.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="bickel2016volume2">Bickel; Doksum (<a href="#ref-bickel2016volume2" role="doc-biblioref">2016</a>)</span> [Seção 7.2.1, para funções de influência e derivadas funcionais; Seção 9.3 e Proposição 9.3.3, para projeção eficiente].<br>
<strong>Fonte complementar:</strong> <span class="citation" data-cites="wilcox2022">Wilcox (<a href="#ref-wilcox2022" role="doc-biblioref">2022, seç. 2.1–2.2</a>, para a interpretação robusta)</span>.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-25-validade-exata-de-um-teste-de-permutação" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-25-validade-exata-de-um-teste-de-permutação">Demonstração 25 — Validade exata de um teste de permutação</h2>
<section id="enunciado-21" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="enunciado-21">Enunciado</h3>
<p>Suponha que, sob <span class="math inline">\(H_0\)</span>, as observações sejam permutáveis em relação aos rótulos dos grupos. Seja <span class="math inline">\(\mathcal G\)</span> o conjunto finito das permutações admissíveis e <span class="math inline">\(T\)</span> uma estatística em que valores grandes contradizem <span class="math inline">\(H_0\)</span>. Defina</p>
<p><span class="math display">\[p(x)
=
\frac{1}{|\mathcal G|}
\sum_{g\in\mathcal G}
\mathbf 1\{T(gx)\geq T(x)\}.\]</span></p>
<p>Então</p>
<p><span class="math display">\[P_{H_0}\{p(X)\leq\alpha\}
\leq\alpha.\]</span></p>
<p>Se não há empates e os níveis possíveis são compatíveis com <span class="math inline">\(|\mathcal G|\)</span>, a igualdade é exata.</p>
</section>
<section id="demonstração-23" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-23">Demonstração</h3>
<p>Condicione na órbita</p>
<p><span class="math display">\[\mathcal O(x)=\{gx:g\in\mathcal G\}.\]</span></p>
<p>Sob a hipótese nula de permutabilidade, todos os elementos da órbita são equiprováveis. Portanto, a posição de <span class="math inline">\(T(X)\)</span> entre os valores</p>
<p><span class="math display">\[\{T(gx):g\in\mathcal G\}\]</span></p>
<p>é uniforme, na ausência de empates.</p>
<p>Se os valores forem ordenados do maior para o menor, <span class="math inline">\(p(X)\)</span> é a proporção de valores da órbita que são pelo menos tão extremos quanto o valor observado. Assim, a condição <span class="math inline">\(p(X)\leq\alpha\)</span> só pode ocorrer quando <span class="math inline">\(T(X)\)</span> está entre os no máximo <span class="math inline">\(\alpha|\mathcal G|\)</span> valores mais extremos da órbita. Condicionalmente à órbita,</p>
<p><span class="math display">\[P_{H_0}\{p(X)\leq\alpha\mid\mathcal O(X)\}
\leq
\frac{\lfloor\alpha|\mathcal G|\rfloor}{|\mathcal G|}
\leq\alpha.\]</span></p>
<p>Tomando esperança sobre a órbita,</p>
<p><span class="math display">\[P_{H_0}\{p(X)\leq\alpha\}
\leq\alpha.\]</span></p>
<p>Empates tornam o teste conservador quando se usa a desigualdade <span class="math inline">\(\geq\)</span>.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Condição essencial">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Condição essencial
</div>
</div>
<div class="callout-body-container callout-body">
<p>A validade exata exige permutabilidade ou uma atribuição aleatória conhecida. Igualdade de médias, isoladamente, não garante que todos os rearranjos dos dados sejam equiprováveis. Em estudos observacionais, a interpretação causal também não decorre do teste de permutação.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="chihara2022">Chihara; Hesterberg (<a href="#ref-chihara2022" role="doc-biblioref">2022, seç. 3.3</a>, argumento de equiprobabilidade das divisões sob <span class="math inline">\(H_0\)</span>)</span>.<br>
<strong>Adaptação:</strong> a obra apresenta a justificativa por equiprobabilidade; a formulação acima explicita o mesmo argumento em termos de órbitas de um grupo finito.</p>
</div>
</div>
</section>
</section>
<section id="demonstração-26-princípio-plug-in-e-bootstrap-da-média" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="demonstração-26-princípio-plug-in-e-bootstrap-da-média">Demonstração 26 — Princípio <em>plug-in</em> e bootstrap da média</h2>
<section id="definição-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="definição-1">Definição</h3>
<p>Dada uma amostra <span class="math inline">\(X_1,\ldots,X_n\)</span>, a distribuição empírica é</p>
<p><span class="math display">\[\widehat F_n
=
\frac{1}{n}
\sum_{i=1}^n\Delta_{X_i}.\]</span></p>
<p>Uma amostra bootstrap <span class="math inline">\(X_1^*,\ldots,X_n^*\)</span> é obtida condicionalmente aos dados por amostragem i.i.d. de <span class="math inline">\(\widehat F_n\)</span>.</p>
</section>
<section id="demonstração-para-a-média" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="demonstração-para-a-média">Demonstração para a média</h3>
<p>Sob a distribuição empírica,</p>
<p><span class="math display">\[E_*(X_1^*)
=
\frac{1}{n}\sum_{i=1}^nX_i
=
\bar X.\]</span></p>
<p>Logo,</p>
<p><span class="math display">\[E_*(\bar X^*)=\bar X.\]</span></p>
<p>A variância de uma observação bootstrap é</p>
<p><span class="math display">\[\operatorname{Var}_*(X_1^*)
=
\frac{1}{n}
\sum_{i=1}^n(X_i-\bar X)^2.\]</span></p>
<p>Como as observações bootstrap são condicionalmente independentes,</p>
<p><span class="math display">\[\operatorname{Var}_*(\bar X^*)
=
\frac{1}{n}
\operatorname{Var}_*(X_1^*)
=
\frac{1}{n^2}
\sum_{i=1}^n(X_i-\bar X)^2.\]</span></p>
<p>Usando</p>
<p><span class="math display">\[S^2=
\frac{1}{n-1}
\sum_{i=1}^n(X_i-\bar X)^2,\]</span></p>
<p>obtemos</p>
<p><span class="math display">\[\operatorname{Var}_*(\bar X^*)
=
\frac{n-1}{n^2}S^2.\]</span></p>
<p>Portanto, o erro-padrão bootstrap ideal da média é</p>
<p><span class="math display">\[\operatorname{se}_*(\bar X^*)
=
\frac{S}{\sqrt n}
\sqrt{\frac{n-1}{n}},\]</span></p>
<p>que é assintoticamente equivalente ao erro-padrão usual <span class="math inline">\(S/\sqrt n\)</span>.</p>
<p>Esse cálculo ilustra o princípio <em>plug-in</em>: a população desconhecida <span class="math inline">\(F\)</span> é substituída por <span class="math inline">\(\widehat F_n\)</span>, e a distribuição amostral de <span class="math inline">\(\bar X\)</span> sob <span class="math inline">\(F\)</span> é aproximada pela distribuição condicional de <span class="math inline">\(\bar X^*\)</span> sob <span class="math inline">\(\widehat F_n\)</span>.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Limite da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Aviso</span>Limite da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p>O cálculo de média e variância não prova a validade geral do bootstrap para qualquer estatística. Consistência bootstrap depende da regularidade do funcional e pode falhar, por exemplo, em problemas de fronteira, extremos amostrais e funcionais não suaves. Essas extensões precisam de verificação bibliográfica específica.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Fonte da demonstração">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Fonte da demonstração
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fonte principal:</strong> <span class="citation" data-cites="chihara2022">Chihara; Hesterberg (<a href="#ref-chihara2022" role="doc-biblioref">2022, seç. 5.2</a>, princípio <em>plug-in</em> e distribuição empírica)</span>.<br>
<strong>Adaptação:</strong> inclusão da derivação exata dos dois primeiros momentos condicionais da média bootstrap.</p>
</div>
</div>
</section>
</section>
</section>
<section id="síntese-conceitual" class="level1 unnumbered">
<h1 class="unnumbered">Síntese conceitual</h1>
<p>As 26 demonstrações formam uma cadeia lógica:</p>
<ol type="1">
<li>a lei dos grandes números e o TCL justificam a estabilidade e a aproximação normal de estatísticas;</li>
<li>os resultados exatos do modelo normal produzem as distribuições <span class="math inline">\(\chi^2\)</span> e <span class="math inline">\(t\)</span>;</li>
<li>suficiência, Rao–Blackwell, completude e Cramér–Rao organizam a comparação de estimadores;</li>
<li>verossimilhança, método delta, equivalências assintóticas e Wilks estruturam a inferência regular em grandes amostras;</li>
<li>Neyman–Pearson, Karlin–Rubin e a dualidade com regiões de confiança organizam a teoria dos testes;</li>
<li>EM, minimização, funções de influência, permutação e bootstrap ampliam a teoria para métodos computacionais, robustos e semiparamétricos.</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled" title="Observação editorial">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Importante</span>Observação editorial
</div>
</div>
<div class="callout-body-container callout-body">
<p>Para uma versão de graduação avançada, um núcleo possível é formado pelas demonstrações 1–15, 18, 21–22 e 25–26. As demonstrações 16–20 e 23–24 podem ser desenvolvidas em disciplinas de mestrado ou em apêndices, com maior atenção às condições de regularidade, aos espaços tangentes e aos contraexemplos.</p>
</div>
</div>
</section>
<section id="referências" class="level1 unnumbered">
<h1 class="unnumbered">Referências</h1>


<div id="refs" class="references csl-bib-body" data-entry-spacing="1" role="list">
<div id="ref-bickel2016volume2" class="csl-entry" role="listitem">
BICKEL, Peter J.; DOKSUM, Kjell A. <strong>Mathematical Statistics: Basic Ideas and Selected Topics: Volume II</strong>. Boca Raton, FL: CRC Press, 2016. v. 2
</div>
<div id="ref-chihara2022" class="csl-entry" role="listitem">
CHIHARA, Laura M.; HESTERBERG, Tim C. <strong>Mathematical Statistics with Resampling and <span>R</span></strong>. 3. ed. Hoboken, NJ: John Wiley &amp; Sons, 2022.
</div>
<div id="ref-cox2006principles" class="csl-entry" role="listitem">
COX, D. R. <strong>Principles of Statistical Inference</strong>. Cambridge: Cambridge University Press, 2006.
</div>
<div id="ref-gupta2011em" class="csl-entry" role="listitem">
GUPTA, Maya R.; CHEN, Yihua. <a href="https://doi.org/10.1561/2000000034">Theory and Use of the <span>EM</span> Algorithm</a>. <strong>Foundations and Trends in Signal Processing</strong>, v. 4, n. 3, p. 223–296, 2011.
</div>
<div id="ref-hogg1978" class="csl-entry" role="listitem">
HOGG, Robert V.; CRAIG, Allen T. <strong>Introduction to Mathematical Statistics</strong>. 4. ed. New York: Macmillan Publishing Co., 1978.
</div>
<div id="ref-larsen2012" class="csl-entry" role="listitem">
LARSEN, Richard J.; MARX, Morris L. <strong>An Introduction to Mathematical Statistics and Its Applications</strong>. 5. ed. Boston: Prentice Hall, 2012.
</div>
<div id="ref-lauritzen2023fundamentals" class="csl-entry" role="listitem">
LAURITZEN, Steffen. <strong>Fundamentals of Mathematical Statistics</strong>. 1. ed. Boca Raton, FL: CRC Press, 2023.
</div>
<div id="ref-ramachandran2009" class="csl-entry" role="listitem">
RAMACHANDRAN, Kandethody M.; TSOKOS, Chris P. <strong>Mathematical Statistics with Applications</strong>. Burlington, MA: Academic Press, 2009.
</div>
<div id="ref-ramachandran2021r" class="csl-entry" role="listitem">
RAMACHANDRAN, Kandethody M.; TSOKOS, Chris P. <strong>Mathematical Statistics with Applications in <span>R</span></strong>. 3. ed. London: Academic Press, 2021.
</div>
<div id="ref-rasch2018" class="csl-entry" role="listitem">
RASCH, Dieter; SCHOTT, Dieter. <strong>Mathematical Statistics</strong>. Chichester: John Wiley &amp; Sons, 2018.
</div>
<div id="ref-rice2007mathematical" class="csl-entry" role="listitem">
RICE, John A. <strong>Mathematical Statistics and Data Analysis</strong>. 3. ed. Belmont, CA: Duxbury Press, 2007.
</div>
<div id="ref-wilcox2022" class="csl-entry" role="listitem">
WILCOX, Rand R. <strong>Introduction to Robust Estimation and Hypothesis Testing</strong>. 5. ed. London: Academic Press, 2022.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Unidade8.html" class="pagination-link" aria-label="Exemplos Aplicados">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Exemplos Aplicados</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>