<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Estimação Pontual</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./unidade4.html" rel="next">
<link href="./unidade2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./unidade3.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estimação Pontual</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
        <div class="sidebar-tools-collapse">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Informações Legais e Declaração de Uso de Inteligência Artificial</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Identificação da Disciplina</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preliminares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Preliminares</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Fundamentos da Inferência Estatística</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Distribuições Amostrais</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade3.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estimação Pontual</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimação por Intervalos: Intervalo de Confiança</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Testes de Hipóteses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Testes de Homogeneidade e Independência</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unidade7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Inferência Estatística e Ciência de Dados</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referências</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#propriedades-de-estimadores" id="toc-propriedades-de-estimadores" class="nav-link active" data-scroll-target="#propriedades-de-estimadores"><span class="header-section-number">4.1</span> Propriedades de Estimadores</a>
  <ul class="collapse">
  <li><a href="#viés" id="toc-viés" class="nav-link" data-scroll-target="#viés">Viés</a></li>
  <li><a href="#variância-e-erro-quadrático-médio" id="toc-variância-e-erro-quadrático-médio" class="nav-link" data-scroll-target="#variância-e-erro-quadrático-médio">Variância e Erro Quadrático Médio</a></li>
  <li><a href="#consistência" id="toc-consistência" class="nav-link" data-scroll-target="#consistência">Consistência</a></li>
  <li><a href="#eficiência" id="toc-eficiência" class="nav-link" data-scroll-target="#eficiência">Eficiência</a></li>
  <li><a href="#estatística-suficiente" id="toc-estatística-suficiente" class="nav-link" data-scroll-target="#estatística-suficiente">Estatística Suficiente</a></li>
  </ul></li>
  <li><a href="#método-dos-momentos" id="toc-método-dos-momentos" class="nav-link" data-scroll-target="#método-dos-momentos"><span class="header-section-number">4.2</span> Método dos Momentos</a>
  <ul class="collapse">
  <li><a href="#ideia-por-trás-do-método" id="toc-ideia-por-trás-do-método" class="nav-link" data-scroll-target="#ideia-por-trás-do-método"><span class="header-section-number">4.2.1</span> Ideia por trás do método</a></li>
  <li><a href="#procedimento-geral-do-método-dos-momentos" id="toc-procedimento-geral-do-método-dos-momentos" class="nav-link" data-scroll-target="#procedimento-geral-do-método-dos-momentos"><span class="header-section-number">4.2.2</span> Procedimento Geral do Método dos Momentos</a></li>
  <li><a href="#passo-1" id="toc-passo-1" class="nav-link" data-scroll-target="#passo-1">Passo 1</a></li>
  <li><a href="#passo-2" id="toc-passo-2" class="nav-link" data-scroll-target="#passo-2">Passo 2</a></li>
  <li><a href="#passo-3" id="toc-passo-3" class="nav-link" data-scroll-target="#passo-3">Passo 3</a></li>
  <li><a href="#passo-4" id="toc-passo-4" class="nav-link" data-scroll-target="#passo-4">Passo 4</a></li>
  </ul></li>
  <li><a href="#exemplo-distribuição-de-pareto" id="toc-exemplo-distribuição-de-pareto" class="nav-link" data-scroll-target="#exemplo-distribuição-de-pareto">Exemplo: Distribuição de Pareto</a>
  <ul class="collapse">
  <li><a href="#passo-2-1" id="toc-passo-2-1" class="nav-link" data-scroll-target="#passo-2-1">Passo 2</a></li>
  <li><a href="#passos-3-e-4" id="toc-passos-3-e-4" class="nav-link" data-scroll-target="#passos-3-e-4">Passos 3 e 4</a></li>
  <li><a href="#variância-via-método-delta" id="toc-variância-via-método-delta" class="nav-link" data-scroll-target="#variância-via-método-delta">Variância via Método Delta</a></li>
  <li><a href="#exemplo-numérico" id="toc-exemplo-numérico" class="nav-link" data-scroll-target="#exemplo-numérico">Exemplo Numérico</a></li>
  <li><a href="#simulação-em-r" id="toc-simulação-em-r" class="nav-link" data-scroll-target="#simulação-em-r">Simulação em R</a></li>
  </ul></li>
  <li><a href="#exemplo-distribuição-uniforme-contínua" id="toc-exemplo-distribuição-uniforme-contínua" class="nav-link" data-scroll-target="#exemplo-distribuição-uniforme-contínua">Exemplo: Distribuição Uniforme Contínua</a>
  <ul class="collapse">
  <li><a href="#passo-1-1" id="toc-passo-1-1" class="nav-link" data-scroll-target="#passo-1-1">Passo 1</a></li>
  <li><a href="#passo-2-2" id="toc-passo-2-2" class="nav-link" data-scroll-target="#passo-2-2">Passo 2</a></li>
  <li><a href="#passos-3-e-4-1" id="toc-passos-3-e-4-1" class="nav-link" data-scroll-target="#passos-3-e-4-1">Passos 3 e 4</a></li>
  <li><a href="#esperança-e-variância" id="toc-esperança-e-variância" class="nav-link" data-scroll-target="#esperança-e-variância">Esperança e Variância</a></li>
  </ul></li>
  <li><a href="#exemplo-distribuição-uniforme-discreta" id="toc-exemplo-distribuição-uniforme-discreta" class="nav-link" data-scroll-target="#exemplo-distribuição-uniforme-discreta">Exemplo: Distribuição Uniforme Discreta</a>
  <ul class="collapse">
  <li><a href="#passo-1-2" id="toc-passo-1-2" class="nav-link" data-scroll-target="#passo-1-2">Passo 1</a></li>
  <li><a href="#passo-2-3" id="toc-passo-2-3" class="nav-link" data-scroll-target="#passo-2-3">Passo 2</a></li>
  <li><a href="#passos-3-e-4-2" id="toc-passos-3-e-4-2" class="nav-link" data-scroll-target="#passos-3-e-4-2">Passos 3 e 4</a></li>
  <li><a href="#esperança-e-variância-1" id="toc-esperança-e-variância-1" class="nav-link" data-scroll-target="#esperança-e-variância-1">Esperança e Variância</a></li>
  <li><a href="#comparação-com-o-estimador-de-máxima-verossimilhança" id="toc-comparação-com-o-estimador-de-máxima-verossimilhança" class="nav-link" data-scroll-target="#comparação-com-o-estimador-de-máxima-verossimilhança">Comparação com o Estimador de Máxima Verossimilhança</a></li>
  </ul></li>
  <li><a href="#exemplo-distribuição-exponencial" id="toc-exemplo-distribuição-exponencial" class="nav-link" data-scroll-target="#exemplo-distribuição-exponencial">Exemplo: Distribuição Exponencial</a>
  <ul class="collapse">
  <li><a href="#passo-1-3" id="toc-passo-1-3" class="nav-link" data-scroll-target="#passo-1-3">Passo 1</a></li>
  <li><a href="#passo-2-4" id="toc-passo-2-4" class="nav-link" data-scroll-target="#passo-2-4">Passo 2</a></li>
  <li><a href="#passos-3-e-4-3" id="toc-passos-3-e-4-3" class="nav-link" data-scroll-target="#passos-3-e-4-3">Passos 3 e 4</a></li>
  <li><a href="#esperança-e-variância-2" id="toc-esperança-e-variância-2" class="nav-link" data-scroll-target="#esperança-e-variância-2">Esperança e Variância</a></li>
  </ul></li>
  <li><a href="#exemplo-distribuição-gama" id="toc-exemplo-distribuição-gama" class="nav-link" data-scroll-target="#exemplo-distribuição-gama">Exemplo: Distribuição Gama</a>
  <ul class="collapse">
  <li><a href="#passo-1-4" id="toc-passo-1-4" class="nav-link" data-scroll-target="#passo-1-4">Passo 1</a></li>
  <li><a href="#passo-2-5" id="toc-passo-2-5" class="nav-link" data-scroll-target="#passo-2-5">Passo 2</a></li>
  <li><a href="#passos-3-e-4-4" id="toc-passos-3-e-4-4" class="nav-link" data-scroll-target="#passos-3-e-4-4">Passos 3 e 4</a></li>
  </ul></li>
  <li><a href="#método-de-máxima-verossimilhança" id="toc-método-de-máxima-verossimilhança" class="nav-link" data-scroll-target="#método-de-máxima-verossimilhança"><span class="header-section-number">4.3</span> Método de Máxima Verossimilhança</a></li>
  <li><a href="#exemplo-emv-poisson" id="toc-exemplo-emv-poisson" class="nav-link" data-scroll-target="#exemplo-emv-poisson">Exemplo EMV (Poisson)</a>
  <ul class="collapse">
  <li><a href="#passo-1-calcule-a-verossimilhança-e-a-log-verossimilhança-dos-dados" id="toc-passo-1-calcule-a-verossimilhança-e-a-log-verossimilhança-dos-dados" class="nav-link" data-scroll-target="#passo-1-calcule-a-verossimilhança-e-a-log-verossimilhança-dos-dados">Passo 1: Calcule a verossimilhança e a log-verossimilhança dos dados</a></li>
  <li><a href="#passo-2-calcule-as-derivadas-parcialis-em-relação-a-theta-e-iguale-a-zero.-resolva-as-equaçãoões" id="toc-passo-2-calcule-as-derivadas-parcialis-em-relação-a-theta-e-iguale-a-zero.-resolva-as-equaçãoões" class="nav-link" data-scroll-target="#passo-2-calcule-as-derivadas-parcialis-em-relação-a-theta-e-iguale-a-zero.-resolva-as-equaçãoões">Passo 2: Calcule a(s) derivada(s) parcial(is) em relação a <span class="math inline">\(\theta\)</span> e iguale a zero. Resolva a(s) equação(ões)</a></li>
  <li><a href="#passo-3-opcionalmente-verifique-se-hattheta-é-de-fato-um-máximo-local-checando-se-a-segunda-derivada-em-hattheta-é-negativa-quando-theta-é-um-único-parâmetro-ou-se-a-hessiana-matriz-das-segundas-derivadas-parciais-é-negativa-semidefinida-quando-theta-é-um-vetor-de-parâmetros" id="toc-passo-3-opcionalmente-verifique-se-hattheta-é-de-fato-um-máximo-local-checando-se-a-segunda-derivada-em-hattheta-é-negativa-quando-theta-é-um-único-parâmetro-ou-se-a-hessiana-matriz-das-segundas-derivadas-parciais-é-negativa-semidefinida-quando-theta-é-um-vetor-de-parâmetros" class="nav-link" data-scroll-target="#passo-3-opcionalmente-verifique-se-hattheta-é-de-fato-um-máximo-local-checando-se-a-segunda-derivada-em-hattheta-é-negativa-quando-theta-é-um-único-parâmetro-ou-se-a-hessiana-matriz-das-segundas-derivadas-parciais-é-negativa-semidefinida-quando-theta-é-um-vetor-de-parâmetros">Passo 3: Opcionalmente, verifique se <span class="math inline">\(\hat{\theta}\)</span> é de fato um máximo (local), checando se a segunda derivada em <span class="math inline">\(\hat{\theta}\)</span> é negativa (quando <span class="math inline">\(\theta\)</span> é um único parâmetro), ou se a Hessiana (matriz das segundas derivadas parciais) é negativa semidefinida (quando <span class="math inline">\(\theta\)</span> é um vetor de parâmetros)</a></li>
  </ul></li>
  <li><a href="#exemplo-emv-exponencial" id="toc-exemplo-emv-exponencial" class="nav-link" data-scroll-target="#exemplo-emv-exponencial">Exemplo EMV (Exponencial)</a></li>
  <li><a href="#exemplo-emv-uniforme-discreta" id="toc-exemplo-emv-uniforme-discreta" class="nav-link" data-scroll-target="#exemplo-emv-uniforme-discreta">Exemplo EMV (Uniforme Discreta)</a></li>
  <li><a href="#exemplo-emv-uniforme-continua" id="toc-exemplo-emv-uniforme-continua" class="nav-link" data-scroll-target="#exemplo-emv-uniforme-continua">Exemplo EMV (Uniforme Continua)</a></li>
  <li><a href="#exemplo-emv-normal-inversa" id="toc-exemplo-emv-normal-inversa" class="nav-link" data-scroll-target="#exemplo-emv-normal-inversa">Exemplo EMV (Normal Inversa)</a></li>
  <li><a href="#exemplo-emv-birnbaum-saunders" id="toc-exemplo-emv-birnbaum-saunders" class="nav-link" data-scroll-target="#exemplo-emv-birnbaum-saunders">Exemplo EMV (Birnbaum-Saunders)</a></li>
  <li><a href="#exemplo-emv-normal" id="toc-exemplo-emv-normal" class="nav-link" data-scroll-target="#exemplo-emv-normal">Exemplo EMV (Normal)</a></li>
  <li><a href="#método-de-mínimos-quadrados" id="toc-método-de-mínimos-quadrados" class="nav-link" data-scroll-target="#método-de-mínimos-quadrados"><span class="header-section-number">4.4</span> Método de Mínimos Quadrados</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estimação Pontual</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="propriedades-de-estimadores" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="propriedades-de-estimadores"><span class="header-section-number">4.1</span> Propriedades de Estimadores</h2>
<p>Ao obter um estimador para um parâmetro desconhecido, é fundamental avaliar sua qualidade. Para isso, utilizamos algumas propriedades que permitem comparar estimadores e analisar seu comportamento, tanto em amostras finitas quanto assintoticamente. Seja <span class="math inline">\(\hat{\theta}\)</span> um estimador para o parâmetro <span class="math inline">\(\theta\)</span>.</p>
<section id="viés" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="viés">Viés</h3>
<p>A primeira propriedade de estimadores que abordaremos é o viés. O viés de um estimador mede se, em termos de valor esperado, o estimador é igual ao verdadeiro parâmetro.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Definição">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definição
</div>
</div>
<div class="callout-body-container callout-body">
<p>Seja <span class="math inline">\(\hat{\theta}\)</span> um estimador para <span class="math inline">\(\theta\)</span>. O viés de <span class="math inline">\(\hat{\theta}\)</span> como estimador para <span class="math inline">\(\theta\)</span> é</p>
<p><span class="math display">\[B(\hat{\theta}, \theta) = E(\hat{\theta}) - \theta.\]</span></p>
<p>Se</p>
<ul>
<li><p><span class="math inline">\(B(\hat{\theta}, \theta) = 0\)</span>, ou equivalentemente <span class="math inline">\(E(\hat{\theta}) = \theta\)</span>, então dizemos que <span class="math inline">\(\hat{\theta}\)</span> é um estimador não viesado de <span class="math inline">\(\theta\)</span>;</p></li>
<li><p><span class="math inline">\(B(\hat{\theta}, \theta) &gt; 0\)</span>, então <span class="math inline">\(\hat{\theta}\)</span> superestima <span class="math inline">\(\theta\)</span>;</p></li>
<li><p><span class="math inline">\(B(\hat{\theta}, \theta) &lt; 0\)</span>, então <span class="math inline">\(\hat{\theta}\)</span> subestima <span class="math inline">\(\theta\)</span>.</p></li>
</ul>
</div>
</div>
<blockquote class="blockquote">
<p>Um estimador não viesado, em média, acerta o valor do parâmetro.</p>
</blockquote>
</section>
<section id="variância-e-erro-quadrático-médio" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="variância-e-erro-quadrático-médio">Variância e Erro Quadrático Médio</h3>
<p>Frequentemente, também estamos interessados em quanto um estimador varia (gostaríamos que ele fosse não viesado e tivesse pequena variância, para que seja mais preciso). Uma medida que captura essa propriedade dos estimadores é a variância do estimador.</p>
<p>A variância de um estimador <span class="math inline">\(\hat{\theta}\)</span> é dada por:</p>
<p><span class="math display">\[Var(\hat{\theta}) = E\left(\left[\hat{\theta} - E(\hat{\theta})\right]^2\right).\]</span></p>
<p>Essa é simplesmente a definição usual de variância aplicada à variável aleatória <span class="math inline">\(\hat{\theta}\)</span>, não sendo uma nova definição.</p>
<p>No entanto, em vez de considerar apenas a variância, podemos querer uma medida que avalie diretamente o erro em relação ao verdadeiro parâmetro <span class="math inline">\(\theta\)</span>. Nesse caso, consideramos:</p>
<p><span class="math display">\[E\left[(\hat{\theta} - \theta)^2\right].\]</span></p>
<p>Essa quantidade é chamada de erro quadrático médio (EQM) e está relacionada tanto ao viés quanto à variância.</p>
<p>Observe que, se <span class="math inline">\(\hat{\theta}\)</span> for não viesado, então <span class="math inline">\(E(\hat{\theta}) = \theta\)</span>, e, nesse caso, o EQM coincide com a variância.</p>
<div class="callout callout-style-default callout-caution callout-titled" title="Definição">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definição
</div>
</div>
<div class="callout-body-container callout-body">
<p>O EQM de um estimador <span class="math inline">\(\hat{\theta}\)</span> de <span class="math inline">\(\theta\)</span> é</p>
<p><span class="math display">\[EQM(\hat{\theta}, \theta) = E\left[(\hat{\theta} - \theta)^2\right].\]</span></p>
<p>Se <span class="math inline">\(\hat{\theta}\)</span> é um estimador não viesado de <span class="math inline">\(\theta\)</span> (i.e <span class="math inline">\(E(\hat{\theta}) = \theta\)</span>), então podemos notar que <span class="math inline">\(EQM(\hat{\theta}, \theta) = Var(\hat{\theta})\)</span>. De fato, em geral <span class="math inline">\(EQM(\hat{\theta}, \theta) = Var(\hat{\theta}) + B(\hat{\theta}, \theta)^2\)</span>.</p>
</div>
</div>
<p>Isso leva ao que é conhecido como o “trade-off viés-variância” em aprendizado de máquina e estatística. Em geral, queremos minimizar o EQM, e essas duas quantidades costumam ser inversamente relacionadas. Ou seja, diminuir uma tende a aumentar a outra, e encontrar o equilíbrio entre elas é o que minimiza o EQM.</p>
<p>Pode ser difícil perceber por que isso acontece neste momento, já que ainda não estamos trabalhando com estimadores tão complexos (estamos apenas vendo os conceitos básicos!).</p>
</section>
<section id="consistência" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="consistência">Consistência</h3>
<div class="callout callout-style-default callout-tip callout-titled" title="Definição">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definição
</div>
</div>
<div class="callout-body-container callout-body">
<p>Um estimador <span class="math inline">\(\hat{\theta}_n\)</span> (dependendo de <span class="math inline">\(n\)</span> amostras iid) de <span class="math inline">\(\theta\)</span> é dito (fracamente) <strong>consistente</strong> se este converge (em probabilidade) para <span class="math inline">\(\theta\)</span>. Isto é, para qualquer <span class="math inline">\(\epsilon &gt; 0\)</span>,</p>
<p><span class="math display">\[\lim_{n \to \infty} P\left(|\hat{\theta}_n - \theta| \geq \epsilon\right) = 0,\]</span> ou equivalentemente,</p>
<p><span class="math display">\[\lim_{n \to \infty} P\left(|\hat{\theta}_n - \theta| &lt; \epsilon\right) = 1.\]</span></p>
<p>Basicamente, quando <span class="math inline">\(n \to \infty\)</span>, a probabilidade de <span class="math inline">\(\hat{\theta}_n\)</span> diferir de <span class="math inline">\(\theta\)</span> por mais de <span class="math inline">\(\epsilon\)</span> unidades é arbritariamente pequena. A definição é um pouco abstrata, então analisamos o que ela significa no contexto de um exemplo. Lançamos uma moeda <span class="math inline">\(n\)</span> vezes e seja <span class="math inline">\(\hat{p}_n\)</span> a proporção de caras obtidas, isto é, o número de caras dividido por <span class="math inline">\(n\)</span>. Essa é uma proporção amostral que estima <span class="math inline">\(p\)</span>, a probabilidade de a moeda resultar em cara. Suponha que <span class="math inline">\(p = \frac{1}{2}\)</span>. Se <span class="math inline">\(\hat{p}_n\)</span> converge em probabilidade para <span class="math inline">\(\frac{1}{2}\)</span>, então: i) <span class="math inline">\(P(0{,}49 \leq \hat{p}_n \leq 0{,}51) \to 1\)</span> quando <span class="math inline">\(n \to \infty\)</span>; ii) <span class="math inline">\(P(0{,}499 \leq \hat{p}_n \leq 0{,}501) \to 1\)</span> quando <span class="math inline">\(n \to \infty\)</span>; e assim por diante.</p>
<p>Dizemos que é consistente em erro quadrático médio (se um estimador é consistente em erro quadrático médio, então ele é fracamente consistente) se</p>
<p><span class="math display">\[\lim_{n \to \infty} EQM(\hat{\theta}, \theta) = 0.\]</span></p>
<p>Ambas essas noções referem-se ao comportamento assintótico de <span class="math inline">\(\hat{\theta}\)</span> e expressam que, à medida que os dados se acumulam, <span class="math inline">\(\hat{\theta}\)</span> se aproxima cada vez mais do verdadeiro valor de <span class="math inline">\(\theta\)</span>.</p>
<p>A consistência assintótica é uma propriedade desejável. No entanto, em um caso específico, para <span class="math inline">\(n\)</span> fixo, ela pode ter relevância limitada.</p>
</div>
</div>
<p>Você pode estar se perguntando: qual é a diferença entre consistência e não-viés? De fato, existe uma diferença sutil, que podemos entender comparando estimadores para <span class="math inline">\(\theta\)</span> na distribuição contínua <span class="math inline">\(\text{Unif}(0, \theta)\)</span>.</p>
<ol type="1">
<li><p><strong>Estimador não viesado e consistente (MoM)</strong></p>
<p>Um exemplo é o estimador de momentos: <span class="math display">\[
\hat{\theta}_{n,\text{MoM}} = 2\bar{X}.
\]</span> Ele é não viesado, isto é, <span class="math display">\[
E[\hat{\theta}_{n,\text{MoM}}] = \theta,
\]</span> e também consistente, pois sua variância tende a zero quando <span class="math inline">\(n \to \infty\)</span>.</p></li>
<li><p><strong>Não viesado, mas não consistente</strong></p>
<p>Considere o estimador que utiliza apenas a primeira observação: <span class="math display">\[
\hat{\theta} = 2X_1.
\]</span> Ele é não viesado, pois <span class="math display">\[
E[\hat{\theta}] = \theta.
\]</span> No entanto, não é consistente, já que não melhora com o aumento de <span class="math inline">\(n\)</span>, pois ignora as demais observações. A consistência exige que o estimador se aproxime de <span class="math inline">\(\theta\)</span> à medida que <span class="math inline">\(n\)</span> cresce.</p></li>
<li><p><strong>Viesado, mas consistente (EMV)</strong></p>
<p>O estimador de máxima verossimilhança é: <span class="math display">\[
\hat{\theta}_{n,\text{EMV}} = \max(X_1, \dots, X_n).
\]</span> Sua esperança é dada por: <span class="math display">\[
E[\hat{\theta}_{n,\text{EMV}}] = \frac{n}{n+1}\theta,
\]</span> o que mostra que ele é viesado. No entanto, <span class="math display">\[
\frac{n}{n+1}\theta \to \theta \quad \text{quando } n \to \infty,
\]</span> ou seja, ele é assintoticamente não viesado e consistente.</p></li>
<li><p><strong>Nem não viesado nem consistente</strong></p>
<p>Um exemplo simples seria: <span class="math display">\[
\hat{\theta} = \frac{1}{2}X_1,
\]</span> que não é nem não viesado nem consistente.</p></li>
</ol>
<div class="callout callout-style-default callout-caution callout-titled" title="Teorema">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Teorema
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Se <span class="math inline">\(\hat{\theta}_n\)</span> é um estimador não viesado para <span class="math inline">\(\theta\)</span> e <span class="math inline">\(\sigma^2_{\hat{\theta}_n} \to 0\)</span> quando <span class="math inline">\(n \to \infty\)</span>, então <span class="math inline">\(\hat{\theta}_n\)</span> é consistente.</p></li>
<li><p>Suponha que o estimador <span class="math inline">\(\hat{\theta}_n\)</span> converge em probabilidade para <span class="math inline">\(\theta\)</span> e o estimador <span class="math inline">\(\hat{\beta}_n\)</span> converge em probabilidade para o parâmetro <span class="math inline">\(\beta\)</span>. Então:</p></li>
</ol>
<ul>
<li><span class="math inline">\(\hat{\theta}_n + \hat{\beta}_n\)</span> converge em probabilidade para <span class="math inline">\(\theta + \beta\)</span>;</li>
<li><span class="math inline">\(\hat{\theta}_n \times \hat{\beta}_n\)</span> converge em probabilidade para <span class="math inline">\(\theta \times \beta\)</span>;</li>
<li>Se <span class="math inline">\(\beta \neq 0\)</span>, <span class="math inline">\(\hat{\theta}_n/\hat{\beta}_n\)</span> converge em probabilidade para <span class="math inline">\(\theta/\beta\)</span>;</li>
<li>Se <span class="math inline">\(g(x)\)</span> é uma função contínua, então <span class="math inline">\(g(\hat{\theta}_n)\)</span> converge em probabilidade para <span class="math inline">\(g(\theta)\)</span>.</li>
</ul>
</div>
</div>
</section>
<section id="eficiência" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="eficiência">Eficiência</h3>
<p>Para tratar do nosso último tópico, <strong>eficiência</strong>, precisamos primeiro definir a <strong>Informação de Fisher</strong>.</p>
<p>A eficiência está relacionada à ideia de que nosso estimador possui a menor variância possível. Quando essa propriedade é combinada com consistência e não-viés, temos um estimador que:</p>
<ul>
<li>está centrado no valor correto (<em>não viesado</em>);</li>
<li>converge para o verdadeiro parâmetro (<em>consistente</em>);</li>
<li>e faz isso da maneira mais rápida possível (<em>eficiente</em>).</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled" title="Informação de Fisher">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Informação de Fisher
</div>
</div>
<div class="callout-body-container callout-body">
<p>Seja <span class="math inline">\(\mathbf{x} = (x_1, \dots, x_n)\)</span> uma amostra iid proveniente de uma distribuição discreta com função de massa de probabilidade <span class="math inline">\(p_X(t \mid \theta)\)</span>, ou de uma distribuição contínua com função densidade <span class="math inline">\(f_X(t \mid \theta)\)</span>, em que <span class="math inline">\(\theta\)</span> é um parâmetro (ou vetor de parâmetros).</p>
<p>A <strong>Informação de Fisher</strong> do parâmetro <span class="math inline">\(\theta\)</span> é definida por: <span class="math display">\[
I(\theta) = n \cdot E\left[\left(\frac{\partial}{\partial \theta} \ln L(\mathbf{x} \mid \theta)\right)^2\right]
= -E\left[\frac{\partial^2}{\partial \theta^2} \ln L(\mathbf{x} \mid \theta)\right],
\]</span> em que <span class="math inline">\(L(\mathbf{x} \mid \theta)\)</span> denota a função de verossimilhança dos dados dado o parâmetro <span class="math inline">\(\theta\)</span> (definida na Seção 4.3).</p>
<p>De acordo com a literatura, a Informação de Fisher “é uma forma de medir a quantidade de informação que uma variável aleatória observável carrega sobre um parâmetro desconhecido <span class="math inline">\(\theta\)</span> do qual depende a distribuição de probabilidade”.</p>
</div>
</div>
<p>A definição apresentada pode parecer bastante complicada à primeira vista, mas, se você analisá-la com calma, verá que não é tão difícil de trabalhar. De fato, ao verificar se o estimador de máxima verossimilhança é um ponto de máximo, já calculamos a segunda derivada da log-verossimilhança. Portanto, para obter a Informação de Fisher, basta dar um passo adicional: calcular a esperança dessa quantidade. No entanto, interpretar diretamente o valor esperado negativo da segunda derivada da log-verossimilhança não é nada intuitivo; trata-se de uma expressão pouco amigável e difícil de visualizar.</p>
<section id="limite-inferior-de-cramér-rao-crlb-e-eficiência" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="limite-inferior-de-cramér-rao-crlb-e-eficiência">Limite Inferior de Cramér-Rao (CRLB) e Eficiência</h4>
<p>Por que definimos essa “complicada” Informação de Fisher? (Na verdade, a situação fica ainda mais complexa quando <span class="math inline">\(\theta\)</span> é um vetor, pois a segunda derivada se torna uma matriz de derivadas parciais de segunda ordem.)</p>
<p>Seria ideal que o erro quadrático médio de um estimador <span class="math inline">\(\hat{\theta}\)</span> fosse o menor possível. O <strong>Limite Inferior de Cramér-Rao (LICR)</strong> fornece justamente um limite inferior para a variância de qualquer estimador não viesado de <span class="math inline">\(\theta\)</span>. Ou seja, se <span class="math inline">\(\hat{\theta}\)</span> é um estimador não viesado de <span class="math inline">\(\theta\)</span>, então existe uma variância mínima possível (lembrando que, para estimadores não viesados, variância = EQM). Se um estimador atinge essa menor variância possível, dizemos que ele é <strong>eficiente</strong>; uma propriedade altamente desejável em inferência estatística. Esse limite mínimo é conhecido como <strong>Limite Inferior de Cramér-Rao</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Limite Inferior de Cramér-Rao">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Limite Inferior de Cramér-Rao
</div>
</div>
<div class="callout-body-container callout-body">
<p>Seja <span class="math inline">\(\mathbf{x} = (x_1, \dots, x_n)\)</span> uma amostra iid proveniente de uma distribuição discreta com função de massa de probabilidade <span class="math inline">\(p_X(t \mid \theta)\)</span>, ou de uma distribuição contínua com função densidade <span class="math inline">\(f_X(t \mid \theta)\)</span>, em que <span class="math inline">\(\theta\)</span> é um parâmetro (ou vetor de parâmetros).</p>
<p>Se <span class="math inline">\(\hat{\theta}\)</span> é um estimador não viesado de <span class="math inline">\(\theta\)</span>, então: <span class="math display">\[
\text{MSE}(\hat{\theta}, \theta) = \text{Var}(\hat{\theta}) \geq \frac{1}{I(\theta)},
\]</span> em que <span class="math inline">\(I(\theta)\)</span> é a Informação de Fisher definida anteriormente.</p>
<p>O que esse resultado nos diz é que, para qualquer estimador não viesado <span class="math inline">\(\hat{\theta}\)</span> de <span class="math inline">\(\theta\)</span>, a variância (que, nesse caso, coincide com o EQM) é, no mínimo, <span class="math inline">\(\frac{1}{I(\theta)}\)</span>.</p>
<p>Se atingimos esse limite inferior, isto é, se: <span class="math display">\[
\text{Var}(\hat{\theta}) = \frac{1}{I(\theta)},
\]</span> então temos a menor variância possível para o estimador. Nesse caso, dizemos que <span class="math inline">\(\hat{\theta}\)</span> é um <strong>estimador não viesado de variância uniformemente mínima (ENVVUM)</strong> para <span class="math inline">\(\theta\)</span>.</p>
</div>
</div>
<p>Como queremos encontrar a menor variância possível, podemos analisar esse problema sob a perspectiva da <strong>eficiência do estimador</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Eficiência">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Eficiência
</div>
</div>
<div class="callout-body-container callout-body">
<p>Seja <span class="math inline">\(\hat{\theta}\)</span> um estimador não viesado de <span class="math inline">\(\theta\)</span>. A eficiência de <span class="math inline">\(\hat{\theta}\)</span> é definida por: <span class="math display">\[
e(\hat{\theta}, \theta) = \frac{I(\theta)^{-1}}{\text{Var}(\hat{\theta})} \leq 1.
\]</span></p>
<p>Esse valor estará sempre entre 0 e 1, pois, se a variância do estimador for igual ao LICR, então a eficiência será igual a 1. Caso a variância seja maior, a eficiência será menor que 1.</p>
<p>Assim, quanto maior a variância, menor a eficiência; e desejamos que a eficiência seja a maior possível (isto é, igual a 1).</p>
<p>Um estimador não viesado é dito <strong>eficiente</strong> se atinge o LICR, ou seja, quando: <span class="math display">\[
e(\hat{\theta}, \theta) = 1.
\]</span> Nesse caso, ele possui a menor variância possível entre todos os estimadores não viesados.</p>
<p>Vale ressaltar que o LICR não é, em geral, garantido para estimadores viesados.</p>
</div>
</div>
</section>
</section>
<section id="estatística-suficiente" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="estatística-suficiente">Estatística Suficiente</h3>
<p>Suponha que temos uma amostra iid <span class="math inline">\(\mathbf{x} = (x_1, \dots, x_n)\)</span> proveniente de uma distribuição conhecida com parâmetro desconhecido <span class="math inline">\(\theta\)</span>. Imagine que temos duas pessoas:</p>
<ul>
<li><p><strong>Estatístico A</strong>: conhece toda a amostra, ou seja, dispõe de <span class="math inline">\(n\)</span> observações: <span class="math inline">\(\mathbf{x} = (x_1, \dots, x_n)\)</span>.</p></li>
<li><p><strong>Estatístico B</strong>: conhece apenas <span class="math inline">\(T(x_1, \dots, x_n) = t\)</span>, um único número que é função da amostra (por exemplo, a soma ou o máximo das observações).</p></li>
</ul>
<p>Heuristicamente, <span class="math inline">\(T(x_1, \dots, x_n)\)</span> é uma <strong>estatística suficiente</strong> se o Estatístico B consegue fazer um trabalho tão bom quanto o Estatístico A, mesmo tendo “menos informação”. Por exemplo, se as observações seguem uma distribuição Bernoulli, conhecer <span class="math display">\[
T(x_1, \dots, x_n) = \sum_{i=1}^n x_i,
\]</span> (o número de sucessos) é tão informativo quanto conhecer todos os resultados individuais. Isso ocorre porque uma boa estimativa seria a proporção de sucessos, isto é, o número de sucessos dividido pelo número total de ensaios.</p>
<p>Assim, não nos importa a <strong>ordem</strong> dos resultados, mas apenas quantos sucessos ocorreram. A palavra “suficiente” sugere exatamente isso: uma quantidade de informação que é “suficiente” para inferência sobre o parâmetro.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Estatística Suficiente">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Estatística Suficiente
</div>
</div>
<div class="callout-body-container callout-body">
<p>Uma estatística <span class="math inline">\(T = T(X_1, \dots, X_n)\)</span> é dita <strong>suficiente</strong> para o parâmetro <span class="math inline">\(\theta\)</span> se a distribuição condicional de <span class="math inline">\(X_1, \dots, X_n\)</span>, dado <span class="math inline">\(T = t\)</span> e <span class="math inline">\(\theta\)</span>, não depende de <span class="math inline">\(\theta\)</span>. Isto é, <span class="math display">\[
P(X_1 = x_1, \dots, X_n = x_n \mid T = t, \theta)
=
P(X_1 = x_1, \dots, X_n = x_n \mid T = t).
\]</span></p>
<p>No caso em que <span class="math inline">\(X_1, \dots, X_n\)</span> são variáveis contínuas, substituímos a probabilidade por uma função densidade.</p>
</div>
</div>
<p>Para motivar a definição, retornamos ao exemplo anterior. Novamente, o Estatístico A possui toda a amostra <span class="math inline">\(x_1, \dots, x_n\)</span>, enquanto o Estatístico B conhece apenas o número <span class="math inline">\(t = T(x_1, \dots, x_n)\)</span>. A ideia é que o Estatístico B conhece apenas <span class="math inline">\(T = t\)</span>, mas, como <span class="math inline">\(T\)</span> é suficiente, ele não precisa conhecer <span class="math inline">\(\theta\)</span> para gerar novas amostras <span class="math inline">\(X_1', \dots, X_n'\)</span> da distribuição.</p>
<p>Isso ocorre porque: <span class="math display">\[
P(X_1 = x_1, \dots, X_n = x_n \mid T = t, \theta) =
P(X_1 = x_1, \dots, X_n = x_n \mid T = t),\]</span> ou seja, a distribuição condicional não depende de <span class="math inline">\(\theta\)</span>. Como o Estatístico B conhece <span class="math inline">\(T = t\)</span>, ele conhece essa distribuição condicional e pode gerar novas amostras.</p>
<p>Assim, o Estatístico B passa a ter <span class="math inline">\(n\)</span> observações iid <span class="math inline">\(X_1', \dots, X_n'\)</span> provenientes da mesma estrutura probabilística. Com essas novas observações, ele pode realizar inferência tão bem quanto o Estatístico A, que possui os dados originais <span class="math inline">\(X_1, \dots, X_n\)</span> (em média). Portanto, nenhum dos dois está em desvantagem. :)</p>
<p>Embora essa definição seja difícil de verificar diretamente, existe um critério que facilita a identificação de estatísticas suficientes:</p>
<div class="callout callout-style-default callout-important callout-titled" title="Critério da Fatoração de Neyman-Fisher">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Critério da Fatoração de Neyman-Fisher
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sejam <span class="math inline">\(x_1, \dots, x_n\)</span> uma amostra iid com função de verossimilhança <span class="math inline">\(L(x_1, \dots, x_n \mid \theta)\)</span>. Uma estatística <span class="math inline">\(T = T(x_1, \dots, x_n)\)</span> é suficiente para <span class="math inline">\(\theta\)</span> se, e somente se, existirem funções não negativas <span class="math inline">\(g\)</span> e <span class="math inline">\(h\)</span> tais que: <span class="math display">\[
L(x_1, \dots, x_n \mid \theta)
=
g(x_1, \dots, x_n)\cdot h\big(T(x_1, \dots, x_n), \theta\big).
\]</span></p>
<p>Ou seja, a verossimilhança dos dados pode ser fatorada como o produto de dois termos:</p>
<ul>
<li>o primeiro termo <span class="math inline">\(g\)</span> pode depender de todos os dados, mas <strong>não depende de</strong> <span class="math inline">\(\theta\)</span>;</li>
<li>o segundo termo <span class="math inline">\(h\)</span> pode depender de <span class="math inline">\(\theta\)</span>, mas depende dos dados <strong>apenas por meio da estatística suficiente</strong> <span class="math inline">\(T\)</span>.</li>
</ul>
<p>Em outras palavras, <span class="math inline">\(T\)</span> é o único elemento que permite a interação entre os dados <span class="math inline">\(x_1, \dots, x_n\)</span> e o parâmetro <span class="math inline">\(\theta\)</span>. Assim, não precisamos acessar diretamente as <span class="math inline">\(n\)</span> observações individuais, basta conhecer o valor de <span class="math inline">\(T\)</span>.</p>
</div>
</div>
<blockquote class="blockquote">
<p>Essas propriedades serão fundamentais para comparar métodos de estimação, como o método dos momentos e a máxima verossimilhança, discutidos ao longo deste capítulo.</p>
</blockquote>
</section>
</section>
<section id="método-dos-momentos" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="método-dos-momentos"><span class="header-section-number">4.2</span> Método dos Momentos</h2>
<p>A estimação por máxima verossimilhança (MV), como veremos nesse capítulo, possui uma intuição bastante elegante, mas pode ser matematicamente trabalhosa de resolver. Vamos aprender inicialmente uma técnica para estimar parâmetros, chamada método dos momentos (MoM).</p>
<p>As definições iniciais e a estratégia podem parecer confusas à primeira vista, mas apresentaremos vários exemplos que devem ajudar a tornar tudo mais claro.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Momentos (Revisão)">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Momentos (Revisão)
</div>
</div>
<div class="callout-body-container callout-body">
<p>Seja <span class="math inline">\(X\)</span> uma variável aleatória e <span class="math inline">\(c \in \mathbb{R}\)</span> um escalar. Então, o <span class="math inline">\(k\)</span>-ésimo momento de <span class="math inline">\(X\)</span> é:</p>
<p><span class="math display">\[
E[X^k],
\]</span> e o <span class="math inline">\(k\)</span>-ésimo momento de <span class="math inline">\(X\)</span> em torno de <span class="math inline">\(c\)</span> é:</p>
<p><span class="math display">\[
E[(X - c)^k].
\]</span> Em geral, temos interesse especial no <strong>primeiro momento</strong> (média) de <span class="math inline">\(X\)</span>: <span class="math inline">\(\mu = E[X]\)</span>, e no <strong>segundo momento em torno da média</strong> (variância): <span class="math inline">\(\text{Var}(X) = E[(X - \mu)^2]\)</span>.</p>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled" title="Momentos Amostrais">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Momentos Amostrais
</div>
</div>
<div class="callout-body-container callout-body">
<p>Seja <span class="math inline">\(X\)</span> uma variável aleatória e <span class="math inline">\(x_1, \ldots, x_n\)</span> uma amostra i.i.d. de <span class="math inline">\(X\)</span>. O <span class="math inline">\(k\)</span>-ésimo momento amostral é: <span class="math display">\[
\frac{1}{n} \sum_{i=1}^{n} x_i^k.
\]</span> O <span class="math inline">\(k\)</span>-ésimo momento amostral em torno de <span class="math inline">\(c\)</span> é: <span class="math display">\[
\frac{1}{n} \sum_{i=1}^{n} (x_i - c)^k.
\]</span></p>
<p>Casos particulares importantes:</p>
<ul>
<li>O primeiro momento amostral é a <strong>média amostral</strong>;</li>
<li>O segundo momento amostral em torno da média é a <strong>variância amostral</strong>.</li>
</ul>
</div>
</div>
<section id="ideia-por-trás-do-método" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="ideia-por-trás-do-método"><span class="header-section-number">4.2.1</span> Ideia por trás do método</h3>
<p>A estimação pelo método dos momentos baseia-se exclusivamente na <strong>Lei dos Grandes Números</strong>, que relembramos a seguir:</p>
<p>Sejam <span class="math inline">\(Y_1, Y_2, \ldots\)</span> variáveis aleatórias independentes com uma distribuição comum que possui média <span class="math inline">\(\mu_{Y}\)</span>. Então, as médias amostrais convergem para a média da distribuição à medida que o número de observações aumenta:</p>
<p><span class="math display">\[
\bar{Y}_{n} = \frac{1}{n} \sum_{i=1}^{n} Y_i \to \mu_{Y} \quad \text{quando } n \to \infty.
\]</span></p>
<p>Para mostrar como o método dos momentos determina um estimador, consideramos inicialmente o caso de <strong>um único parâmetro</strong>.</p>
<p>Começamos com variáveis aleatórias independentes <span class="math inline">\(X_1, X_2, \ldots\)</span>, geradas segundo a função densidade de probabilidade <span class="math inline">\(f_X(x \mid \theta)\)</span>, associada a um parâmetro desconhecido <span class="math inline">\(\theta\)</span>. A média comum das variáveis <span class="math inline">\(X_i\)</span>, denotada por <span class="math inline">\(\mu_X\)</span>, é uma função <span class="math inline">\(k(\theta)\)</span> de <span class="math inline">\(\theta\)</span>. Por exemplo, se as <span class="math inline">\(X_i\)</span> são variáveis aleatórias contínuas, então:</p>
<p><span class="math display">\[
\mu_X = \int_{-\infty}^{\infty} x f_X(x \mid \theta)\, dx = k(\theta).
\]</span></p>
<p>A Lei dos Grandes Números afirma que:</p>
<p><span class="math display">\[
\bar{X}_n = \frac{1}{n} \sum_{i=1}^{n} X_i \to \mu_X \quad \text{quando } n \to \infty.
\]</span></p>
<p>Assim, quando o número de observações <span class="math inline">\(n\)</span> é grande, a média da distribuição <span class="math inline">\(\mu = k(\theta)\)</span> pode ser bem aproximada pela média amostral, isto é:</p>
<p><span class="math display">\[
\bar{X} \approx k(\theta).
\]</span></p>
<p>Essa relação pode ser transformada em um estimador <span class="math inline">\(\hat{\theta}\)</span>, definindo:</p>
<p><span class="math display">\[
\bar{X} = k(\hat{\theta}),
\]</span></p>
<p>e resolvendo essa equação em relação a <span class="math inline">\(\hat{\theta}\)</span>.</p>
<p>Na sequência, descreveremos o procedimento no caso de um <strong>vetor de parâmetros</strong> e apresentaremos diversos exemplos. Veremos também que o <strong>método delta</strong> pode ser utilizado para estimar a variância dos estimadores obtidos pelo método dos momentos.</p>
</section>
<section id="procedimento-geral-do-método-dos-momentos" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="procedimento-geral-do-método-dos-momentos"><span class="header-section-number">4.2.2</span> Procedimento Geral do Método dos Momentos</h3>
<p>De forma mais geral, para variáveis aleatórias independentes <span class="math inline">\(X_1, X_2, \ldots\)</span>, geradas segundo uma distribuição associada ao parâmetro <span class="math inline">\(\theta\)</span>, e sendo <span class="math inline">\(m\)</span> uma função real, se <span class="math inline">\(k(\theta) =E_{\theta}[m(X_1)],\)</span> então</p>
<p><span class="math display">\[
\frac{1}{n} \sum_{i=1}^{n} m(X_i) \to k(\theta) \quad \text{quando } n \to \infty.
\]</span></p>
<p>O método dos momentos resulta das escolhas <span class="math inline">\(m(x) = x^m\)</span>. Denotamos</p>
<p><span class="math display">\[
\mu_m = E[X^m] = k_m(\theta). \tag{1}
\]</span></p>
<p>para o <span class="math inline">\(m\)</span>-ésimo momento.</p>
<p>Nosso procedimento de estimação segue os <strong>4 passos</strong> abaixo, que conectam os momentos amostrais aos parâmetros do modelo:</p>
</section>
<section id="passo-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-1">Passo 1</h3>
<p>Se o modelo possui <span class="math inline">\(d\)</span> parâmetros, calculamos as funções <span class="math inline">\(k_m\)</span> na equação (1) para os primeiros <span class="math inline">\(d\)</span> momentos:</p>
<p><span class="math display">\[
\mu_1 = k_1(\theta_1, \theta_2, \ldots, \theta_d), \quad
\mu_2 = k_2(\theta_1, \theta_2, \ldots, \theta_d), \quad \ldots \quad
\mu_d = k_d(\theta_1, \theta_2, \ldots, \theta_d),
\]</span></p>
<p>obtendo assim <span class="math inline">\(d\)</span> equações em <span class="math inline">\(d\)</span> incógnitas.</p>
</section>
<section id="passo-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-2">Passo 2</h3>
<p>Resolvemos esse sistema para os <span class="math inline">\(d\)</span> parâmetros como funções dos momentos:</p>
<p><span class="math display">\[
\theta_1 = g_1(\mu_1, \mu_2, \dots, \mu_d), \quad
\theta_2 = g_2(\mu_1, \mu_2, \dots, \mu_d), \quad \dots \quad
\theta_d = g_d(\mu_1, \mu_2, \dots, \mu_d). \tag{2}
\]</span></p>
</section>
<section id="passo-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-3">Passo 3</h3>
<p>Com base nos dados <span class="math inline">\(\mathbf{x} = (x_1, x_2, \ldots, x_n)\)</span>, calculamos os primeiros <span class="math inline">\(d\)</span> momentos amostrais:</p>
<p><span class="math display">\[
\bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_i, \quad
\overline{x^2} = \frac{1}{n} \sum_{i=1}^{n} x_i^2, \quad \ldots \quad
\overline{x^d} = \frac{1}{n} \sum_{i=1}^{n} x_i^d.
\]</span></p>
<p>Pela Lei dos Grandes Números, para cada momento <span class="math inline">\(m = 1, \ldots, d\)</span>, temos: <span class="math inline">\(\mu_m \approx \overline{x^m}.\)</span></p>
</section>
<section id="passo-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-4">Passo 4</h3>
<p>Substituímos os momentos populacionais <span class="math inline">\(\mu_m\)</span> pelos momentos amostrais <span class="math inline">\(\overline{x^m}\)</span>. Assim, as soluções em (2) fornecem as fórmulas dos estimadores de momentos <span class="math inline">\((\hat{\theta}_1, \hat{\theta}_2, \ldots, \hat{\theta}_d)\)</span>. Para os dados <span class="math inline">\(\mathbf{x}\)</span>, esses estimadores são dados por:</p>
<p><span class="math display">\[
\hat{\theta}_1(\mathbf{x}) = g_1(\bar{x}, \overline{x^2}, \cdots, \overline{x^d}), \quad
\hat{\theta}_2(\mathbf{x}) = g_2(\bar{x}, \overline{x^2}, \cdots, \overline{x^d}), \quad \ldots \quad
\hat{\theta}_d(\mathbf{x}) = g_d(\bar{x}, \overline{x^2}, \cdots, \overline{x^d}).
\]</span></p>
<p>A forma como essa descrição abstrata funciona na prática é melhor compreendida por meio de exemplos.</p>
</section>
</section>
<section id="exemplo-distribuição-de-pareto" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-distribuição-de-pareto">Exemplo: Distribuição de Pareto</h2>
<p>Sejam <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> uma amostra aleatória simples de variáveis aleatórias com distribuição de Pareto, cuja densidade é dada por:</p>
<p><span class="math display">\[
f_X(x \mid \theta) = \theta x^{-(\theta+1)}, \quad x &gt; 1.
\]</span></p>
<p>A função de distribuição acumulada é:</p>
<p><span class="math display">\[
F_X(x) = 1 - x^{-\theta}, \quad x &gt; 1.
\]</span></p>
<p>A média e a variância são, respectivamente:</p>
<p><span class="math display">\[
\mu = \frac{\theta}{\theta - 1}, \quad \sigma^2 = \frac{\theta}{(\theta - 1)^2(\theta - 2)}.
\]</span></p>
<p>Neste caso, temos apenas <strong>um parâmetro</strong>, <span class="math inline">\(\theta\)</span>. Assim, no <strong>Passo 1</strong>, precisamos apenas do primeiro momento:</p>
<p><span class="math display">\[
\mu_1 = \mu = k_1(\theta) = \frac{\theta}{\theta - 1}.
\]</span></p>
<section id="passo-2-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-2-1">Passo 2</h3>
<p>Resolvendo para <span class="math inline">\(\theta\)</span> em função da média <span class="math inline">\(\mu\)</span>:</p>
<p><span class="math display">\[
\theta = g_1(\mu) = \frac{\mu}{\mu - 1}.
\]</span></p>
</section>
<section id="passos-3-e-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passos-3-e-4">Passos 3 e 4</h3>
<p>Substituindo a média populacional pela média amostral <span class="math inline">\(\bar{X}\)</span>, obtemos o estimador de momentos:</p>
<p><span class="math display">\[
\hat{\theta} = \frac{\bar{X}}{\bar{X} - 1}.\]</span></p>
</section>
<section id="variância-via-método-delta" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="variância-via-método-delta">Variância via Método Delta</h3>
<p>Um bom estimador deve ter variância pequena. Para estimar a variância de <span class="math inline">\(\hat{\theta}\)</span>, utilizamos o <strong>método delta</strong>:</p>
<p><span class="math display">\[
\sigma^2_{\hat{\theta}} \approx \left[g_1'(\mu)\right]^2 \frac{\sigma^2}{n}.
\]</span></p>
<p>Calculamos a derivada:</p>
<p><span class="math display">\[
g_1'(\mu) = -\frac{1}{(\mu - 1)^2}.
\]</span></p>
<p>Substituindo <span class="math inline">\(\mu = \frac{\theta}{\theta - 1}\)</span>, obtemos:</p>
<p><span class="math display">\[
g_1'(\mu) = -(\theta - 1)^2.\]</span></p>
<p>Assim, a variância aproximada é:</p>
<p><span class="math display">\[
\sigma^2_{\hat{\theta}} \approx \frac{(\theta - 1)^4}{n} \cdot \frac{\theta}{(\theta - 1)^2(\theta - 2)} = \frac{\theta(\theta - 1)^2}{n(\theta - 2)}.\]</span></p>
</section>
<section id="exemplo-numérico" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exemplo-numérico">Exemplo Numérico</h3>
<p>Considere <span class="math inline">\(\theta = 3\)</span> e <span class="math inline">\(n = 100\)</span>:</p>
<p><span class="math display">\[
\sigma^2_{\hat{\theta}} \approx \frac{3(3 - 1)^2}{100(3 - 2)} = \frac{12}{100} = \frac{3}{25}.\]</span></p>
<p>Logo, o desvio padrão aproximado é:</p>
<p><span class="math display">\[
\sigma_{\hat{\theta}} \approx \sqrt{\frac{3}{25}} = 0{,}346.
\]</span></p>
</section>
<section id="simulação-em-r" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="simulação-em-r">Simulação em R</h3>
<p>Para simular uma variável aleatória com distribuição de Pareto, usamos o método da transformação inversa. Se <span class="math inline">\(U \sim \text{Uniforme}(0,1)\)</span>, então:</p>
<p><span class="math display">\[X = (1 - U)^{-1/\theta}.\]</span></p>
<p>Código em <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>paretobar <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">1000</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">14</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>){</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  v <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="dv">100</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  pareto <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> v<span class="sc">^</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  paretobar[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(pareto)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(paretobar, <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">bar</span>(X)), <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="unidade3_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>betahat <span class="ot">&lt;-</span> paretobar <span class="sc">/</span> (paretobar <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(betahat, <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">hat</span>(beta)), <span class="at">probability =</span> <span class="cn">TRUE</span>, <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="unidade3_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(betahat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.054922</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(betahat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3213791</code></pre>
</div>
</div>
<p>A média amostral do estimador de <span class="math inline">\(\theta\)</span>, igual a 3.0549, está próxima do valor verdadeiro do parâmetro considerado na simulação que foi <span class="math inline">\(3\)</span>. Neste exemplo, o estimador <span class="math inline">\(\hat{\theta}\)</span> apresenta <strong>viés positivo</strong>. Em outras palavras, em média, a estimativa é maior que o verdadeiro valor do parâmetro, isto é: <span class="math inline">\(E[\hat{\theta}] &gt; \theta\)</span>. O desvio padrão amostral, igual a 0.3214, é próximo do valor <strong>0.346</strong> estimado pelo método delta. Quando estudarmos <strong>estimadores não viesados</strong>, veremos que esse viés já poderia ter sido antecipado.</p>
</section>
</section>
<section id="exemplo-distribuição-uniforme-contínua" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-distribuição-uniforme-contínua">Exemplo: Distribuição Uniforme Contínua</h2>
<p>Considere <span class="math inline">\(X \sim U(0, \theta)\)</span>. Sabemos que:</p>
<p><span class="math display">\[\mu = \frac{\theta}{2} \quad \text{e} \quad \sigma^2 = \frac{\theta^2}{12}.\]</span></p>
<section id="passo-1-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-1-1">Passo 1</h3>
<p>Neste caso, também temos apenas <strong>um parâmetro</strong>, <span class="math inline">\(\theta\)</span>. Assim, no <strong>Passo 1</strong>, precisamos apenas do primeiro momento:</p>
<p><span class="math display">\[
\mu_1 = \mu = k_1(\theta) = \frac{\theta}{2}.
\]</span></p>
</section>
<section id="passo-2-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-2-2">Passo 2</h3>
<p>Resolvendo para <span class="math inline">\(\theta\)</span> em função da média <span class="math inline">\(\mu\)</span>:</p>
<p><span class="math display">\[
\theta = g_1(\mu) = 2\mu.
\]</span></p>
</section>
<section id="passos-3-e-4-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passos-3-e-4-1">Passos 3 e 4</h3>
<p>Substituindo a média populacional pela média amostral <span class="math inline">\(\bar{X}\)</span>, obtemos o estimador de momentos:</p>
<p><span class="math display">\[\hat{\theta} = 2\bar{X}.\]</span></p>
</section>
<section id="esperança-e-variância" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="esperança-e-variância">Esperança e Variância</h3>
<p>Como o estimador obtido pelo MoM é função linear da média amostral, então é fácil obter seu valor esperado, basta usar propriedades de valores esperado e o fato de <span class="math inline">\(E(\bar{X}) = \mu\)</span>. Assim, temos que</p>
<p><span class="math display">\[E(\hat{\theta})  = 2E(\bar{X}) = 2\left(\frac{\theta}{2}\right) = \theta.\]</span></p>
<p>portanto, <span class="math inline">\(\hat{\theta}\)</span> é um estimador não viciado. De maneira similar, podemos obter a expressão da variância de <span class="math inline">\(\hat{\theta}\)</span>, usando propriedades de variância e o fato de <span class="math inline">\(Var(\bar{X}) = \sigma^2/n\)</span>. Desta forma, temos que:</p>
<p><span class="math display">\[Var(\hat{\theta}) = 4Var(\bar{X}) = 4\left(\frac{\theta^2/12}{n}\right) = \frac{\theta^2}{3n}.\]</span> Além disso, pela Lei dos Grandes Números, temos que <span class="math inline">\(\bar{X} \xrightarrow{p} \mu\)</span> quando <span class="math inline">\(n \to \infty\)</span>. Agora, usamos o fato de que a convergência em probabilidade é preservada por funções contínuas (no caso, multiplicar por 2):</p>
<p><span class="math display">\[\hat{\theta} = 2\bar{X} \xrightarrow{p} \theta,\]</span></p>
<p>mostrando que o estimador também é <strong>consistente</strong>.</p>
<blockquote class="blockquote">
<p><strong>Observação:</strong> Neste caso específico, o estimador de momentos coincide com um estimador simples baseado na média. No entanto, para a distribuição uniforme, o estimador de máxima verossimilhança é <span class="math inline">\(\hat{\theta}_{MV} = \max(X_1, \dots, X_n)\)</span>, o que levanta uma interessante comparação entre métodos de estimação.</p>
</blockquote>
</section>
</section>
<section id="exemplo-distribuição-uniforme-discreta" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-distribuição-uniforme-discreta">Exemplo: Distribuição Uniforme Discreta</h2>
<p>Considere <span class="math inline">\(X \sim U_d(A)\)</span> com <span class="math inline">\(A = {1, 2, \ldots, \theta}\)</span> e <span class="math inline">\(\theta \in \Theta = \{1, 2, \ldots\}\)</span>. Sabemos que:</p>
<p><span class="math display">\[\mu = E_{\theta}(X) = \frac{1+\theta}{2} \quad \text{e} \quad \sigma^2 = V(X) = \frac{\theta^2 - 1}{12}.\]</span></p>
<section id="passo-1-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-1-2">Passo 1</h3>
<p>Neste caso, temos apenas um parâmetro, <span class="math inline">\(\theta\)</span>. Assim, utilizamos o primeiro momento:</p>
<p><span class="math display">\[\mu_1 = \mu = k_1(\theta) = \frac{1+\theta}{2}.\]</span></p>
</section>
<section id="passo-2-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-2-3">Passo 2</h3>
<p>Resolvendo para <span class="math inline">\(\theta\)</span> em função da média <span class="math inline">\(\mu\)</span>:</p>
<p><span class="math display">\[\theta = g_1(\mu) = 2\mu -1.\]</span></p>
</section>
<section id="passos-3-e-4-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passos-3-e-4-2">Passos 3 e 4</h3>
<p>Substituindo a média populacional pela média amostral <span class="math inline">\(\bar{X}\)</span>, obtemos o estimador de momentos:</p>
<p><span class="math display">\[\hat{\theta} = 2\bar{X} - 1.\]</span></p>
</section>
<section id="esperança-e-variância-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="esperança-e-variância-1">Esperança e Variância</h3>
<p>Como o estimador obtido pelo método dos momentos é uma função linear da média amostral, podemos utilizar propriedades do valor esperado. Sabendo que <span class="math inline">\(E(\bar{X}) = \mu\)</span>, temos:</p>
<p><span class="math display">\[E(\hat{\theta}) = 2E(\bar{X}) - 1 = 2\left(\frac{1+\theta}{2}\right) - 1 = \theta.\]</span> Portanto, <span class="math inline">\(\hat{\theta}\)</span> é um estimador não viesado.</p>
<p>De maneira similar, utilizando o fato de que <span class="math inline">\(Var(\bar{X}) = \sigma^2/n\)</span>, obtemos:</p>
<p><span class="math display">\[Var(\hat{\theta}) = 4Var(\bar{X}) = \frac{\theta^2-1}{3n}.\]</span> Além disso, como <span class="math inline">\(\hat{\theta}\)</span> é um estimador não viesado e sua variância é igual a zero, quando <span class="math inline">\(n \to \infty\)</span>, logo <span class="math inline">\(\hat{\theta}\)</span> é um estimador consistente.</p>
</section>
<section id="comparação-com-o-estimador-de-máxima-verossimilhança" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="comparação-com-o-estimador-de-máxima-verossimilhança">Comparação com o Estimador de Máxima Verossimilhança</h3>
<p>Para a distribuição uniforme discreta, o estimador de máxima verossimilhança é dado por:</p>
<p><span class="math display">\[\hat{\theta}_{MV} = \max(X_1, X_2, \dots, X_n).\]</span> Esse resultado decorre do fato de que a função de verossimilhança é constante para <span class="math inline">\(\theta \geq \max(X_i)\)</span> e nula caso contrário, sendo maximizada no menor valor possível de <span class="math inline">\(\theta\)</span> que ainda torna a amostra observável.</p>
<p><strong>Comparação entre os estimadores</strong></p>
<ul>
<li><p>O estimador de momentos, <span class="math inline">\(\hat{\theta}_{\text{MoM}} = 2\bar{X} - 1\)</span>, utiliza toda a informação da amostra, mas pode assumir valores não inteiros.</p></li>
<li><p>O estimador de máxima verossimilhança, <span class="math inline">\(\hat{\theta}_{\text{MV}} = \max(X_1, X_2, \dots, X_n)\)</span>, depende apenas do maior valor observado, mas sempre pertence ao espaço paramétrico.</p></li>
</ul>
<p>Além disso:</p>
<ul>
<li><p><span class="math inline">\(\hat{\theta}_{\text{MoM}}\)</span> é não viesado.</p></li>
<li><p><span class="math inline">\(\hat{\theta}_{\text{MV}}\)</span> é viesado (subestima o valor verdadeiro), pois <span class="math inline">\(E(\max(X_1, X_2, \dots, X_n)) &lt; \theta\)</span>, embora seja consistente.</p></li>
</ul>
<p>Essa comparação ilustra uma diferença fundamental entre métodos de estimação: enquanto o método dos momentos busca reproduzir características médias da distribuição, o método de máxima verossimilhança está diretamente ligado à plausibilidade dos dados observados.</p>
</section>
</section>
<section id="exemplo-distribuição-exponencial" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-distribuição-exponencial">Exemplo: Distribuição Exponencial</h2>
<p>Considere <span class="math inline">\(X \sim \text{Exp}(\theta)\)</span>. Sabemos que:</p>
<p><span class="math display">\[\mu = E(X) = \frac{1}{\theta}\quad \text{e} \quad \sigma^2 = V(X) = \frac{1}{\theta^2}.\]</span></p>
<section id="passo-1-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-1-3">Passo 1</h3>
<p>Neste caso, temos apenas um parâmetro, <span class="math inline">\(\lambda\)</span>. Assim, utilizamos o primeiro momento:</p>
<p><span class="math display">\[\mu_1 = \mu = k_1(\theta) = \frac{1}{\theta}.\]</span></p>
</section>
<section id="passo-2-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-2-4">Passo 2</h3>
<p>Resolvendo para <span class="math inline">\(\theta\)</span> em função da média <span class="math inline">\(\mu\)</span>:</p>
<p><span class="math display">\[\theta = g_1(\mu) = \frac{1}{\mu}.\]</span></p>
</section>
<section id="passos-3-e-4-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passos-3-e-4-3">Passos 3 e 4</h3>
<p>Substituindo a média populacional pela média amostral <span class="math inline">\(\bar{X}\)</span>, obtemos o estimador de momentos:</p>
<p><span class="math display">\[\hat{\theta} = \frac{1}{\bar{X}}.\]</span></p>
</section>
<section id="esperança-e-variância-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="esperança-e-variância-2">Esperança e Variância</h3>
<p>Note que o estimador <span class="math inline">\(\hat{\theta}\)</span> não é uma função linear da média amostral, o que torna a análise de suas propriedades um pouco mais envolvida. Sabemos que <span class="math inline">\(S = \sum_{i=1}^n X_i \sim \text{Gama}(n, \theta)\)</span>, o que implica que:</p>
<p><span class="math display">\[\bar{X} \sim \text{Gama}(n, n\theta).\]</span> Além disso, é possível mostrar que <span class="math inline">\(\hat{\theta} = 1/\bar{X}\)</span> segue uma distribuição gama inversa (GI) de parâmetros <span class="math inline">\(n\)</span> e <span class="math inline">\(n\theta\)</span>, ou seja</p>
<p><span class="math display">\[\frac{1}{\bar{X}} \sim \text{GI}(n, n\theta).\]</span> Consequentemente, a média e a variância são:</p>
<p><span class="math display">\[E(\hat{\theta}) = \frac{n\theta}{n-1}\; (n&gt;1) \quad \text{e} \quad Var(\hat{\theta}) = \frac{n^2\theta^2}{(n-1)^2(n-2)}\; (n&gt;2).\]</span></p>
<p>Além disso, como <span class="math inline">\(\bar{X} \xrightarrow{p} \mu = \frac{1}{\theta}\)</span> quando <span class="math inline">\(n \to \infty\)</span>, segue que:</p>
<p><span class="math display">\[\hat{\theta} = \frac{1}{\bar{X}} \xrightarrow{p} \theta,\]</span> pois a função <span class="math inline">\(g(x)=1/x\)</span> é quase-certamente contínua, i.e., é contínua no suporte considerado, mostrando que o estimador é consistente.</p>
</section>
</section>
<section id="exemplo-distribuição-gama" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-distribuição-gama">Exemplo: Distribuição Gama</h2>
<p>Considere <span class="math inline">\(X \sim \text{Gama}(\theta_1, \theta_2)\)</span>, em que:</p>
<p><span class="math display">\[
\mu = E[X] = \frac{\theta_1}{\theta_2}, \quad \text{e}\quad \sigma^2 = Var(X) = \frac{\theta_1}{\theta_2^2}.
\]</span></p>
<section id="passo-1-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-1-4">Passo 1</h3>
<p>Neste caso, temos dois parâmetros, <span class="math inline">\(\alpha\)</span> e <span class="math inline">\(\beta\)</span>. Assim, utilizamos o primeiro e o segundo momento:</p>
<p><span class="math display">\[\mu_1 = k_1(\theta_1, \theta_2) = \frac{\theta_1}{\theta_2} \quad \text{e}\quad \mu_2 = k_2(\theta_1, \theta_2) = \frac{\theta_1(1 + \theta_1)}{\theta_2^2}.\]</span></p>
</section>
<section id="passo-2-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-2-5">Passo 2</h3>
<p>Resolvendo para <span class="math inline">\(\theta_1\)</span> e <span class="math inline">\(\theta_2\)</span> em função de <span class="math inline">\(\mu_1\)</span> e <span class="math inline">\(\mu_2\)</span>:</p>
<p><span class="math display">\[\theta_1 = g(\mu_1, \mu_2) = \frac{\mu_1^2}{\mu_2 - \mu_1^2} \quad \text{e} \quad \theta_2 = g(\mu_1, \mu_2) = \frac{\mu_1}{\mu_2 - \mu_1^2}.\]</span></p>
</section>
<section id="passos-3-e-4-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passos-3-e-4-4">Passos 3 e 4</h3>
<p>Substituindo a média populacional pela média amostral <span class="math inline">\(\bar{X}\)</span> e segundo momento populacional pelo segundo momento amostral, obtemos os seguintes estimadores de momentos:</p>
<p><span class="math display">\[
\widehat{\theta}_1 = \frac{\bar{X}^2}{\widehat{\sigma}^2} \quad \text{e} \quad \widehat{\theta}_2 = \frac{\bar{X}}{\widehat{\sigma}^2}
\]</span></p>
<p>em que:</p>
<p><span class="math display">\[
\widehat{\sigma}^2 = \frac{1}{n} \sum_{i=1}^{n} X_i^2 - \bar{X}^2.
\]</span></p>
<div class="callout callout-style-default callout-caution callout-titled" title="Exercícios">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercícios
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>O <strong>múon</strong> é uma partícula elementar com carga elétrica <span class="math inline">\(-1\)</span> e spin (momento angular intrínseco) igual a <span class="math inline">\(\frac{1}{2}\)</span>. Trata-se de uma partícula subatômica instável com tempo de vida médio de <span class="math inline">\(2{,}2 \, \mu s\)</span>.</li>
</ol>
<p>Os múons possuem massa aproximadamente <strong>200 vezes maior</strong> que a massa do elétron. Como o múon tem a mesma carga e spin que o elétron, ele pode ser visto como uma versão muito mais pesada do elétron.</p>
<p>A colisão de um feixe de prótons (<span class="math inline">\(p\)</span>) acelerados, com energia de <span class="math inline">\(600 \, \text{MeV}\)</span> (milhões de elétron-volts), com os núcleos de um alvo de produção gera píons positivos (<span class="math inline">\(\pi^+\)</span>) por meio de uma das seguintes reações:</p>
<p><span class="math display">\[p + p \rightarrow p + n + \pi^+ \quad \text{ou} \quad p + n \rightarrow n + n + \pi^+.\]</span></p>
<p>A partir do decaimento subsequente dos píons (tempo de vida médio de <span class="math inline">\(26{,}03 \, \text{ns}\)</span>), múons positivos (<span class="math inline">\(\mu^+\)</span>) são formados via o decaimento de dois corpos:</p>
<p><span class="math display">\[
\pi^+ \rightarrow \mu^+ + \nu_\mu,
\]</span></p>
<p>em que <span class="math inline">\(\nu_\mu\)</span> representa o <strong>neutrino do múon</strong>.</p>
<p>O decaimento do múon em um pósitron (<span class="math inline">\(e^+\)</span>), um neutrino do elétron (<span class="math inline">\(\nu_e\)</span>) e um antineutrino do múon (<span class="math inline">\(\bar{\nu}_\mu\)</span>):</p>
<p><span class="math display">\[
\mu^+ \rightarrow e^+ + \nu_e + \bar{\nu}_\mu,
\]</span></p>
<p>possui uma distribuição angular <span class="math inline">\(t\)</span> com densidade dada por:</p>
<p><span class="math display">\[
f(t \mid \alpha) = \frac{1}{2\pi} (1 + \alpha \cos t), \quad 0 \leq t \leq 2\pi,
\]</span></p>
<p>em que <span class="math inline">\(t\)</span> é o ângulo entre a trajetória do pósitron e o spin do <span class="math inline">\(\mu^+\)</span>, e o parâmetro de anisotropia <span class="math inline">\(\alpha \in [-1/3, 1/3]\)</span> depende da polarização do feixe de múons e da energia do pósitron. Com base nas observações <span class="math inline">\(t_1, \ldots, t_n\)</span>, obtenha o estimador de momentos <span class="math inline">\(\hat{\alpha}\)</span> para <span class="math inline">\(\alpha\)</span>.</p>
<p><strong>Observação:</strong> Neste caso, a média é igual a <span class="math inline">\(\pi\)</span> para todos os valores de <span class="math inline">\(\alpha\)</span>. Portanto, será necessário utilizar o <strong>segundo momento</strong> para obter um estimador.</p>
<ol start="2" type="1">
<li><p>Sejam <span class="math inline">\(x_1, x_2, \ldots, x_n\)</span> uma amostra i.i.d. de <span class="math inline">\(X \sim N(\theta_1, \theta_2)\)</span>, em que <span class="math inline">\(\theta_1\)</span> é a média e <span class="math inline">\(\theta_2\)</span> é a variância. Queremos obter o estimador de momentos para o vetor de parâmetros: <span class="math inline">\(\theta = (\theta_1, \theta_2)\)</span>. Verifique se o estimador é viesado e obtenha sua variância.</p></li>
<li><p>Verifique se os estimadores de momentos dos parâmetros que indexam a distribuição gama são consistentes.</p></li>
</ol>
</div>
</div>
</section>
</section>
<section id="método-de-máxima-verossimilhança" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="método-de-máxima-verossimilhança"><span class="header-section-number">4.3</span> Método de Máxima Verossimilhança</h2>
<p>Nesta seção, apresentamos exemplos de estimação por máxima verossimilhança (MV). A ideia central é simples:</p>
<blockquote class="blockquote">
<p>Encontrar o valor de <span class="math inline">\(\theta\)</span> que maximiza a verossimilhança dos dados observados.</p>
</blockquote>
<p>Na Estimação por MV, utilizamos uma amostra iid <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> de alguma distribuição com parâmetro(s) desconhecido(s) <span class="math inline">\(\theta\)</span>, com o objetivo de estimar <span class="math inline">\(\theta\)</span>.</p>
<p><span class="math display">\[\hat{\theta} = \arg\max_\theta L(\theta \mid x) = \arg\max_\theta \prod_{i=1}^n f_X(x_i \mid \theta).\]</span></p>
<p><strong>Observação:</strong> Recorde que, na descrição em palavras, o que fizemos para encontrar <span class="math inline">\(\hat{\theta}\)</span> foi calcular a verossimilhança; que é a probabilidade de observar os dados dado o parâmetro <span class="math inline">\(\theta\)</span>; e escolher o “melhor” <span class="math inline">\(\theta\)</span> , ou seja, aquele que maximiza essa verossimilhança.</p>
</section>
<section id="exemplo-emv-poisson" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-emv-poisson">Exemplo EMV (Poisson)</h2>
<p>Suponha que <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> sejam amostras iid de uma distribuição Poisson com parâmetro <span class="math inline">\(\theta\)</span>. Qual é o EMV de <span class="math inline">\(\theta\)</span>?</p>
<section id="passo-1-calcule-a-verossimilhança-e-a-log-verossimilhança-dos-dados" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-1-calcule-a-verossimilhança-e-a-log-verossimilhança-dos-dados">Passo 1: Calcule a verossimilhança e a log-verossimilhança dos dados</h3>
<p>Para fazer isso, tomamos o seguinte produto das funções de probabilidade (FP’s) da Poisson em cada observação <span class="math inline">\(x_i\)</span>, considerando todos os pontos de dados.</p>
<p><span class="math display">\[L(\theta \mid x) = \prod_{i=1}^n \frac{e^{-\theta} \theta^{x_i}}{x_i!}.\]</span></p>
<p>Novamente, isso representa a probabilidade de observar <span class="math inline">\(x_1\)</span>, depois <span class="math inline">\(x_2\)</span>, e assim por diante. Essa função é bastante difícil de derivar, então, para facilitar, vamos calcular a log-verossimilhança, utilizando as seguintes identidades:</p>
<p><span class="math display">\[\ln(ab) = \ln(a) + \ln(b),\quad \ln(a/b) = \ln(a) - \ln(b), \quad \text{e} \quad \ln(a^b) = b \ln(a).\]</span></p>
<p>Na maioria dos casos, queremos otimizar a log-verossimilhança em vez da verossimilhança (pois não queremos utilizar a regra do produto do cálculo)!</p>
<p><span class="math display">\[\begin{aligned}
\ln(L(\theta \mid x)) &amp;=  \ln\left(\prod_{i=1}^n \frac{e^{-\theta} \theta^{x_i}}{x_i!}\right) \\
&amp;=  \sum_{i=1}^n \ln\left(\frac{e^{-\theta} \theta^{x_i}}{x_i!}\right) \\
&amp;= \sum_{i=1}^n\left[\ln(e^{-\theta}) + \ln(\theta^{x_i}) - \ln(x_i!)\right] \\
&amp;= \sum_{i=1}^n \left(-\theta + x_i \ln \theta - \ln(x_i!)\right).
\end{aligned}\]</span></p>
</section>
<section id="passo-2-calcule-as-derivadas-parcialis-em-relação-a-theta-e-iguale-a-zero.-resolva-as-equaçãoões" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-2-calcule-as-derivadas-parcialis-em-relação-a-theta-e-iguale-a-zero.-resolva-as-equaçãoões">Passo 2: Calcule a(s) derivada(s) parcial(is) em relação a <span class="math inline">\(\theta\)</span> e iguale a zero. Resolva a(s) equação(ões)</h3>
<p>Agora queremos calcular a derivada da log-verossimilhança em relação a <span class="math inline">\(\theta\)</span>. A derivada de <span class="math inline">\(-\theta\)</span> é simplesmente <span class="math inline">\(-1\)</span>, e a derivada de <span class="math inline">\(x_i \ln(\theta)\)</span> é <span class="math inline">\(\frac{x_i}{\theta}\)</span>, pois lembre-se de que <span class="math inline">\(x_i\)</span> é constante em relação a <span class="math inline">\(\theta\)</span>.</p>
<p><span class="math display">\[\frac{\partial \ln(L(\theta \mid x))}{\partial \theta} = \sum_{i=1}^n \left(-1 + \frac{x_i}{\theta}\right).\]</span></p>
<p>Agora, igualamos a derivada a zero e resolvemos para <span class="math inline">\(\theta\)</span>. O valor <span class="math inline">\(\hat{\theta}\)</span> é justamente o estimador que queremos encontrar. Fazendo alguma álgebra, obtemos:</p>
<p><span class="math display">\[\sum_{i=1}^n \left(-1 + \frac{x_i}{\theta}\right) = 0,\]</span></p>
<p><span class="math display">\[-n + \frac{1}{\hat{\theta}}\sum_{i=1}^n x_i = 0,\]</span></p>
<p><span class="math display">\[\hat{\theta} = \frac{1}{n}\sum_{i=1}^n x_i.\]</span></p>
<p>Ou seja, o estimador de máxima verossimilhança é simplesmente a média amostral, <span class="math inline">\(\bar{X}\)</span>.</p>
</section>
<section id="passo-3-opcionalmente-verifique-se-hattheta-é-de-fato-um-máximo-local-checando-se-a-segunda-derivada-em-hattheta-é-negativa-quando-theta-é-um-único-parâmetro-ou-se-a-hessiana-matriz-das-segundas-derivadas-parciais-é-negativa-semidefinida-quando-theta-é-um-vetor-de-parâmetros" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="passo-3-opcionalmente-verifique-se-hattheta-é-de-fato-um-máximo-local-checando-se-a-segunda-derivada-em-hattheta-é-negativa-quando-theta-é-um-único-parâmetro-ou-se-a-hessiana-matriz-das-segundas-derivadas-parciais-é-negativa-semidefinida-quando-theta-é-um-vetor-de-parâmetros">Passo 3: Opcionalmente, verifique se <span class="math inline">\(\hat{\theta}\)</span> é de fato um máximo (local), checando se a segunda derivada em <span class="math inline">\(\hat{\theta}\)</span> é negativa (quando <span class="math inline">\(\theta\)</span> é um único parâmetro), ou se a Hessiana (matriz das segundas derivadas parciais) é negativa semidefinida (quando <span class="math inline">\(\theta\)</span> é um vetor de parâmetros)</h3>
<p>Também queremos calcular a segunda derivada, pois, caso contrário, não sabemos se o ponto encontrado é um máximo ou um mínimo. Derivamos novamente a primeira derivada <span class="math inline">\(\sum_{i=1}^n \left(-1 + \frac{x_i}{\theta}\right)\)</span> em relação a <span class="math inline">\(\theta\)</span>, e observamos que, como <span class="math inline">\(\theta^2\)</span> é sempre positivo, o seu negativo é sempre negativo. Assim, a segunda derivada é sempre menor que zero, o que implica que a função é côncava para baixo em todo o domínio.</p>
<p>Isso significa que qualquer ponto onde a derivada seja zero corresponde a um máximo global. Portanto, encontramos com sucesso o máximo global da função de verossimilhança.</p>
<p><span class="math display">\[
\frac{\partial^2 \ln(L(\theta \mid x))}{\partial \theta^2} = \sum_{i=1}^n \left(-\frac{x_i}{\theta^2}\right) &lt; 0. \quad \text{(côncava para baixo em todo o domínio)}
\]</span></p>
</section>
</section>
<section id="exemplo-emv-exponencial" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-emv-exponencial">Exemplo EMV (Exponencial)</h2>
<p>Suponha que <span class="math inline">\(X_1, X_2, \dots, X_n \overset{iid}{\sim} \text{Exp}(\theta)\)</span>, em que <span class="math inline">\(\theta &gt; 0\)</span> é a taxa. Encontre o EMV de <span class="math inline">\(\theta\)</span>.</p>
</section>
<section id="exemplo-emv-uniforme-discreta" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-emv-uniforme-discreta">Exemplo EMV (Uniforme Discreta)</h2>
<p>Suponha que <span class="math inline">\(X_1, X_2, \dots, X_n \overset{iid}{\sim} U_d(A)\)</span> com <span class="math inline">\(A = {1, 2, \ldots, \theta}\)</span> e <span class="math inline">\(\theta \in \Theta = \{1, 2, \ldots\}\)</span>. Encontre o EMV de <span class="math inline">\(\theta\)</span>.</p>
</section>
<section id="exemplo-emv-uniforme-continua" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-emv-uniforme-continua">Exemplo EMV (Uniforme Continua)</h2>
<p>Suponha que <span class="math inline">\(X_1, X_2, \dots, X_n \overset{iid}{\sim} \text{Unif}(0, \theta)\)</span>, em que <span class="math inline">\(\theta &gt; 0\)</span>. Encontre o EMV de <span class="math inline">\(\theta\)</span>.</p>
</section>
<section id="exemplo-emv-normal-inversa" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-emv-normal-inversa">Exemplo EMV (Normal Inversa)</h2>
<p>Suponha que <span class="math inline">\(X_1, X_2, \dots, X_n \overset{iid}{\sim} \mathcal{NI}(\theta_1, \theta_2)\)</span>, em que <span class="math inline">\(\theta_1\)</span> é a média e <span class="math inline">\(\theta_2\)</span> é o parâmetro de forma. Encontre os EMV de <span class="math inline">\(\theta_1\)</span> e <span class="math inline">\(\theta_2\)</span>.</p>
</section>
<section id="exemplo-emv-birnbaum-saunders" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-emv-birnbaum-saunders">Exemplo EMV (Birnbaum-Saunders)</h2>
<p>Suponha que <span class="math inline">\(X_1, X_2, \dots, X_n \overset{iid}{\sim} \mathcal{BS}(\theta_1, \theta_2)\)</span>, em que <span class="math inline">\(\theta_1\)</span> é o parâmetro de forma e <span class="math inline">\(\theta_2\)</span> é o parâmetro de escala. Encontre os EMV de <span class="math inline">\(\theta_1\)</span> e <span class="math inline">\(\theta_2\)</span>.</p>
</section>
<section id="exemplo-emv-normal" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="exemplo-emv-normal">Exemplo EMV (Normal)</h2>
<p>Suponha que <span class="math inline">\(X_1, X_2, \dots, X_n \overset{iid}{\sim} \mathcal{N}(\theta_1, \theta_2)\)</span>, em que <span class="math inline">\(\theta_1\)</span> é a média e <span class="math inline">\(\theta_2\)</span> é a variância. Encontre os EMV de <span class="math inline">\(\theta_1\)</span> e <span class="math inline">\(\theta_2\)</span>.</p>
</section>
<section id="método-de-mínimos-quadrados" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="método-de-mínimos-quadrados"><span class="header-section-number">4.4</span> Método de Mínimos Quadrados</h2>
<p>Ver <a href="https://statlab-oficial.github.io/ModelosdeRegressao/demo.html#demonstra%C3%A7%C3%A3o-de-que-hat-beta_0-e-hat-beta_1-s%C3%A3o-os-estimadores-de-mqo-em-mrls">Link</a>!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./unidade2.html" class="pagination-link" aria-label="Distribuições Amostrais">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Distribuições Amostrais</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./unidade4.html" class="pagination-link" aria-label="Estimação por Intervalos: Intervalo de Confiança">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimação por Intervalos: Intervalo de Confiança</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>